### ISSUE TITLE
Gulp support etc 

### ISSUE THREAD

**Issue by yeomann** [Automattic/_s#1002]
I wonder that why there is no support for any work flow introduced by _s team. For such nice starter theme, I think, It should include any workflow tool like gulp or grunt for automating tasks such as sass etc?

**Comment by slushman** [comment]
I believe the philosophy is this is a starter theme, so any developer-level customizations/decisions, like using Gulp (vs Grunt, Codekit, node.js, or whatever) would be left to the individual developers and/or projects. 

I'm using Gulp with my fork of _s and plan to release a gulpfile specifically for dropping into _s based projects.

**Comment by alaczek** [comment]
Same issue was brought up and discussed a while back for Grunt integration (see #585). As @slushman said, using a build tool is a developer decision and left to individual developers.
Therefore I'm gonna close this issue, but I'd like to encourage you to fork _s and implement Gulp for yourself.
