### ISSUE TITLE
CSS render error: grey text in grey background in Chromium on main website

### ISSUE THREAD

**Issue by COLABORATI** [Automattic/_s#1004]
there is a css rendering error on the main website in chromium, there is grey text on grey bacground, what is barelky readable, please see attached screenshot. Please add some contrast, so people can actually read that text, thank you!
![2016-08-09_underscores-grey-grey](https://cloud.githubusercontent.com/assets/6514273/17511240/56fbda06-5e22-11e6-9950-553aa4ae6048.png)

**Comment by grappler** [comment]
Issues with the website should be opened here: https://github.com/Automattic/underscores.me/issues/new

**Comment by alaczek** [comment]
This issue has been moved to Automattic/underscores.me#49 so I'm closing this one.
@COLABORATI thank you for reporting!
