### ISSUE TITLE
Changing Slug for Default post type (Not Working)

### ISSUE THREAD

**Issue by kala725** [Automattic/_s#1010]
add_action( 'init', function() { 
    $post_type_args = get_post_type_object('post');
    $post_type_args->rewrite = array( 'slug' => 'article', 'permastruct' => 'article/%postname%');
    $post_type_args->has_archive = true;

    register_post_type('post', $post_type_args);
} );

Can you tell me, why the above code doesnot work.

**Comment by thomasguillot** [comment]
This has nothing to do with _s, please use WordPress.org forums.

**Comment by philiparthurmoore** [comment]
@kala725, you'll find those forums here: https://wordpress.org/support/

If you're unable to get assistance there, I suggest looking into Google or the StackExchange WordPress board for help.  

Thanks for understanding and if you run into any issues with _s in the future, please don't hesitate to open an issue, even if you're not sure if it belongs here.

(In general, tickets directly related to the theme itself are answered. Everything outside of that is not. Thanks again.)
