### ISSUE TITLE
hey there issue in the content-single

### ISSUE THREAD

**Issue by Un1xMida** [Automattic/_s#1015]
greetings guys , 
am following lynda course that mentioned template called content-single.php inside the template-parts folder but unfortunately i cant find it under my template-parts folder

**Comment by josephfusco** [comment]
Hey @Un1xMida ,

It was decided to be taken out of this project last December (see commit https://github.com/Automattic/_s/commit/60f7311f1977179822e83c95745fa6787894959a). The video might be referencing an older version of the project.

Also see https://github.com/Automattic/_s/issues/948

Hope this helps.

**Comment by Un1xMida** [comment]
hmmmmmm ok how can i handle it ?

**Comment by josephfusco** [comment]
The template part for displaying post in this case would be [content.php](https://github.com/Automattic/_s/blob/master/template-parts/content.php).

**Comment by Un1xMida** [comment]
thanks allot buddy :laughing: have a good day .
