### ISSUE TITLE
rel="designer" in footer link

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#1016]
I was wondering why there is `rel="designer"` in footer credit link? It seems that it's invalid html attribute and doesn't have any meaning.

**Comment by mrwweb** [comment]
In fact, shouldn't it be `rel="nofollow"`? From [WHATWG](https://blog.whatwg.org/the-road-to-html-5-link-relations#rel-nofollow):

> rel=nofollow "indicates that the link is not endorsed by the original author or publisher of the page, or that the link to the referenced document was included primarily because of a commercial relationship between people affiliated with the two pages."

**Comment by samikeijonen** [comment]
Could be, or nothing at all. That would be my best guess. It's just a link.

**Comment by stevengliebe** [comment]
It seems Google suggests that if a credit link is used in the footer, it should be nofollow.

https://www.seroundtable.com/google-nofollow-web-design-by-links-19943.html

**Comment by jdevalk** [comment]
`nofollow` would make more sense than `designer`, as that's at least an allowed attribute value :) 

But I'd be fine with just removing the `rel=` too.

**Comment by samikeijonen** [comment]
Now there is PR #1050 for removing `rel="designer"`.

**Comment by SergeyBiryukov** [comment]
> Now there is PR #1050 for removing rel="designer".

Duplicate of #1020?

**Comment by samikeijonen** [comment]
Yes, sorry it's duplicate. Let's go with #1020.
