### ISSUE TITLE
Separate Blog Page loop?

### ISSUE THREAD

**Issue by Kusnezow1** [Automattic/_s#1025]
Hey Guys, 

I have following problem. I want to create a page besides the index.php which shows all posts of the website, but the loop of the index.php does not work, it shows me the blog page itself as a separate post.

<?php
    if ( have_posts() ) :
    if ( is_home() && ! is_front_page() ) : ?>
    <header>
    <h3 class="card-title"><?php single_post_title(); ?></h3>
    </header>
    <?php
    endif;
    /\* Start the Loop _/
    while ( have_posts() ) : the_post();
    /_
    \* Include the Post-Format-specific template for the content.
     If you want to override this in a child theme, then include a file
    \* called content-___.php (where ___ is the Post Format name) and that will be used instead.
    */
    get_template_part( 'template-parts/content', get_post_format() );
    endwhile;
    the_posts_navigation();
    else :
    et_template_part( 'template-parts/content', 'none' );
    endif; 
?>

How do I create a separate and WORKING loop? its on this page: https://vladimirkusnezow.de/blog/

**Comment by karmatosed** [comment]
This repository isn't really for getting help writing your code. Unfortunately, we have to focus and that mens you haven't got a response.
