### ISSUE TITLE
Javascript calls on wp_footer

### ISSUE THREAD

**Issue by carlos-andres** [Automattic/_s#1029]
Good Day, 

i like to know how to move Javascript wordpress files {like: jquery, admin-bar, etc} to header. but i don´t see any options on functions.php file.. 

![image](https://cloud.githubusercontent.com/assets/5489747/18897592/2e0011bc-84f1-11e6-9394-412e028420f9.png)

any help will be greatly appreciated, and many thanks

**Comment by grappler** [comment]
GitHub is used to track issues with the theme and not to provide support.

For support please check the forums: https://wordpress.org/support/ or Stack exchange https://wordpress.stackexchange.com/

If I remember correctly it would be something like

```php
	// Move jQuery to the footer
	wp_scripts()->add_data( 'jquery', 'group', 1 );
	wp_scripts()->add_data( 'jquery-core', 'group', 1 );
	wp_scripts()->add_data( 'jquery-migrate', 'group', 1 );
```

**Comment by carlos-andres** [comment]
Thanks @grappler 

you´re right but its rather curious to me that when I activate the template generated in http://underscores.me/ in wp_footer feature is placing calls to all js 

Many thanks for your help.

**Comment by grappler** [comment]
It is best practice to load the JS in the footer. This allows the site to load faster.

**Comment by carlos-andres** [comment]
mr @grappler you´re right and id know that. but in this case one project in specific require that..  
it is not by my own will.
