### ISSUE TITLE
Accessibility styling

### ISSUE THREAD

**Issue by slushman** [Automattic/_s#1037]
In the style.css file, line 682 - is there any time you'd want an outline on an element where the tabindex is set to -1? If not, couldn't we change that to:

So the outline: 0; applies to any element with a tabindex of -1? I'm trying to understand why the selector here is so specific. Can someone explain?

**Comment by samikeijonen** [comment]
I'm not sure why it's that specific. Maybe just because `_s` only wants to style  the `#content` where it adds the `tabindex="-1"` and let theme authors decide other styling.

This is remotly related to ticket #1046 also.

**Comment by mrwweb** [comment]
I bet @samikeijonen is right. In cases where one uses target/anchor links for in-page navigation, I could imagine one might want the focus style to indicate where focus moved (though in those cases, I personally use `:targeted`). If one thinks of this style as accompanying the skip-to-content link, the it makes more sense. In that case, then, maybe an explanatory comment makes more sense than making it less specific.

**Comment by davidakennedy** [comment]
Thanks for the issue @slushman! @samikeijonen is right. It was styled that way to be specific so if themes needed to style elements with `tabindex`, they could do it more easily. Closing this out.
