### ISSUE TITLE
mysql_real_escape_string() deprecated

### ISSUE THREAD

**Issue by mojoblanco** [Automattic/_s#1038]
mysql_real_escape_string()  is deprecated in php 7. It causes a fatal error.

**Comment by jrfnl** [comment]
Well, no. It was deprecated in PHP 5.5 and the extension was removed in PHP 7.0.

All the same, AFAICS the function is not used in `_s`, so what's the issue ?

**Comment by mojoblanco** [comment]
I guess I installed a plugin that overwrote my functions.php and added code that uses the function.
