### ISSUE TITLE
Help me understand the GPL for commercial use

### ISSUE THREAD

**Issue by kmob2** [Automattic/_s#1040]
Hello,

I came across this theme here, and I see it's purpose is for developers to use it to modify it and turn into their own theme. I see that the _s theme is being distributed using the GPL license. 
I have been playing around with the theme for a week, and so far I have modified about 95% of all files.

My goal is to create a wordpress theme, which I could eventually sell on markets like ThemeForest, but I don't want re-distribute it using the GPL license, otherwise it will "legally" end up on blackhat websites, where my theme can legally be downloaded.

I had a look at ThemeForest and I see that all the top selling themes are using a proprietary licenses, even though some were clearly based on heavily modified free themes that used the GPL license.

I really do like GPL, but seeing the amount of "hacked" and "nulled" themes on Blackhat forums and on Facebook pages, I don't feel like giving those people a hand by using GPL, which then makes it legal for them to give away my product for free, or even charge for it.

**So my question is, can I use _s theme, heavily modify it, and then somehow change the license or add an additional license, so that when I sell it on ThemeForest, that people will not be allowed to re-distribute it for free?**

**Comment by mtomas7** [comment]
GPL is "viral" license. Whatever it touches, must become GPL. _s is GPL theme, so even heavy modified it will be GPL. If you want to achieve your goal, you must start your theme from scratch, o find a theme with MIT, BSD or similar "non-viral" license and then modify it.

https://developer.wordpress.org/themes/getting-started/wordpress-licensing-the-gpl/

**Comment by mtomas7** [comment]
After reading more about the issue I realized that WordPress theme can only be GPL, so no luck with MIT or BSD licenses... Only CSS and image files can have different license than GPL:

> In conclusion, the WordPress themes supplied contain elements that are derivative of WordPress’s copyrighted code. These themes, being collections of distinct works (images, CSS files, PHP files), need not be GPL-licensed as a whole. Rather, the PHP files are subject to the requirements of the GPL while the images and CSS are not. Third-party developers of such themes may apply restrictive copyrights to these elements if they wish.

https://wordpress.org/news/2009/07/themes-are-gpl-too/

**Comment by sheabunge** [comment]
I believe that MIT license (and probably BSD as well) is GPL-compatible, and so can be used instead of the GPL when licencing PHP code in WordPress themes and plugins.

**Comment by karmatosed** [comment]
I feel this isn't directly an issue of the theme, so as a result closing. I understand conversations sometimes need to happen, but this repository is for directly working on _s.
