### ISSUE TITLE
A11y issue: an empty link is formed when a custom header image is added

### ISSUE THREAD

**Issue by laviperchik** [Automattic/_s#1041]
In custom-header.php, line 9 the `alt` for the custom header image is empty. An empty `alt` is ok, accessibility-wise, as long as the `img` is not wrapped with a link. This is not the case here, and therefore an empty link is formed. 

I suggest adding an `alt` to the image, or adding the following code inside the link:
`<span class="screen-reader-text"><?php esc_html_e( 'homepage', 'underscores' ); ?></span>`

**Comment by samikeijonen** [comment]
Thanks for noticing. I noticed the same in Core Custom logo feature. I'll ask around what would be best approach here.

**Comment by samikeijonen** [comment]
What if we modify the example in couple of ways.

1. Should there really be link to home page. We already might have that link in logo, site title, and menu.
1. Let header image be decorative with empty `alt` like now.

Code:

```
	<?php if ( get_header_image() ) : ?>
		<img src="<?php header_image(); ?>" width="<?php echo esc_attr( get_custom_header()->width ); ?>" height="<?php echo esc_attr( get_custom_header()->height ); ?>" alt="">
	<?php endif; // End header image check. ?>
```

**Comment by laviperchik** [comment]
I couldn't agree more with the solution you've suggested, header images are not clickable usually.

**Comment by samikeijonen** [comment]
We should actually use [the_header_image_tag](https://developer.wordpress.org/reference/functions/the_header_image_tag/) function. It take cares of responsive markup. 

By default it actually has `get_bloginfo( 'name' )` as alt attribute.

**Comment by samikeijonen** [comment]
Also noting that in WP 4.7 there will be function `the_custom_header_markup` which works for video headers also.
