### ISSUE TITLE
aria-haspopup shouldn't be set on list item

### ISSUE THREAD

**Issue by afercia** [Automattic/_s#1045]
See testing and screenshots on https://core.trac.wordpress.org/ticket/38397

The menu list items are not-focusable, not-actionable, elements thus setting an `aria-haspopup` attribute on them when they have a children menu doesn't benefit in any way accessibility. Assistive technologies won't announce the menu item has a sub menu.

**Comment by samikeijonen** [comment]
Let's fix this in the same way as in Twenty17.

**Comment by samikeijonen** [comment]
Noting that `aria-hashpopup` was [removed](https://core.trac.wordpress.org/changeset/39232). Could be removed from `_s` also since the menu is similar.
