### ISSUE TITLE
word-wrap in screen-reader-text class

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#1047]
In Core ticket [38764](https://core.trac.wordpress.org/ticket/38764) there is discussion about adding `word-wrap: normal` to `screen-reader-class` because screen readers may read out words ignoring spaces between words.

Even though `_s` uses `word-wrap: break-word` only in comment content link I can imagine that many themes add that style rule to body or content also. But they probably never change `screen-reader-class`.

Therefore it makes sense to add `word-wrap: normal` to `screen-reader-class`.

**Comment by afercia** [comment]
For reference, see also:

WordPress core:
https://core.trac.wordpress.org/ticket/31962

Twenty Sixteen:
WordPress/twentysixteen@4a7578c
