### ISSUE TITLE
Consider to update the screen-reader-text CSS class to reset word-wrap

### ISSUE THREAD

**Issue by afercia** [Automattic/_s#1048]
Elements that use the `screen-reader-text` CSS class may inherit properties from other CSS rules. When they inherit `word-wrap: break-word`, screen readers may read out words ignoring spaces between words. See:

WordPress core:
https://core.trac.wordpress.org/ticket/31962

Twenty Sixteen:
https://github.com/WordPress/twentysixteen/commit/4a7578c6aa5490abcbfa7e1bfa201176b27a95f0

Twenty Seventeen:
https://core.trac.wordpress.org/ticket/38764

**Comment by samikeijonen** [comment]
@afercia: I opened similar issue in #1047.

**Comment by afercia** [comment]
@samikeijonen ah sorry, need more coffee 🙂

**Comment by samikeijonen** [comment]
No worries😃
