### ISSUE TITLE
Confusing language in the project README

### ISSUE THREAD

**Issue by meredevelopment** [Automattic/_s#1059]
Having used underscores many times as a starter theme, I was just very confused to read the following in first paragraph of the project's README: 

`"I'm a starter theme ... I'm a theme meant for hacking so don't use me as a Parent Theme. Instead try turning me into the next, most awesome, WordPress theme out there."`

Upon seeing `"don't use me as a Parent Theme"` I wondered if I should have been using it as a Child Theme all along? That seemed to be implied. 

Somehow I think the paragraph need to be convey the following, but in better language: The theme should not be used as a Parent Theme 'out of the box', and will not provide a Theme Framework for Child Themes as is. Hoowever, _s is ideal for use as the *basis* for a Parent Theme.

I realise this is a matter of semantics and nomenclature, but I figure if it's confused me—a moderately intelligent person who's already had their coffee—it might confuse others. What do you reckon*?

_*engage empathy_

**Comment by karmatosed** [comment]
Hi @meredevelopment we do not recommend that you use _s itself as a parent theme. That's what the message is saying. Forgive me, but I am a bit confused as to why that isn't clear from the message?

As itself isn't considered right to use for a Parent Theme I feel in this case the message isn't going to cause any empathy issues. I understand in your case though there was a confusion. Perhaps you got that assumption from somewhere outside of the official documentation?

Let me clarify why we do say this, we say it as changes happen a lot to _s so using it as a parent isn't the right path.

**Comment by meredevelopment** [comment]
@karmatosed Oh ok I AM confused then... I thought it was just the explanation that wasn't clear. sorry.

So should _s not be used as a starting point for custom themes? 

It could be that I just don't understand what the term 'Parent Theme' is in the Automatic / WP context. I thought there were basically two sorts of themes: Parent Themes that are standalone, and Child Themes that rely on a Parent Theme for fallbacks and underlying styles/functionality.

Sadly, this sounds like I'm being argumentative... I'm not trying to be 😁

**Comment by karmatosed** [comment]
Don't worry at all, language can be confusing around themeing.

Themes do not require parent themes. Parent themes and child themes are a concept where you can use a theme to base themes on. It's not a requirement though of themes.
