### ISSUE TITLE
Is there list of official maintainers?

### ISSUE THREAD

**Issue by mrwweb** [Automattic/_s#1069]
In trying to [appeal a closed issue](https://github.com/Automattic/_s/issues/1019#issuecomment-269540429), I realized I have no idea who the official maintainers of _s are and what the policy is for closing tickets. Could this information get added to CONTRIBUTING.md?

**Comment by samikeijonen** [comment]
That's a good point. It would be nice to know for transparency and all.

**Comment by bahiirwa** [comment]
+1

**Comment by mrwweb** [comment]
Hoping to get some activity here. Tagging people I've seen close issues or commit PRs (I know this list is way incomplete): @karmatosed @davidakennedy @kovshenin @sixhours @laurelfulford @alaczek

**Comment by bahiirwa** [comment]
@mrwweb Check out https://github.com/bahiirwa/_s/blob/master/CONTRIBUTING.md. You could build on that.

**Comment by mrwweb** [comment]
@bahiirwa Where'd you get that list from?

**Comment by bahiirwa** [comment]
I did some snooping on guys who merged and closed issues in the past. Not conclusive/exhaustive I must say.

**Comment by mrwweb** [comment]
With the core focus on the Customizer and Editor, _s will likely need to make some changes pretty quickly as new features that impact theming near public release. Getting processes for reviewing issues/PRs/etc in order now, makes a whole lot of sense.

My interest in contributing to _s is seriously flagging due to this uncertainty, and that makes me really sad. I'm extremely hesitant to invest time in coding and thinking that right now seems unlikely to result in a reasonably-responsive and transparent review.

--------------------

Also, just sharing [this relevant article](https://foxland.fi/underscores-development/) from @samikeijonen:

> - Issues and pull requests should be reviewed and discussed more frequently. I don’t even know who have access the repo, and that’s one of the problems. Transparency is always good.
> - There should be several people who takes the main lead reviewing and discussing issues and PRs.
> - Main lead could rotate in month period. And main lead would check the repo every week, or every other week.
> - Checking the repo could mean active discussion, testing the PRs, closing the issues, calling for help and second opinions and so on.

**Comment by davidakennedy** [comment]
We’re busy working on some improvements to Underscores, as well as [Components](http://components.underscores.me/). Development should pick up again soon. Things have ebbed and flowed thanks to other priorities.

As far as a list of maintainers, Underscores is and has always been maintained by the [Theme Team at Automattic](https://themeshaper.com/about/). Hope that helps!

**Comment by mrwweb** [comment]
Thanks for the clarification, @davidakennedy. Much appreciated.

I'd like to note that "Theme Team" does not appear anywhere in the repo and there's clearly confusion around this if both I and @samikeijonen didn't know this. This really needs to be in CONTRIBUTING.md, README.md, or both.

And while we're here, any chance I can get #1019 unclosed and given further review by the Automattic Theme Team. There's an extensive explanation for why it was closed without given proper consideration on the ticket.

**Comment by bahiirwa** [comment]
Reopening this is effective. Issue keeps on cropping. https://github.com/Automattic/_s/issues/1109 https://github.com/Automattic/_s/issues/1084
