### ISSUE TITLE
author.php

### ISSUE THREAD

**Issue by cosminrr** [Automattic/_s#1072]
Hello,

Sorry if this post is in the wrong section but I have a question...

I want to create a author page but I can't make it work, neither the author.php or template-parts/content-author.php works, it just redirects me to the home page.

My example: http://simplecodetips.com/author/cosminr/ redirects to http://simplecodetips.com and is not displaying the author page.

Is there any function that I can add to archive.php to get the redirect to the right file eg.: author.php or content-author.php?

Thanks!

**Comment by bahiirwa** [comment]
Hey @cosminrr, Please post your query at http://stackoverflow.com/. You will find great help there and much quicker responses.

**Comment by cosminrr** [comment]
Thanks @bahiirwa, I will post there now and post the answer here if I get one that works.

Have a great day!
