### ISSUE TITLE
Incorrect class for current page ancestor in _menus.scss

### ISSUE THREAD

**Issue by aziznatour** [Automattic/_s#1073]
The following is incorrect: `.current_page_ancestor > a`
File: [/sass/navigation/_menus.scss](https://github.com/Automattic/_s/blob/master/sass/navigation/_menus.scss)
Line: 68

	.current_page_item > a,
	.current-menu-item > a,
	.current_page_ancestor > a,
	.current-menu-ancestor > a {
	}

It should be `.current-page-ancestor > a` (hyphens instead of underscore)

**Comment by bahiirwa** [comment]
@aziznatour Did you have a look at this https://github.com/Automattic/_s/issues/1031?

**Comment by bahiirwa** [comment]
@aziznatour Did you have a look at https://github.com/Automattic/_s/issues/1031?

**Comment by aziznatour** [comment]
@bahiirwa I have now. Why does WordPress generate a hyphened class if it's supposed to be underscores? I'm confused.

**Comment by bahiirwa** [comment]
Been looking into this. Maybe you can look into the differences here.
https://developer.wordpress.org/reference/functions/wp_nav_menu/#current-page-ancestor-menu-items vs  https://developer.wordpress.org/reference/functions/wp_list_pages/#menu-item-css-classes

**Comment by aziznatour** [comment]
WordPress 4.7.1 
File: `wp/wp-includes/nav-menu-template.php` 
Line: `474`
```

{
   $classes[] = empty( $queried_object->taxonomy ) ? 'current-' . $queried_object->post_type . '-ancestor' : 'current-' . $queried_object->taxonomy . '-ancestor';
}
```

This seems to be the code responsible for outputting the class in `wp_nav_menu()` and it is indeed hyphenated.

The underscore one is for `wp_page_menu()`:

```
if ( 'post_type' == $parent_item->type && 'page' == $parent_item->object ) {
   // Back compat classes for pages to match wp_page_menu()
   if ( in_array('current-menu-parent', $classes) )
      $classes[] = 'current_page_parent';
   if ( in_array('current-menu-ancestor', $classes) )
      $classes[] = 'current_page_ancestor';
}
```

I'm not sure if the docs are inaccurate or if something is being overridden :|

**Comment by joshmcrty** [comment]
@aziznatour @bahiirwa I'm not sure what the issue here is. `wp_nav_menu()` falls back to `wp_page_menu()` by default if the site admin hasn't set up a custom menu (see https://developer.wordpress.org/reference/functions/wp_nav_menu/#usage), so it's important to include selectors (hyphens and underscores) for both functions' output in the CSS/Sass. That way the menu looks correct in either situation.

**Comment by aziznatour** [comment]
@joshmcrty that's sounds like the ideal solution, maybe something as the following:
```
.current_page_item,
.current-page-item,
.current_menu_item,
.current-menu-item,
.current_page_ancestor,
.current-page-ancestor,
.current_menu_ancestor,
.current-menu-ancestor {
   a {
   }
}
```

**Comment by bahiirwa** [comment]
+1 for the solution.

**Comment by joshmcrty** [comment]
@aziznatour @bahiirwa actually I was saying that the ideal solution is _already_ in place. All `.current…item` and `.current…ancestor` selectors that either function might output are already accounted for, so this issue can be closed.

**Comment by davidakennedy** [comment]
Thanks for opening this issue @aziznatour! As @joshmcrty mentioned, this is already accounted for and not a problem, so I'll close this out.
