### ISSUE TITLE
Loading XML instead of HTML

### ISSUE THREAD

**Issue by buro244** [Automattic/_s#1077]
Hi there,
I have an issue that drives me crazy. I build a few WordPress websites with underscores_me as a basic platform. Great to start with! 

But sometimes the browser loads a WordPress page (or post) wrongly. Instead of loading the HTML it is loading a xml / rss version. See the screenshot for what I mean. After a refresh the page loads fine. But next time accessing the site it does the same.

It only happens with themes that where made with Underscores_me (at least I never saw it with other themes I run). I tried to disable some lines in the functions.php but until now it doesn't help. 

Has anyone have any idea what this could be? What do I miss? 

![screen shot 2017-01-18 at 13 41 43](https://cloud.githubusercontent.com/assets/3931734/22064609/96b2707e-dd84-11e6-82f4-39214109fee8.png)

Regards,

Jan

**Comment by jay187** [comment]
Did you find a solution to this problem? Having a similar problem with a wordpress website

**Comment by buro244** [comment]
Hi jay187,
Yes, I found a solution but still do not know what causes it. The websites that had this issue where all on the same webserver. I asked the hosting-provider to move the sites and the problem is over since they moved. I am not a programmer but the PHP version could be a problem.

**Comment by jay187** [comment]
Hi buro,

thanks for your reply. We've also switched to another PHP Version and I've disabled the Webserver Caching Module. Hopefully this will help.

**Comment by davidakennedy** [comment]
Hi @buro244 and @jay187!

Thanks for opening this issue. This doesn't strike me as a problem with Underscores. It's used for hundreds of themes on WordPress.com and throughout the WordPress community, and this has never come up before.

It does sound like it could be a server issue... I tried to replicate on a local install, but can't.

I'm going to close this. If you find a clear way to replicate the issue specifically with Underscores, and have some steps that would help us debug the problem, please reopen the issue.

Thanks again!
