### ISSUE TITLE
PHP Codesniffer errors

### ISSUE THREAD

**Issue by limestreet** [Automattic/_s#1079]
There are errors caused by Codesniffer:
1. A gettext call containing placeholders was found, but was not accompanied by a "translators:" comment on the line above to clarify the meaning of the placeholders. (WordPress.WP.I18n.MissingTranslatorsComment)
2. Missing singular placeholder, needed for some languages. See https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals (WordPress.WP.I18n.MissingSingularPlaceholder)
3. Default timezone is required since PHP 5.4 (PHPCompatibility.PHP.DefaultTimezoneRequired.Missing)

The last one is in my opinion false-positive and should be excluded (if we check only theme code).
BTW - I can provide PR with fixes for these issues.
Thanks!

**Comment by grappler** [comment]
Nr. 1 needs a PR.
Nr 2. has a PR https://github.com/Automattic/_s/pull/1012
Nr 3. is a error with your local system and not the code.

**Comment by jrfnl** [comment]
#1012 actually includes a fix for one missing translators comment, not sure if there are more.

**Comment by grappler** [comment]
There is another missing translator comment in [content-none.php](https://github.com/Automattic/_s/blob/master/template-parts/content-none.php#L21)

**Comment by limestreet** [comment]
All I can see:
missing translators comment:
https://github.com/Automattic/_s/blob/master/inc/template-tags.php#L28
https://github.com/Automattic/_s/blob/master/inc/template-tags.php#L33
https://github.com/Automattic/_s/blob/master/inc/template-tags.php#L52
https://github.com/Automattic/_s/blob/master/inc/template-tags.php#L58

https://github.com/Automattic/_s/blob/master/footer.php#L18
https://github.com/Automattic/_s/blob/master/footer.php#L20

https://github.com/Automattic/_s/blob/master/template-parts/content-none.php#L21
https://github.com/Automattic/_s/blob/master/search.php#L19


Additionally - "Assignments must be the first block of code on a line (Squiz.PHP.DisallowMultipleAssignments.Found)":
https://github.com/Automattic/_s/blob/master/inc/template-tags.php#L87

**Comment by limestreet** [comment]
So @jrfnl - if you can address those in your PR (#1012) please go ahead :)
Thanks

**Comment by grappler** [comment]
I think it would be better to have a separate PR just to fix the missing translators comments and another for `DisallowMultipleAssignments`

**Comment by limestreet** [comment]
This one needs only small change to something like this (but probably you're right with separate PR - to have history cleaner):
`$all_the_cool_cats = get_transient( '_s_categories' );`
`if ( false === ( $all_the_cool_cats ) ) {`

**Comment by limestreet** [comment]
or even:
`$all_the_cool_cats = get_transient( '_s_categories' );`
`if ( ! $all_the_cool_cats ) {`

**Comment by corvannoorloos** [comment]
If something would be changed here I wouldn't mind also seeing the phrase "all_the_cool_cats" being altered into something more descriptive/less hipster.

Not entirely sure about backwards compatibility though.

**Comment by jrfnl** [comment]
Well, a good start would be _finally_ merging #1012 - which fixes the issues related to the WPCS 0.10.0 release. Let's be fair, the PR has been open for more than 5 months already... 

Not sure when WPCS 0.11.0 will be released, but let's make sure there is a PR ready when it is. Be aware that until there is a release, things may still be moved around/added/removed, so if a PR is created at this moment, it may not address the issues WPCS 0.11.0 will actually highlight in the end.

Having said that: the translators comments should be fixed, no matter what.

**Comment by limestreet** [comment]
@jrfnl - you're right - we should move forward :)
Additionally I think that no 3 (from my initial comment) should be considered as well. In local environment I can easy set date for PHP but in testing environment (i.e. when using official php docker images) it is not set by default. IMO "Default timezone is required since PHP 5.4 " error is not related to theme code as well - it is related to environment. So I think this test should be excluded (PHPCompatibility.PHP.DefaultTimezoneRequired.Missing).

**Comment by jrfnl** [comment]
FYI: I've pulled PRs #1099 and #1101 to address the issues not yet addressed by #1012.

Once all three have been merged, the builds should pass again.

**Comment by davidakennedy** [comment]
I've merged all the appropriate PRs, as well as made a tweak to the build process mentioned here: https://github.com/Automattic/_s/issues/1067#issuecomment-307258832

It's passing again, so closing this out. 😄 

Thank you @limestreet @grappler @corvannoorloos for the help here.
