### ISSUE TITLE
Full functionality of plugins

### ISSUE THREAD

**Issue by christophz** [Automattic/_s#1080]
When I install a plugin like "WooCommerce", "WooCommerce Template Hints" and "Which Template" I recognize that Underscores doesn't show the results properly. 

However, when switching to a default WP theme like "Twenty Seventeen" everything works correctly. I couldn't manage to debug what is missing in my functions.php or template files to make the plugin hook in correctly. 

What do I have to do to make plugins work 100%? Is something missing in templates files or in functions.php?

**Output Underscores:**
[![enter image description here][1]][1]

----------

**Output Twenty Seventeen:**

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/ORRms.png
  [2]: https://i.stack.imgur.com/SdBQH.png

**Comment by David-Brown** [comment]
Did you [declare WooCommerce support](https://docs.woocommerce.com/document/declare-woocommerce-support-in-third-party-theme/) in the Underscores-based theme?

**Comment by christophz** [comment]
@David-Brown yes, I did. And the message hinting that this is missing vanished after that.

**Comment by davidakennedy** [comment]
@christophz My initial thought here is that _s is an unfinished theme. 😄  So there are a lot of missing pieces that may cause plugins trouble. That said, paging @jeffikus and @tiagonoronha for their WooCommerce expertise. They may be able to shed some light on this.

**Comment by jeffikus** [comment]
@davidakennedy We will be looking at this early next week. @tiagonoronha and I have set some time aside for this.

**Comment by Ismail-elkorchi** [comment]
Related: https://github.com/woocommerce/woocommerce/issues/13087

**Comment by jeffikus** [comment]
See #1190

**Comment by philiparthurmoore** [comment]
@christophz Was your issue only with WooCommerce? Becuase that seems to be in motion already. https://github.com/Automattic/_s/issues/1190

**Comment by davidakennedy** [comment]
I'm closing this out, as we specifically addressed this with the addition of WooCommerce support in #1190.
