### ISSUE TITLE
Creating a template

### ISSUE THREAD

**Issue by JoaquimFMF** [Automattic/_s#1086]
Hi.
I am thinking of the possibility of creating a template ... However, possibly, I will not be able to continue the template, that is, I will not be able to make updates to the template. And this brings a problem because of wordpress updates ...
If I developed the template based on the "Underscores theme" would my problem be solved? That is, would it suffice to update the "Underscores theme" and my template would always be updated?

**Comment by grappler** [comment]
Do you mean a page templates? https://developer.wordpress.org/themes/template-files-section/page-templates/

If you build a theme that follow the WordPress best practices then there should be no issues when updating WordPress as the updates are backwards compatible.

Underscores theme is a good base to build your theme on. In most cases a site will require a redesign after x years so you make any necessary changes then.

**Comment by davidakennedy** [comment]
Hi @JoaquimFMF – thanks for opening this issue. Like @grappler said, if you build according to WordPress theming standards, you should have no problems with updates. I'm closing this issue since it's not something we need to address.
