### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JoaquimFMF** [Automattic/_s#1087]
As a company can we use, without any cost, the "underscores" and all third party software that may be included in the "underscores" (for example: third party codes etc.)?

**Comment by grappler** [comment]
The licence for `_s` and it's assets is GPLv2 You can read it here https://github.com/Automattic/_s/blob/master/LICENSE

A basic summary can be found here https://choosealicense.com/licenses/gpl-2.0/

**Comment by davidakennedy** [comment]
@JoaquimFMF @mallardduck Everything in Underscores is compatible with the GPL, so use it. 😄 

Regarding the CSS/JS issue, it's a definite gray area. If you are building/running a theme on your own site, you're not required to release source code. If you offer the theme for download/use by others, then you would be.

Happy theming!
