### ISSUE TITLE
Conflict "screen-reader-text" and i18n word order change on continue reading link

### ISSUE THREAD

**Issue by mayukojpn** [Automattic/_s#1088]
I saw hidden post title added to the continue reading link since https://github.com/Automattic/_s/pull/516.

But in Japanese language, we have different translation for `continue reading` and `continue reading %s`. We should insert particle `の` between object and `continue reading`. If string doesn't have object, we should remove `の`。

Original|Japanese
--|--
continue reading|続きを読む
continue reading %s|%s**の**続きを読む

As result, we can see only `の続きを読む` without object with display and it doesn't make sense. Is there any better solution?

See also: [Wikipedia: Japanese particle: no](https://en.wikipedia.org/wiki/Japanese_particles#no)

# My suggestion
## A: update translator comment and translate as separate sentence
In default themes like Twenty Fifteen, we translate it as separated sentence. but [most theme translator doesn't know this situation](https://translate.wordpress.org/consistency?search=Continue+reading+%25s&set=ja%2Fdefault). I want to tell them the post name will be removed on screen. This is not the best solution because `Continue reading. Post name.` doesn't form a sentence.

## B: add different translation
I prefer it, but how?

**Comment by grappler** [comment]
A solution that I implemented recently as I had the same problem with the French translation.

`%s<span class="screen-reader-text">の</span>続きを読む`

👋

**Comment by mayukojpn** [comment]
Wow It looks nice though a bit tricky! 😳 I'll share with the team.

**Comment by waviaei** [comment]
That sound ok for screen, but, when a person uses a screen reader AND there are no object for %s, a screen reader wwill read up as "の続きを読む" ... will it not?

**Comment by grappler** [comment]
There will always be an object which is the name of the post title. An edge case would be if there is no post title.

**Comment by naokomc** [comment]
I think improving the translator comment is a better way to go since that's the intended way for the original string.

I already see a bunch of mistranslated versions:
https://translate.wordpress.org/consistency?search=Continue+reading+%25s+%3Cspan+class%3D%22meta-nav%22%3E%26rarr%3B%3C%2Fspan%3E&set=ja%2Fdefault&search_case_sensitive=1

**Comment by waviaei** [comment]
@grappler true, yes, tat would be an edge case.

**Comment by grappler** [comment]
This is how Twenty Seventeen has done it.

```php
/* translators: %s: Name of current post */
the_content( sprintf(
	__( 'Continue reading<span class="screen-reader-text"> "%s"</span>', 'twentyseventeen' ),
	get_the_title()
) );
```

@mayukojpn It may be good to reopen the issue.

**Comment by mayukojpn** [comment]
I like Twenty Seventeen's approach! With this format, current translator comment is enough and we don't need to update.

Why don't we use same format in _s :)

**Comment by mayukojpn** [comment]
I almost missed, but we have another discussion about arrow in this string,: https://github.com/Automattic/_s/pull/624

I don't think it's good string 🙄
```
__( 'Continue reading<span class="screen-reader-text"> %s</span> <span class="meta-nav">&rarr;</span>', '_s' )
```

**Comment by davidakennedy** [comment]
It would be good to follow Twenty Seventeen's lead here. PRs welcome!
