### ISSUE TITLE
"Blocked for security reasons!" issue, when zip attatched on gmail or cpanel

### ISSUE THREAD

**Issue by baljindersingh88** [Automattic/_s#1089]
Hi
I have noticed an issue while attaching(on Gmail) the zip of theme generated with underscore.me.Also the issue exist on cpanel too.I got a message that files are infected(while uploading the zip).
Did some research and found the files with issues,files are:-
js/customizer.js
js/navigation.js
js/skip-link-focus-fix.js

I hope the info provided will be helpful in resolving the issue.

Thanks
Baljinder Singh

**Comment by grappler** [comment]
This is the new gmail policy. https://support.google.com/mail/answer/6590?hl=en
https://nakedsecurity.sophos.com/2017/02/17/gmail-now-blocks-all-javascript-email-attachments/

You won't be able to send any JS files via Gmail. This is not something to do with `_s`

**Comment by baljindersingh88** [comment]
Ok but i am getting it on cpanel also, they are saying , there is some infectious script HTML like.

**Comment by grappler** [comment]
I am not sure about Cpanel but there is no malicious code. Are you able to upload an empty JS file to cpanel?

**Comment by baljindersingh88** [comment]
Yes i will try

**Comment by davidakennedy** [comment]
Thanks for opening this @baljindersingh88! I'm closing this out, as it's not an issue with Underscores.

**Comment by yungtravla** [comment]
I spit on this policy and the fact that Windows makes JS files executable by default...

You should seriously consider parsing JS files and then block them if they truly pose a risk.

This is affecting my work flow.

**Comment by jasminazfb** [comment]
You can simply upload your file on OneDrive or GoogleDrive and send to specific mail address you wanted :)

P.S. If you have more files, just .zip those to one and upload :)

**Comment by saif2008** [comment]
I also had same issue, it was because i had c++ code with .obj and .exe files. You can have these files from .cpp file after build and run so i just delete those and was able to attached.

**Comment by Steven-zion** [comment]
upload you .zip to google drive instead of gmail
