### ISSUE TITLE
[Violation] Handler took # ms of runtime (150ms allowed)

### ISSUE THREAD

**Issue by devcon7** [Automattic/_s#1092]
This is a fresh install of WordPress 4.7.3.

After activating the vanilla install of the theme, when you go to "Appearance > Customize," you will see many violations being logged in the inspect element console for Chrome.

The exact message I get is as it follows:
[Violation] Handler took 246ms of runtime (150ms allowed)
load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-drop&load%5B%5D=pable,jquery-ui-position,jquery-ui-tooltip,wp-ajax-response,jquery-color,wp-lists,postbox,nav-menu,utils,plupload&ver=4.7.2 LINE:2

[Violation] Forced reflow while executing JavaScript took 34ms
[Violation] Long running JavaScript task took 290ms

No plugins are installed. The violation warning goes away when I switch theme to other themes.

Please advise.

Thank you!

**Comment by davidakennedy** [comment]
Thanks for opening this issue @devcon7!

All of those scripts mentioned in that warning are loaded by WordPress core, not Underscores. Underscores is not meant to be a finished theme, so even though it puts forward best practices in WordPress, user experience, performance and other areas, it's up to those using it to make the best decisions.

If you'd like to file a bug with WordPress core, you can do so here: https://core.trac.wordpress.org/

I'm closing this out, as it doesn't appear to be an issue with Underscores.
