### ISSUE TITLE
getting update notices

### ISSUE THREAD

**Issue by redsoxfan2499** [Automattic/_s#1096]
We use Underscores base theme on 90% of our WordPress projects. I just recently went to the Underscores page and using the generator created a theme. I uploaded it tot our staging site and I am getting Theme Updates notices. I ran a test and clicked on updates and it installed Redux and WooTheme files and folders. I delete the theme and started again. Generated a new theme from the Underscore generator and the same thing happened. I have not updated this one now.  I have never experienced this before. Why is this happening??  Screen shot attached. 

<img width="1156" alt="screen shot 2017-03-20 at 8 32 03 am" src="https://cloud.githubusercontent.com/assets/1205420/24101817/bd076156-0d47-11e7-9f9d-156117240510.png">

**Comment by grappler** [comment]
The reason is that there is a theme with the same folder name as yours. You need to rename your themes name https://www.kadencethemes.com/product/pinnacle-premium-wordpress-theme/

This is not a support forum but a place to discuss the development of the starter theme.

**Comment by redsoxfan2499** [comment]
Grappler, 

thanks for the info, the help and quick response. 

Thanks, 

Darren
