### ISSUE TITLE
Implement a task manager such as Gulp or Grunt

### ISSUE THREAD

**Issue by iszwnc** [Automattic/_s#1097]
I was thinking about contributing to __s_ with a set of useful (at least for me) tools for Front End developers. I'm a more a Front End than a WordPress developer, although, the process to build the pages are basically the same, therefore, the same (annoying and repetitive) of:

- Compiling SASS to CSS;
- Making use of the ES6's new features;
- Validating your JavaScript and CSS;
- Refreshing page everytime you change an HTML or CSS file;
- ...

There are plenty more concepts I'd like to bring to __s_, but first I'd like to know what you guys think about it.

Cheers!

**Comment by tyrann0us** [comment]
See #585.

**Comment by iszwnc** [comment]
@tyrannOus Alright. I didn't know that this issue existed, altough for such a giant _repo_ like this one, I should've assumed that you guys had already discussed it. Therefore, I am closing this issue because it's no longer useful.
