### ISSUE TITLE
Possible style.css "focus" issue

### ISSUE THREAD

**Issue by erikdslater** [Automattic/_s#1102]
Hi there,

Looking at the following code in **style.css**:
```
.main-navigation li:hover > a,
.main-navigation li.focus > a {
}
```

I believe ```.focus``` should be ```:focus``` ... or am I missing something?

Thanks,

Erik D. Slater

**Comment by msroberts** [comment]
The `li` itself is not focusable.  `navigation.js` adds a `.focus` class to the `li` when a visitor tabs to the contained `a`.

**Comment by erikdslater** [comment]
That would be the _"something"_ I missed :-)
