### ISSUE TITLE
Is the repository not actively maintained anymore?

### ISSUE THREAD

**Issue by vinoddalvi** [Automattic/_s#1109]
The last update on repository was in 2016 so is the project abandoned or anything else?

**Comment by bahiirwa** [comment]
Check https://github.com/Automattic/_s/issues/1069

**Comment by dameer** [comment]
Too bad for this great starter theme, been using it for years, now I gotta find a decent alternative.

**Comment by davidakennedy** [comment]
I clarified this here: https://github.com/Automattic/_s/pull/1084

Thanks @mrwweb for PR!
