### ISSUE TITLE
Add Schema and/or Microformats 2 Support?

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/_s#1113]
I'm opening an issue to discuss adding further support for one or both of these since it comes up frequently and there are in-progress pull requests, one for each. We might as well talk about these together, and try to come to a conclusion for the PRs.

Even though we haven't moved on adding more support for these in the past, it's always good to discuss again since things may change.

See: #1065 and #972.

Core supports version one of Microformats. It won't add support for version two because of a [possible breaking change](https://core.trac.wordpress.org/ticket/30783#comment:27):

> Closing after chatting with @dshanske. As `h-entry` isn't a one for one replacement of `hentry`, I can't see how the change could be made without breaking a majority of WordPress sites.
The only option is a theme option, and at the point it's just as easy to remove the classes with filters on `post_class` and `body_class`.

Related to Microformats: #930.

Past discussions about Microformats: #591 

Past discussions about Schema.org: #510 and a [host of others](https://github.com/Automattic/_s/search?utf8=%E2%9C%93&q=schema&type=Issues).

cc: @grappler @dshanske @stephanethomas since you all have worked on PRs and discussed things previously.

In general, these haven't been added in the past because:

* too much additional markup and complexity
* it's hard to know the final product of the theme being made from _s, so deciding what data to include is a guess
* it's out of scope for a starter theme like _s

Discuss! 😄

**Comment by dshanske** [comment]
h-entry is a one to one replacement for hentry. But Core applies hentry to all post types when pages or any other hierarchical​ type would not apply as it applies to date based content. Other than that, things like authorship and such are a one to one match.

**Comment by dshanske** [comment]
Specifically about markup and complexity, sticking purely to microformats, it givens how to mark up elements that _s has.  h-feed and hfeed work the same way, and should be applied to pages with multiple h-entry(hentrys) only. vcard and h-card work the same way.

**Comment by dshanske** [comment]
There is another way to solve the h-entry issue. Any page with an explicit author and publication date can use h-entry. The reason why pages in _s don't is because they do not note the publication date or the author in most themes. If they did, then h-entry and hentry would be appropriate.

**Comment by davidakennedy** [comment]
Just some general thoughts and questions on this from me:

* I'm still on the fence about adding support for either or both of these because of the reasons listed in this issue. But I'm open to changing my mind since WordPress has a long history with Microformats and Schema.org has been adopted by search engines.
* I wonder about fixing the issue in #930 and whether that will cause issues in the long run.
* I'd love to see some demand from people who use themes made with _s. I think we come at things too often from a designer/developer perspective. If people want this because it helps their businesses get found more, we should listen to that.
* Do we just go with Microformats 2 or both versions?

**Comment by grappler** [comment]
I don't think we need to add full Schema and/or Microformats 2 Support but make it easier for developers to do so who want to.

- #930 is the first step of setting a good example. Related core ticket: https://core.trac.wordpress.org/ticket/32336
- The second step would be apply the class to only specific post types.  Related core ticket: https://core.trac.wordpress.org/ticket/28482

> But Core applies hentry to all post types when pages or any other hierarchical​ type would not apply as it applies to date based content. Other than that, things like authorship and such are a one to one match.

**Comment by stephanethomas** [comment]
> @stephanethomas since you all have worked on PRs and discussed things previously.

I'm not really into microformats. You probably wanted to ping another Stéphane ;).

**Comment by davidakennedy** [comment]
> I don't think we need to add full Schema and/or Microformats 2 Support but make it easier for developers to do so who want to.

I can get behind that. Apart from those two things listed, anything else we can do?

**Comment by grappler** [comment]
> Apart from those two things listed, anything else we can do?

I can't think of anything else.

Related a bit here are @joyously thoughts https://slack-files.com/T024MFP4J-F5SFNUWG7-03f2820dfd

**Comment by davidakennedy** [comment]
Closing in favor of the path outlined in #1268.
