### ISSUE TITLE
Set up all functions to be overloadable

### ISSUE THREAD

**Issue by jrfnl** [Automattic/_s#1116]
At this moment, only the `_s_posted_on()` and `_s_entry_footer()` functions in `template-tags.php` and `_s_setup()` in `functions.php` are set up to allow for overloading by a potential child theme.

While `_s` is intended to be a base theme and not a parent theme, this does not negate the possibility that a derivative theme based on `_s` would become a parent-theme for other child-themes.

To that end, I'd like to suggest making all methods within `_s` overloadable by a child-theme, i.e. wrapping all functions within a `if ( ! function_exists( 'function_name' ) ) {}` wrapper.

Opinions ?

**Comment by grappler** [comment]
We should not use pluggable functions if they are being used in hooks as we can use `remove_action/filter` in the child theme. Template files are the only ones that we cannot remove and need to be overridden.

Related: https://github.com/Automattic/_s/issues/929 & https://github.com/WordPress/twentyseventeen/pull/419

**Comment by jrfnl** [comment]
@grappler Thanks for your response.

According to that reasoning:
* The wrapper around `_s_setup()` should be removed as it is hooked in.
* A wrapper should be added to `_s_categorized_blog()` as it is called directly from two different places in the theme (404 template and the `_s_entry_footer()` function)
* A wrapper should be added to `_s_infinite_scroll_render()` as it is called via another function.

**Comment by grappler** [comment]
> The wrapper around `_s_setup()` should be removed as it is hooked in. 

I agree.

> A wrapper should be added to `_s_categorized_blog()` as it is called directly from two different places in the theme (404 template and the `_s_entry_footer()` function)

I am not sure if that is needed as the result is bool and the checks are very simple. I am not sure what changes would need to be made.

> A wrapper should be added to `_s_infinite_scroll_render()` as it is called via another function.

Possibly. It is also possible to use `remove_theme_support()` and redefine theme support.

**Comment by jrfnl** [comment]
> > A wrapper should be added to _s_categorized_blog() as it is called directly from two different places in the theme (404 template and the _s_entry_footer() function)
>
> I am not sure if that is needed as the result is bool and the checks are very simple. I am not sure what changes would need to be made.

The `get_categories()` function provides a lot of possibilities to customize the query, so I can imagine there will be situations where people will want to change things (only categories used by a certain post type, exclude a category etc). With that in mind, I think the function being overloadable would make a lot of sense.

> > A wrapper should be added to _s_infinite_scroll_render() as it is called via another function.
>
> Possibly. It is also possible to use remove_theme_support() and redefine theme support.

There are several pathways which can be taken here:
* Unhooking the `_s_jetpack_setup()` function
* Using `remove_theme_support()`
* *or* if all someone wants to do is change the template parts called in: overload the function.

So, again, I think it makes sense to add the wrapper.

**Comment by philiparthurmoore** [comment]
It's probably a good idea to follow Core's lead on this with how they handle all of these functions in the default themes.

**Comment by ernilambar** [comment]
I also prefer overloadable functions even if it can be removed/customized using hook. Some time user need to tweak a function and they find adding that one function in the child theme more easy than removing and hooking function again.

**Comment by samikeijonen** [comment]
I agree on Ulrich [comment](https://github.com/Automattic/_s/issues/1116#issuecomment-307690097). Or in fact I would remove all pluggable functions but that's another discussion.

**Comment by davidakennedy** [comment]
I'd be in favor of going to the approach [outlined here](https://github.com/Automattic/_s/issues/1116#issuecomment-308893591). It seems reasonable. It's not perfectly in line with how Twenty Seventeen does it, but it mostly is, and that doesn't mean we can't evolve a bit.

**Comment by pattonwebz** [comment]
I'll pick up this issue the coming week and work through the functions making them pluggable where appropriate.

**Comment by davidakennedy** [comment]
Hi @pattonwebz! We're still interested in seeing this happen. If you want to work on it, ping here. If not, no worries!

**Comment by pattonwebz** [comment]
Hey @davidakennedy, honestly I had forgotten about this. Added to a todo list now and will work on it over the coming days :)
