### ISSUE TITLE
No Read Permissions

### ISSUE THREAD

**Issue by cesarcopi** [Automattic/_s#1128]
I downloaded the file from your site
Http://underscores.me/
But at the time of installing it, it can not be read.

Provision solution: Change permissions manually.

**Comment by josephfusco** [comment]
Hey @cesarcopi,

Underscores.me has it's own repo if you can please move this issue to there. https://github.com/Automattic/underscores.me

**Comment by philiparthurmoore** [comment]
Moved over to https://github.com/Automattic/underscores.me/issues/53.

**Comment by jrfnl** [comment]
This might be something which can be changed here actually by making sure the chmod permissions on all files and folders in `_s` are set correctly.
