### ISSUE TITLE
Remove Landmark Roles

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/_s#1132]
With WordPress moving ahead with [better browser support](https://make.wordpress.org/core/2017/04/23/target-browser-coverage/), and _s [supporting Microsoft Internet Explorer 11 and Edge, as well as the latest two versions of all other major browsers](https://github.com/Automattic/_s/blob/master/CONTRIBUTING.md), removing the landmarks roles makes sense.

They're implied with the proper HTML5 markup, and warnings are given in most code checking tools if they're added. For more information, see [this post from 2015](http://html5doctor.com/on-html-belts-and-aria-braces/) by  Steve Faulkner that recommends dropping them.

We've kept them for quite awhile to have better support with assistive technology, but it's time to move forward.

I [brought this up](https://wordpress.slack.com/archives/C02RP4X03/p1497892561177146) with the WordPress Accessibility team, and they're for it.

Previously:

#786 
#797 
#889 

and probably more. 😄

**Comment by samikeijonen** [comment]
Go for it.
