### ISSUE TITLE
Improve comment navigation

### ISSUE THREAD

**Issue by ernilambar** [Automattic/_s#1138]
[the_comments_navigation](https://developer.wordpress.org/reference/functions/the_comments_navigation/) is available since 4.4. In `comments.php`, we could use it rather than creating custom comment navigation.

**Comment by samikeijonen** [comment]
Definitely. I was just to open similar issue.

**Comment by davidakennedy** [comment]
See: #884. Will ping there and see if there's interest on cleaning up the PR.

**Comment by davidakennedy** [comment]
Fixed in #884, merged by @grappler.
