### ISSUE TITLE
Removing function call for Post Formats

### ISSUE THREAD

**Issue by ernilambar** [Automattic/_s#1148]
Since we have already removed support for Post Formats, now we can remove `get_post_format()` and other relevant code.

Eg,
```
get_template_part( 'template-parts/content', get_post_format() );
```
could be simply 
```
get_template_part( 'template-parts/content' );
```

**Comment by samikeijonen** [comment]
Or even `get_template_part( 'template-parts/content', get_post_type() );` or similar.

**Comment by grappler** [comment]
Related to this we #1017 still open.

**Comment by alaczek** [comment]
Removing `get_post_format()` feels like the right move. We should probably carry on the discussion in #1017

**Comment by samikeijonen** [comment]
Should this be close because this is done in a3739e969b32b85e63fab1aa09bc5f85f14081ae.

**Comment by grappler** [comment]
Closed by #1017

**Comment by ernilambar** [comment]
@grappler I still see `get_post_format()` in several files. Have we decided to change only in `single.php` file?

**Comment by grappler** [comment]
@ernilambar Ah, yes you make a good point.

**Comment by philiparthurmoore** [comment]
@grappler I'm coming to this late. Is the decision to rip out post formats all around? (I'm more than okay with that.)

**Comment by joyously** [comment]
I'm also late to this, but I don't see any reasoning to remove the call. If it remains, child themes can easily add template parts to handle the post formats without changing the calling template.

**Comment by philiparthurmoore** [comment]
@joyously My comment was related to post format removal everywhere, not simply the content call in https://github.com/Automattic/_s/pull/1017. The change from https://github.com/Automattic/_s/pull/1017 was already merged in so the issue I'm asking about related to all-around post format support removal or cherry picking where it's removed. This may have already been discussed.

**Comment by grappler** [comment]
@philiparthurmoore Yes, as post formats have been removed in #968 it makes sense to remove the calls to `get_post_format()`. In #1017 `get_post_format()` was replaced with `get_post_type()` which should be changed everywhere. At the same time we should update the inline docs.

**Comment by philiparthurmoore** [comment]
@grappler Thank you. In that case, yes. Agree completely that any calls to post formats should be gutted completely.

**Comment by David-Brown** [comment]
General question: are post formats to be removed from core? Just curious.

**Comment by grappler** [comment]
> are post formats to be removed from core?

Not that I know of but things may change with Gutenberg.

**Comment by samikeijonen** [comment]
What's the status of this? There are still `get_post_format` calls? Should we open new issue/PR for this?

**Comment by crunnells** [comment]
Hey @samikeijonen, I think the issue still stands (so no need for a _new_ issue), but I think a new PR that removes `get_post_format()` is needed.
