### ISSUE TITLE
Show post thumbnail on posts list pages

### ISSUE THREAD

**Issue by truongwp** [Automattic/_s#1151]
Should we show post thumbnail on posts list pages (blog, archive)? Post Thumbnails is supported but no displayed anywhere. If it should be, I can provide PR.

**Comment by grappler** [comment]
I think it makes sense if we have defined support `add_theme_support( 'post-thumbnails' )` to correctly display the post thumbnail too.

**Comment by alaczek** [comment]
This is covered in https://github.com/Automattic/_s/pull/1158

**Comment by philiparthurmoore** [comment]
@alaczek Should we close this out, so the conversation continues in #1158?

**Comment by grappler** [comment]
@philiparthurmoore GitHub best practice would dictate that the Issue is only closed once the PR is merged.

**Comment by philiparthurmoore** [comment]
Makes sense. Thanks.

**Comment by philiparthurmoore** [comment]
Closing. This was merged in https://github.com/Automattic/_s/commit/115dd8209c41669d1c6c173cbe533523bbc73158.
