### ISSUE TITLE
mixin font-size issue

### ISSUE THREAD

**Issue by tomasderrig** [Automattic/_s#1166]
hi all,

I'm having issues with getting responsive typography to work with this mixin setup in humescores wordpress theme - following a lynda wordpress course and the responsive type setup doesn't work 

```
**_mixins_master file:**
// Rem output with px fallback
@mixin font-size($sizeValue: 1) {
	font-size: ($sizeValue * 20) * 1px;
	font-size: $sizeValue * 1.25rem;

**_typography file:**
body,
button,
input,
select,
textarea {
	color: $color__text-main;
	font-family: $font__serif;
	@include font-size(.9);
	line-height: $font__line-height-body;
	
	@media screen and (min-width: $query__small) {
		@include font-size(1);
	}
}

@import "headings";

@import "copy";
```

**Comment by grappler** [comment]
This seems to be a support question. GitHub is used for the development of `_s`. If you need support you are probably better off on the wordpress.org forums, the WordPress Stack Exchange (http://wordpress.stackexchange.com), or IRC (#wordpress on Freenode).

**Comment by davidakennedy** [comment]
Thanks for creating this issue @tomasderrig! Like @grappler said, it looks like your issue isn't with _s itself. If I'm missing something, let me know. Happy to reopen this if it's a bug with _s.
