### ISSUE TITLE
Theme not showing up

### ISSUE THREAD

**Issue by roobex** [Automattic/_s#1180]
Wordpress 4.8 not recognizing starter theme

**Comment by tyrann0us** [comment]
This seems to be a support question. GitHub is used for the development of _s. If you need support you are probably better off on the wordpress.org forums, the WordPress Stack Exchange (http://wordpress.stackexchange.com), or IRC (#wordpress on Freenode).
(@grappler, I hope you don't mind if I use [your text](https://github.com/Automattic/_s/issues/1166#issuecomment-313744487) here.)

**Comment by JustOwned** [comment]
I faced same problem, I don't know what #245 want to mean about and my webpage showing like theme didn't connect with stylesheet_uri

![chrome_2017-07-14_06-05-54](https://user-images.githubusercontent.com/4678120/28192204-8ec8548a-685a-11e7-943b-c8d500bad74e.png)

**Comment by joshmcrty** [comment]
@JustOwned that screenshot looks correct to me. This is just a starter theme and it has very basic CSS. It's meant for you to modify with your own CSS in addition to what's provided, as well as adding other PHP or JavaScript functionality that you need.
