### ISSUE TITLE
categorized_blog

### ISSUE THREAD

**Issue by eugelogic** [Automattic/_s#1182]
Hello there,
I was wondering if you could help me please.
I've been redirected here from Slack since there is no channel dedicated to _S.
I'm running my _S custom theme against the WPCS and bumped into the following on inc/template-tags.php
`Assignments must be the first block of code on a line`
This is referred to:
`function hlcchl_categorized_blog() {
	if ( false === ( $all_the_cool_cats = get_transient( 'hlcchl_categories' ) ) ) {` 
I realised the version of _S I'm using is a few weeks old so I was trying to look through this repo to find the `categorized_blog()` function and see if that error had been fixed but couldn't.
So my questions are:
- is the `categorized_blog()` function still in use on _S? if yes, where can I find it?
- how can I fix the `Assignments must be the first block of code on a line` error?

Many thanks in advance,
Eugene

**Comment by eugelogic** [comment]
Hello again,
I have fixed the error now :-)
old code:
`if ( false === ( $all_the_cool_cats = get_transient( 'hlcchl_categories' ) ) ) {`
new code:
`if ( false === (`
`$all_the_cool_cats = get_transient( 'hlcchl_categories' ) ) ) {`
I just had to split the code on two lines since assignments must be the first block of code on a line as suggested here as well [https://github.com/squizlabs/PHP_CodeSniffer/issues/1277](https://github.com/squizlabs/PHP_CodeSniffer/issues/1277)

I'm still curious to know if the `categorized_blog()` function has been removed and why?

Many thanks

**Comment by ernilambar** [comment]
categorized_blog() is removed now I guess.
