### ISSUE TITLE
Add WooCommerce Support to _s

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/_s#1190]
At WordPress.com, we're beginning to build more themes with WooCommerce integration.

So it makes sense to add support much in the way support exists for Jetpack. The basics are there, but not everything, and it's easy to remove if you don't need it.

Questions around WooCommerce support have come up a few times in the past in #761 and #1057.

@tiagonoronha  and @jeffikus will start a branch and PR for this. From there, we can take feedback and evolve it, if necessary.

Some principles for this:

- It will have just the basics with some basic styling for some key components.
- We won't style on top of WooCommerce styles.
- We'll make everything easy to remove.
- We'll likely consider an addition to the generator on Underscores.me so that if you don't want it, you can just get _s without it.

The idea here is to make this as easy to use as _s and help themers learn how to do a minimal implementation for WooCommerce.

**Comment by philiparthurmoore** [comment]
@davidakennedy Is this good to close now?

**Comment by davidakennedy** [comment]
Yep, thanks @philiparthurmoore! Looks like this didn't autoclose.
