### ISSUE TITLE
Improve description of widget area

### ISSUE THREAD

**Issue by joyously** [Automattic/_s#1193]
The description of the widget area should indicate when and where the area is shown, not a generic "Add widgets here."

```
function _s_widgets_init() {
	register_sidebar( array(
		'name'          => esc_html__( 'Sidebar', '_s' ),
		'id'            => 'sidebar-1',
		'description'   => esc_html__( 'Add widgets here.', '_s' ),
		'before_widget' => '<section id="%1$s" class="widget %2$s">',
		'after_widget'  => '</section>',
		'before_title'  => '<h2 class="widget-title">',
		'after_title'   => '</h2>',
	) );
}
```

**Comment by grappler** [comment]
> The description of the widget area should indicate when and where the area is shown

As this is a starter theme it is a bit more difficult to know where the sidebar will be used.

Like mentioned in the [wordpress.com Theme guide ](https://developer.wordpress.com/themes/#widgets) the sidebar names should be descriptive of their location, ie. Sidebar, Footer.

**Comment by joyously** [comment]
Isn't it shown at all? If so, put that.
The problem is that since it is a starter theme, authors just leave the default "Add widgets here", as if it is a good thing. It could at least say "This sidebar is shown on all pages." or "This will be shown on the right of the content." or anything more descriptive than what it has.

**Comment by grappler** [comment]
> Isn't it shown at all? If so, put that.

This sounds like you are schooling me instead of working together towards a solution. I hated it when my teachers did it to me.

I looked through a few themes to see what they had as their description. I think maybe the last one may be best.

- `'Main sidebar that appears on the right.'`
- `'This sidebar will only be visible on the front page and the blog index'`
- `'This section appears on the right of the main content on every page.'`
- `'Sidebar shown in all standard pages by default.'`

**Comment by joyously** [comment]
>> Isn't it shown at all? If so, put that.
> This sounds like you are schooling me instead of working together towards a solution. 

Not my intent. I don't really know this theme by itself, except that I've seen it used as the basis for many. So I don't know where the sidebar is shown. That's a good example of why it should have the actual description of where the sidebar is shown to begin with. It would not only document itself correctly, but show the author how to document it.

Each of your examples are better than what is there now. My preference is the third one, because it has "where" and "when".

**Comment by slushman** [comment]
@joyously, I think we would all agree a better description should be provided, however, like @grappler has already pointed out, this is a starter theme. No one maintaining _s knows where these sidebars will appear in the themes developed based on _s, so it doesn't make sense to change the sidebar descriptions here. That would and should be completely up to the theme developer.

**Comment by joyously** [comment]
I disagree. I can install this theme and it works. Therefore, it either shows a sidebar or not when it is installed. 
If it does, it should have a valid description for that sidebar, not only for the user of the theme to see what it is doing, but for the theme author that will build on the theme to see what kind of description should be used for their end product.
If it does not, it is still registering a sidebar and should have a valid description so the theme author knows what should go there. Even if it only says "Describe where and when this sidebar is shown", that is better than "Add a widget".
The author already knows he can change anything in this theme, but the more things that are set up correctly already, the fewer he has to change.  I am really tired of reviewing themes based on _s that just say "Add a widget".

**Comment by grappler** [comment]
> Therefore, it either shows a sidebar or not when it is installed.

The sidebar is shown and we can agree on that.

> My preference is the third one, because it has "where" and "when".

We can define where the sidebar is shown as it is not styled. It could be either left, right or under the content.

The sidebar description is not that important when the user is using the customizer as the changes can be seen real time.

> Even if it only says "Describe where and when this sidebar is shown"

I don't think there is any other text like this and I don't think we should start now forcing developers to have the adapt the default text.

**Comment by samikeijonen** [comment]
By vote would be generic `Sidebar shown in all standard pages by default.` because there are no styles where the sidebar is. Or similar to Twenty17: `Add widgets here to appear in your sidebar on all standard pages.`

**Comment by ernilambar** [comment]
I would go with `Add widgets here to appear in your sidebar.`.

**Comment by davidakennedy** [comment]
Thanks for the issue @joyously and the thoughtful discussion from everyone.

Some backstory on this can be found in #938. The description used to be blank and authors never changed it. It's what it is now, and that's very generic. They still don't seem to change it. 😄 

My fear is that if we make the description apply to how _s works out of the box, and authors change that behavior without updating the copy here, it becomes incorrect, which is worse than generic. This is one of those gray areas for a starter theme.

So I'm leaning toward leaving it as it is now. But open to better, slightly less generic descriptions. I'll leave this issue open for awhile to see if any more ideas surface.

**Comment by alaczek** [comment]
I'm leaning towards leaving as is as well. 

> We can't define where the sidebar is shown as it is not styled. It could be either left, right or under the content.
Agreed!

> I can install this theme and it works.
While _s can be installed and run on a site, it's not meant to be, so I'd rather we don't encourage it.

**Comment by sixhours** [comment]
+1 for leaving it as-is. "Add widgets here" is short and to-the-point.

We could make the description developer-centric with more guidance as to what this particular line of code is for. Something like:

"Describe where the widget area is located in your theme, ie. 'Add widgets to the left sidebar.'"

**Comment by philiparthurmoore** [comment]
I'm closing this out. I see no compelling reason to make a change due to all the feedback above. The sidebar description is impossible to make one-size-fits-all. It's just not possible without knowing the intention of a theme or its design. `Add widgets here` is something that developers and users alike should understand.
