### ISSUE TITLE
Global Constant For Setting 'Text Domain'

### ISSUE THREAD

**Issue by DWebSoft** [Automattic/_s#1194]
Hey,
As _s theme is used as a starter theme, most of the developers used it for creating their themes. It has bunch of pre-defined functions for rapid development and improving theme experience. So my suggestion was, "Won't it be feasible if we can just provide a Global Constant to set  'Text Domain' for theme? "

Details:
As of now, we have to add Text Domain in style.css file and as a parameter to the translation functions. Now if someone decides to use _s as a starter template, he have to change Text Domain in style.css file and every other location where translation functions are use.
Consider the snippet in footer.php file as an example:
`
<a href="<?php echo esc_url( __( 'https://wordpress.org/', '_s' ) ); ?>"><?php
				/* translators: %s: CMS name, i.e. WordPress. */
				printf( esc_html__( 'Proudly powered by %s', '_s' ), 'WordPress' );
			?></a>
`
If we add a global constant in functions.php file as follow:
`
define( 'TEXT_DOMAIN' , '_s' );
`
The snippet of footer file can be changed to:
`
<a href="<?php echo esc_url( __( 'https://wordpress.org/', TEXT_DOMAIN ) ); ?>"><?php
				/* translators: %s: CMS name, i.e. WordPress. */
				printf( esc_html__( 'Proudly powered by %s', TEXT_DOMAIN ), 'WordPress' );
			?></a>
`
In this way, the developer don't have to change Text Domain at every location. Just change it in style.css
and functions.php file!
I hope this change can included.

**Comment by tyrann0us** [comment]
Please read https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/ on why this is considered bad practise.
Also, the the WordPress Developer Resources [states](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/):
> Do not use variable names for the text domain portion of a gettext function.  Do not do this as a shortcut: __( ‘Translate me.’ , $text_domain );

**Comment by joshmcrty** [comment]
Also,
underscores.me
takes care of the find/replace when you generate the theme files.

**Comment by DWebSoft** [comment]
Thanks @tyrann0us and @joshmcrty for clearing my doubts.
