### ISSUE TITLE
the_posts_navigation() not working properly. (404 page)

### ISSUE THREAD

**Issue by Dduvacher** [Automattic/_s#1198]
I've created around 20 posts and when I go to my site and when I click on Older posts, I'm redirected to a 404 page.

[EDIT]
The "Older Post" link go to a url like http://yourwebsite/bucket/event-bucket/page/2 and is returning 404 page and if i enter manually a link like http://yourwebsite/bucket/event-bucket?page=2 it works well.

I tried to change the permalink but if I change it, all my posts disappear on my page.

**Comment by philiparthurmoore** [comment]
@Dduvacher This ticket is a little weak and hard to address. Can you please provide steps to reproduce this issue or do the following: 1) disable plugins, 2) re-save your permalink settings. I'm unable to reproduce this behavior, but I could very well be missing something. Thank you.

**Comment by davidakennedy** [comment]
Hi there @Dduvacher! Thanks for the report.

I'm not able to reproduce this with a copy of _s on WordPress and several posts. It sounds like you may need troubleshooting help. Please head over to the WordPress.org support forums to get help if you're experiencing some issues with your WordPress setup. See: https://wordpress.org/support/forum/how-to-and-troubleshooting/

If it does turn out to be an issue with _s, let us know more details, and we'll be happy to help.

**Comment by jimbatamang** [comment]
Hi @philiparthurmoore, it looks like when you use the blog page as a child page (eg: event-bucket is the child of bucket), this issue occurred.
