### ISSUE TITLE
Meta: Better Labels

### ISSUE THREAD

**Issue by philiparthurmoore** [Automattic/_s#1199]
I've added in a few to this repo. The PR screen is impossible to quickly scan through without labels indicating what the issues are about. Not really sure where else to place this to let `_s` contributors and committers know what's up. So, here you go.

<img width="423" alt="2017-09-10_18-18-04" src="https://user-images.githubusercontent.com/28684/30248575-a819683e-9654-11e7-811f-37eb6ca8705f.png">

**Comment by grappler** [comment]
@philiparthurmoore What is the difference between Sass and Styling? Could we perhaps change Sass to Tooling and include changes to travis etc?

**Comment by philiparthurmoore** [comment]
@grappler Absolutely. I'm not married to any of these labels. I just know that not having them makes it so hard to quickly manage issues/PRs, etc. I'm happy to follow whatever nomenclature you prefer so long as it makes our job easier.
