### ISSUE TITLE
Bringing back ARIA roles?

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#1202]
We removed ARIA roles in #1132. But WAI-ARIA 1.1 and HTML 5.1 specifications have been updated. This is the biggest change for ARIA roles:

<blockquote>&lt;header&gt; and &lt;footer&gt; elements will now only be exposed as header and footer, and banner and ContentInfo landmarks respectively, if these elements are direct descendants of the body tag, and therefore are scoped for the whole page.</blockquote>

In `_s` header and footer are not direct descendants of the body tag, they are inside `#page` wrapper.

My question is, should we bring back `<header role="banner">` and `<footer role="contentinfo">`?

Here is [more information about the ARIA roles subject](https://www.marcozehe.de/2017/08/30/firefox-57-will-less-chatty-screen-readers-situations/).

**Comment by samikeijonen** [comment]
It doesn't mention `<main>` but let's talk about that too.

**Comment by davidakennedy** [comment]
My feeling on this is: Yes. Kind of frustrating since we just removed them. 😄 

We could also remove the wrapper container, but I have a felling that's useful in a lot of cases for designers and developers. Curious to hear what others think.

**Comment by joedolson** [comment]
Should put header and footer back; there shouldn't be any need to do that with main. 

I think that removing the wrapper container doesn't do anything to solve the problem - as soon as an author added one back in, the roles would be broken again.

**Comment by philiparthurmoore** [comment]
FWIW I think the roles should be added back in, for precisely the reason that @joedolson mentioned. We cannot control how people use _s, but we can control how it's distributed, and doing it in a way that is developer-proof, as far as roles go, seems sensible.

**Comment by asuh** [comment]
From an outside voice and perspective, I vote that `#page` should be dropped instead of adding back aria roles to header and footer elements.

As of October 2017, after Windows 10 Fall Creators Update is released, all modern browsers support CSS Grid Layout. Together with mobile-first responsive design and CSS Grid Layout, the need for a global wrapper element is more of a past relic. Pages used to need global auto margins and fixed widths to be centered and this was good when we weren't really considering devices smaller than a laptop/desktop.

While we can't control how people use _s, promoting componentized wrapping instead of global wrapping allows more styling flexibility, follows the WAI-ARIA 1.1 and HTML 5.1 updates, and is following the change of what is becoming a modern best practice. More of the Alexa Top 500 have dropped global wrappers and I expect as more sites adopt CSS Grid Layout, this change will move faster and become a trend, not a fad.

Documentation for _s can educate what to do when someone needs to add a global wrapper.

**Comment by samikeijonen** [comment]
@asuh I have to say that I 100% agree with you. I'm definitely dropping `#page` from my own future themes.

I probably remove "extra" divs like `<div id="content" class="site-content">` and `<div id="primary" class="content-area">` also.

But I'm not sure is `_s` there yet. It's usually 1-2 years behind from latest and greatest, and for a reason (older browsers and 2 main versions of WP).

**Comment by asuh** [comment]
I hope we reconsider our thinking about labeling CSS Grid Layout the "latest and greatest" as we did with Flexbox or other features introduced with prefixes. Modern browsers are mostly evergreen, the iterations of new features like CSS Grid are developed inside browser feature flags so that when released it's mature and ready to go. Together with either Flexbox or messy IE10/11 prefixes, support for Grid goes back several browser versions.

Bringing this back to Aria, without the global wrapper, the only landmark element that really needs explicit Aria role, because of <=IE11, is <main> as described here: http://html5accessibility.com/

I would agree that _s doesn't need to be cutting edge for everything but I can't emphasize strongly enough that CSS Grid Layout should be the one exception. It's that important.

**Comment by philiparthurmoore** [comment]
> I would agree that _s doesn't need to be cutting edge for everything but I can't emphasize strongly enough that CSS Grid Layout should be the one exception. It's that important.

I do not dispute the importance of CSS Grid Layout but I'd hardly consider it critical enough to distract from the core issue of this ticket, which is whether or not ARIA roles should be added back into header and footer elements.

**Comment by asuh** [comment]
> whether or not ARIA roles should be added back into header and footer elements.

Understood. I was trying to create value to why the Aria roles don't need to be added back to header and footer and why the global wrapper should be dropped instead.

**Comment by samikeijonen** [comment]
It seems that at the moment best approach is to add back the roles in `header` and `footer`. Any volunteers for PR, would be quick fix and huge amount of glory:)

**Comment by pattonwebz** [comment]
I made a PR adding back roles on `header` and `footer`. I will gladly accept glory for a quick fix lol

**Comment by samikeijonen** [comment]
@pattonwebz Looks good to me!

@davidakennedy can approve or give feedback when he has time.

**Comment by WraithKenny** [comment]
I think we are misreading the article here.

When it says "direct descendant," they aren't talking about `body > header {}` but rather in the context of landmark regions, i.e. `body :not( article, section, main, nav, aside ) header {}` (https://www.w3.org/TR/wai-aria-practices/examples/landmarks/HTML5.html). The wrapper div, being semanticless, should have no effect and not be a problem. Has anyone pulled FF56 to test whether this is an issue or not? (I haven't)

**Comment by samikeijonen** [comment]
@WraithKenny That's a good point, and you might be right. Is it possible that you test it out?

**Comment by WraithKenny** [comment]
To be honest, I'm not exactly sure how or what to test here (sorry).

**Comment by samikeijonen** [comment]
No worries, we can test it out.

**Comment by samikeijonen** [comment]
I did some testing with Firefox  `56.0.`1 and `57.0b10`. I was little surprised that there was no change at all how NVDA listed landmarks.

## How I tested
- Latest _s
- NVDA version 2017.3
- Firefox `56.0.`1 and `57.0b10`.

### Test results

Both Firefox versions list landmarks like this with some test data. 

```html
Banner
-- Navigation

Main
-- Navigation

Complementary
--Search

Content info
```
I tested with Insert+F7 which list links, headings, and landmarks.

I also tested adding `<section>` around `<header>`. In this case banner is not listed but it happens in both Firefox versions. Based on article I assumed it would be listed in version 56 but not in version 57.

I could not test with Firefox Nightly because it kind of crashed NVDA in my computer.

## Conclusion

I didn't notice any difference between `56.0.`1 and `57.0b10`. That would mean that we do not need to add ARIA roles back to header and footer.

But I would appreciate if someone could test also, and perhaps with Firefox Nightly also.

**Comment by grappler** [comment]
I tried to test it on my OSX but it seemed not to work with VoiceOver.

When using other tools to check the landmarks I could not see any difference between the Firefox 56 and 57.

As it would be only a specific issue related to Firefox I think we should wait before we till Firefox 57 is released as a stable version.

**Comment by samikeijonen** [comment]
This is getting interesting. In Voiceover Footer landmark is not listed without a `role="contentinfo"`.

Screenshot in current `_s`:
<img width="741" alt="no footer landmark in Voiceover" src="https://user-images.githubusercontent.com/1820415/31864160-7b266b8c-b761-11e7-9ef8-dd381519d5da.png">

Screenshot with `role="contentinfo"` added:
<img width="760" alt="footer landmark is listed in Voiceover" src="https://user-images.githubusercontent.com/1820415/31864166-95ba5300-b761-11e7-810e-23270e4b1f4b.png">

Seems to be a known bug but I had no idea about it. Fixing this bug might take a long time so I propose that we add at least `<footer role="contentinfo">` back which was the original idea.

We can also wait for Firefox 57 so we can decide what to do with `role="banner"`.

**Comment by samikeijonen** [comment]
Here is good [test table about HTML5 element in different screen readers](http://www.weba11y.com/blog/2016/04/22/screen-reader-support-for-new-html5-section-elements/).

**Comment by samikeijonen** [comment]
After short talk with `a11y` team, let's wait for FF57.

Maybe Voiceover bug goes away while waiting:)

**Comment by tyrann0us** [comment]
Firefox 57 has been released on [November 14, 2017](https://www.mozilla.org/en-US/firefox/57.0/releasenotes/). Maybe we can refresh this issue?

**Comment by pattonwebz** [comment]
Anyone able to make decisions on if this would be good to add back in? I still have this PR opened for it from away back: https://github.com/Automattic/_s/pull/1212

**Comment by Ismail-elkorchi** [comment]
Hi @samikeijonen :wave: ! Would this issue remain relevant after merging https://github.com/Automattic/_s/pull/1251 ?

**Comment by samikeijonen** [comment]
Hi @Ismail-elkorchi. I'd say we can close this issue and not to add aria roles back in.

At least Safari Version 13.1  in MacOS have fixed footer landmark issue. 

I don't have WIN to test out FF with NVDA at this moment but I'm confident there is no issues in there.

**Comment by Ismail-elkorchi** [comment]
Thanks @samikeijonen, I appreciate your input on this.
