### ISSUE TITLE
Is skip-link-focus-fix.js still necessary?

### ISSUE THREAD

**Issue by startover909** [Automattic/_s#1206]
All the information I can find regarding this script and the bug it's intended to fix are years old. I tested current versions of Chrome FireFox IE11 and Edge and none exhibit the bug. Maybe it was fixed a long time ago? Or does it only affect some very old versions of browsers with very few users (and I'd imagine that even fewer keyboard-only users would choose to use such browsers).  So is it safe to let this go at this point of time in 2017?

**Comment by samikeijonen** [comment]
It's still an issue in IE11.

**Comment by startover909** [comment]
Hmmm, I can't reproduce it on IE 11 in Windows 10 v.1703.  Skip to content link then tab key worked as intended without the fix js.  Maybe I'm running a different theme that's somehow different.

**Comment by samikeijonen** [comment]
On WIN8/IE11 I can still see this issue. My computer wants to update to WIN10 but I try not to:)

**Comment by startover909** [comment]
I actually have access to a Win 8.1 system too and the IE version on there is 11.0.9600.18793 with Update Version 11.0.46 (KB4036586), which does not exhibit the issue with.  Test site:

https://www.liujack.me

Do you have a link to a site which shows the bug for you so that I can test it as well?

Thanks.

**Comment by samikeijonen** [comment]
I don't see the issue on that site but I don't have time to debug the theme used in there.

However I just tested with Twenty Seventeen, vanilla _s, and couple of my own themes. They all have the issue if I remove the skip-link JS script.

Can you test with Twenty Seventeen and vanilla `_s` theme also?

**Comment by davidakennedy** [comment]
Hi @startover909! Thanks for creating this issue. That JavaScript is still needed as @samikeijonen noted, the issue persists in IE 11. I tested on Browserstack with Windows 10 and IE 11 and Windows 8.1 and IE 11, and it's still a problem.

You should see the issue if you remove the script and test. The focus will not move to the content area when you click the skip to content link after "tabbing" to it. Instead it goes back tot he top of the page.

I'm going to close this issue, but feel free to comment again if I'm missing something.

**Comment by Salamander3** [comment]
Well it's a dequeue for me.

**Comment by westonruter** [comment]
In Core [#54421](https://core.trac.wordpress.org/ticket/54421) I've proposed omitting the skip link focus fix by default, given that IE11 only accounts for 0.5% of browser market share. As such, it's not warranted to include wasted script bytes on every single page when barely anyone is using IE11 and even a smaller percentage of them will need the a11y fix. See https://github.com/WordPress/wordpress-develop/pull/1904.

**Comment by westonruter** [comment]
Note: I just committed the removal/disabling of the skip-link-focus-fix in core: https://core.trac.wordpress.org/changeset/55861

This should be re-opened.

**Comment by Ismail-elkorchi** [comment]
The skip-link-focus-fix was already removed in https://github.com/Automattic/_s/pull/1424.
