### ISSUE TITLE
menu items don't get "active" class

### ISSUE THREAD

**Issue by eyalbin** [Automattic/_s#1210]
I have this great theme installed on several sites.

for some reason, menu items don't get an active css indicator when the page is active. I tried to add this code to the functions.php file but it didn't help:

```php
add_filter('nav_menu_css_class', 'add_active_class', 10, 2 );

function add_active_class($classes, $item) {
  $class_names = array( 'current-menu-item', 'current-menu-ancestor', 'current-menu-parent', 'current_page_parent',  'current_page_ancestor' );

  if( $item->menu_item_parent == 0 && in_array( $class_names, $classes) ) {
    $classes[] = "active";
  }

  return $classes;
}
```

**Comment by samikeijonen** [comment]
There is already `current-menu-item` so is there a reason why you need `active` class?

**Comment by eyalbin** [comment]
This is the problem. there is no  **current-menu-item** class for an active page (this is what I meant by "active")

**Comment by grappler** [comment]
I am sorry I can't reproduce the issue. When using `_s` without any customizations the menu item for the current page get's the classes `current_page_item` and `current-menu-item`.

Please use a version of the theme without any customisations and disable any plugins.

What steps can I take to reproduce this issue?

**Comment by eyalbin** [comment]
You are correct, after a lot of debug, this issue is not a theme issue, thanks for the support
