### ISSUE TITLE
_s_posted_on should be split into two functions

### ISSUE THREAD

**Issue by dshanske** [Automattic/_s#1213]
Suggesting that the posted on function should be split into two functions. posted_on and posted_by. The function to generate the date and the author shouldn't be in the same function.

**Comment by David-Brown** [comment]
+1 for this. Splitting this into separate functions would make it easier to accommodate a variety of designs.

**Comment by philiparthurmoore** [comment]
This largely depends on the theme design. Modularizing it instead of lumping it into one huge function seems sensible.

**Comment by grappler** [comment]
This seems to be a good idea as we do talk about single responsibility in programming.

So we would have `_s_posted_on()` and `_s_posted_by()`?

I suppose we would output them both like so?
```php
<?php
	_s_posted_on();
	_s_posted_by();
?>
```

**Comment by dshanske** [comment]
That would be the idea.

**Comment by davidakennedy** [comment]
I'd be for this as well. Going to add a Needs Patch label.

**Comment by jrfnl** [comment]
As #1226 has been merged, this issue should be closed ?

As a side-note - I think the current split as has been merged is a deterioration from a localization point of view as the sentence structure is now broken up in two methods and two individually translatable phrases which together form a sentence with the sentence order presuming English / left-to-right sentence structure.

**Comment by laurelfulford** [comment]
Ah thanks @jrfnl - closing!

I merged the PR because there seemed to be general consensus for it -- if you think it should be revisited, please go ahead and open a new issue. Thank you!
