### ISSUE TITLE
Slideshows

### ISSUE THREAD

**Issue by PaulBart** [Automattic/_s#1219]
Hi.  I've been using _'s for a couple of years without issues.  But this weekend I started a new site, and I can't for the life of me get the usual sliders I use to work? I've did a similar site a couple of weeks ago.  I've reinstalled WP and put in a fresh _'s theme and the problem still exists! 

I should say when switching to twenty seventeen theme or another blank theme "bones" the slide show works...

Any ideas as I'd rathe continue to use _'s if I can! But at the moment the theme is un useable to me, as in I don't know enough to fix this issues. 

Thanks 

https://brandingvietnam.com/testsite/glrestaurant/

**Comment by bahiirwa** [comment]
Hey @PaulBart , This is not issue from _s. Check your scripts application. My console showed me you have errors running the JS from plugin. Check image below

![image](https://user-images.githubusercontent.com/7713923/31882127-7808d204-b7ee-11e7-970c-d659fd128d80.png)

**Comment by PaulBart** [comment]
But the plugin works on other theme's? It even works on other sites with the _'s theme done in the past? I wondered if the theme had been updated recently, and there is now a conflict?

**Comment by PaulBart** [comment]
here is the same plugin in a site I did the other week - works fine...

https://brandingvietnam.com/testsite/bizcon/test/

**Comment by grappler** [comment]
I tested the plugin on my local environment on `_s` and the slider worked fine.

In your case the slider is not working as the file `cache/nextend/web/n2-ss-2/n2-ss-2.js` is missing.

For that reason this seems to be a Smart Slider issue.

**Comment by PaulBart** [comment]
@grappler  That file isn't missing and I've built this locally and on a remote server independently of one another and I get the same result every time. I can also switch the theme to 2017 and the slider works. OK well looks like I'm at a dead end.
