### ISSUE TITLE
How do I start the server locally?

### ISSUE THREAD

**Issue by connor11528** [Automattic/_s#1235]
I downloaded this project from [the website](https://underscores.me) and have it on my local machine using PHPStorm. I've created a mysql database through Sequel Pro

How do I start the PHP server and get the code running locally? I am fine using the terminal or something like wp-cli if it's best practice

**Comment by caraya** [comment]
This is not a standalone website. It's a Wordpress theme that will only work as part of a Wordpress installation. 

Assuming that you have a local wordpress installation to do development in:

1. Move or copy the folder to a local wordpress installation under `/wp-content/themes`
2. Open wordpress in a web browser
3. Go to your admin screen and activate the theme. 

If you're doing development in a remote server I'll trust you know what you're doing.

**Comment by connor11528** [comment]
Okay got it. I'll setup a wordpress site and then use this as the theme
