### ISSUE TITLE
Duplicate search field

### ISSUE THREAD

**Issue by pixelstrolch** [Automattic/_s#1241]
If you search and get no result, there will be a search field inside `#primary`. Since there must be a search form in any other area, I think there is no need to [add another one](https://github.com/Automattic/_s/blob/master/template-parts/content-none.php#L40).

However, with the `else` case the user didn't use a search form and we have no certainty that there is one in another area.

**Comment by samikeijonen** [comment]
The main search could be behind some kind of toggle in the header, or somewhere else we can't predict. I'd leave this up to theme author does it make sense to have search form in "not found".

No big deal removing it though.

**Comment by grappler** [comment]
I think it may be OK to remove the search bar when getting no results.

There is one case where a search form may not exist. If someone searches a keyword from the 404 page and then gets no results and there is no other search field. 

Looking at the no search results page I see that we could make a few improvements. If we remove the search field then we can only see the search keyword in the URL.

Here are the screenshots:

**A search without a result:**
![image](https://user-images.githubusercontent.com/1785641/33808342-f1b8c80e-dde4-11e7-8bc8-14c943f677d3.png)

**A search with a result:**
![image](https://user-images.githubusercontent.com/1785641/33808346-0488c416-dde5-11e7-90ed-5bb7132535f9.png)

**Comment by pixelstrolch** [comment]
> The main search could be behind some kind of toggle in the header, or somewhere else we can't predict.

Agree. This unpredictable place is usually not the primary content area. I'd say the search field is in the complementary area or inside the navigation. 

> There is one case where a search form may not exist. If someone searches a keyword from the 404 page and then gets no results and there is no other search field.

I couldn't reproduce this. If I remove [get_search_form();](https://github.com/Automattic/_s/blob/master/template-parts/content-none.php#L40) for the 'no results' case, there has to be a search field inside the navigation or as a widget in the complementary area. I believe this search field will be there if the user had the possibility to search in the first place. 

There is a search field inside `404.php` which is needed because there is no sidebar loaded. 

> I'd leave this up to theme author …

Totally works for me

**Comment by Ismail-elkorchi** [comment]
I agree with @samikeijonen's comment.  I'd say we should leave this up to theme authors to modify as they see fit.
