### ISSUE TITLE
underscores not working with Visual Composer Animation.

### ISSUE THREAD

**Issue by onmarketing** [Automattic/_s#1242]
Hi,

I created underscores theme with Visual Composer plugin, Single Image - select animation fade in then save it then went blank on Frontend
  
![capture 1](https://user-images.githubusercontent.com/29661125/33840356-97153e02-de8c-11e7-9dd1-c44853822bb2.PNG)

Does anyone know about this? Does anyone created underscores theme with Visual Composer plugin before?

Thanks,

Shaun.

**Comment by grappler** [comment]
I don't really see why there should be an issue as `_s` is a basic theme with not big features.

Normally Javascript is involved with animation. I would check the Developer Tools in the browser to see if there were any JS errors.

The GitHub repo is used for tracking bugs and not development support. It would be best to get help from StackOverflow or the WordPress.org forums.

**Comment by laurelfulford** [comment]
As this issue doesn't seem to be related to Underscores, I'm going to close this issue.

@onmarketing if you do track down the source and it does somehow relate to code here, please feel free to come back and open a new issue.
