### ISSUE TITLE
Readme.txt shows incorrect 'Requires at least' version number

### ISSUE THREAD

**Issue by joyously** [Automattic/_s#1249]
https://github.com/Automattic/_s/blob/115dd8209c41669d1c6c173cbe533523bbc73158/readme.txt#L6

This line should be referencing 4.5 because of the use of `the_custom_logo()`.
Drop a zip on https://wpseek.com/pluginfilecheck/ to see.

**Comment by crunnells** [comment]
Thanks for the report @joyously!
