### ISSUE TITLE
Refactor _S to modern CSS layout standards using grid and flex

### ISSUE THREAD

**Issue by mor10** [Automattic/_s#1250]
_s should adopt modern layout modules at core:

- `display: grid;` for two-dimensional layouts
- `display: flex;` for one-dimensional layouts
- `float` for in-context floating of elements

This moves _s into the modern era of web layouts and lays the groundwork for grid-based themes. Using `grid` and `grid-template-areas` for global layouts and `flex` for navigation areas allows a drastic simplification of the theme's HTML markup while allowing the theme author greater control over the responsive layouts they want to build.

Additionally, flex and grid both honor text direction meaning this refactoring would make _S fully RTL compatible out of the box without the need for an additional stylesheet.

All modern browsers support CSS grid and flex, and there are available solutions for creating sufficient fallbacks for older browsers that individual theme authors can implement based on their specific requirements.

**Comment by mcsmithers** [comment]
I'd like to give this a shot is that's okay.  I am, still pretty new to open-source contribution so feedback is appreciated.

**Comment by mor10** [comment]
There's a pull request for this ticket. Would love a second pair of eyes on it.

**Comment by laurelfulford** [comment]
Hi @mor10! Thanks for submitting this issue, and the related PR. 😄 

We’ve discussed this as a team, and think this is a good direction.

We’ll review the PR in the near future!

**Comment by philiparthurmoore** [comment]
Two things:

1. If this is adopted (sounds like a good idea) can we please ensure that it is made very clear that the layout of _s has changed, either on the Underscores website (opportunity to freshen up the site) or on GitHub? This is a non-trivial change that requires a certain level of understanding of web layouts in CSS that some developers do not have.
2. For browser coverage, can we please make sure that minimum required browser version is clear after making this change?

This is a relatively minor change as far as catching up with modern standards goes, but it's a major change for _s and appropriate documentation would be great.

**Comment by DAVRTZ** [comment]
I'm building a underscores theme exactly with css grid and flex

**Comment by nboaldin** [comment]
+1
