### ISSUE TITLE
Comply with up-to-date coding standards

### ISSUE THREAD

**Issue by jrfnl** [Automattic/_s#1253]
There are two open PRs to deal with updating `_s` to comply with more recent coding standards, PR #1157 and #1186.

Both of these are based on WPCS `0.12.0`, but in the mean time WPCS `0.13.0` and `0.14.0` have come out.

I'm quite willing to update the ruleset and code to comply with WPCS `0.14.0`, building onto the existing work in the open PRs and creating a new PR which encompasses the complete fix, allowing the builds to pass again.

However, I'm not really looking to waste my time on creating a PR which will be left open for six months and by that time will be outdated again.

So... my question really is: if I create the above mentioned PR, will it get attention and be merged within a reasonable time ?

Or maybe I should ask: is there anyone with merge rights still actively interested in maintaining `_s` as a base-theme and example for all ? Or is this project effectively dead ?

/@cc @grappler @davidakennedy @karmatosed

**Comment by samikeijonen** [comment]
All I can say that you pinged the right persons. And the project is active and maintained. But it's really really slow. 

> So... my question really is: if I create the above mentioned PR, will it get attention and be merged within a reasonable time ?

Waiting time can be months, which can happen in Core also.

**Comment by dev-masta** [comment]
I've been using _s for dozens of my projects and this is the first time I stopped by at Github and realized that there are open issues and PRs waiting to be merged and that you guys might need help.

So if there's anything I can do to help, point me in the right direction.
I might not invest 40 hours per week, but at least it will become a little less slow...

**Comment by samikeijonen** [comment]
@dev-masta Any help is appreciated. I recommend testing open PRs and comment if you find bugs or something else.

**Comment by davidakennedy** [comment]
Hi @jrfnl! Thanks for creating this issue.

> There are two open PRs to deal with updating _s to comply with more recent coding standards, PR #1157 and #1186.
>
> Both of these are based on WPCS 0.12.0, but in the mean time WPCS 0.13.0 and 0.14.0 have come out.
> 
> I'm quite willing to update the ruleset and code to comply with WPCS 0.14.0, building onto the existing work in the open PRs and creating a new PR which encompasses the complete fix, allowing the builds to pass again.
> 
> However, I'm not really looking to waste my time on creating a PR which will be left open for six months and by that time will be outdated again.

We value the time any contributor puts into PRs, so thank you! I think where those PRs got sidetracked was that they relied on other PRs and it became difficult to track what needed to happen when.

> So... my question really is: if I create the above mentioned PR, will it get attention and be merged within a reasonable time ?

Yes, go for it. I will make sure it gets merged. Perhaps a better approach to this type of thing is to wait until the new WPCS version comes out, then make the PRs with the needed changes? That might result in less issues with things getting out of date.

> Or maybe I should ask: is there anyone with merge rights still actively interested in maintaining _s as a base-theme and example for all ? Or is this project effectively dead ?

Yes. It's very much an active project. We tend to work on _s in spurts. Sometimes, addressing a few issues and PRs at a time, and sometimes doing bigger sprints on it. Usually there are gaps in between as we juggle other projects that the Theme Team (the team at Automattic which maintains _s) works on.

Let me know your thoughts on the PR approach, and thanks again for contributing!

**Comment by davidakennedy** [comment]
@dev-masta Like @samikeijonen said, we could always use help. We usually try to label issues that need a patch. You can also always test current PRs and comment whether they worked or provide feedback.

Thanks for being interested, and would love to see some contributions from you in the future!

**Comment by jrfnl** [comment]
> Yes, go for it. I will make sure it gets merged. Perhaps a better approach to this type of thing is to wait until the new WPCS version comes out, then make the PRs with the needed changes?

That's when the currently open PRs where created (when WPCS 0.12.0 came out), but as those were never merged....

Anyway, I think WPCS 1.0.0 is still quite a ways off, so getting the code ship-shape against WPCS 0.14.0 would be useful.

I'll see if can do a quick round.

**Comment by jrfnl** [comment]
@davidakennedy Ok, so, I've created a PR to sort this out #1267. Keeping my fingers crossed this will be merged quickly.
