### ISSUE TITLE
Hidden characters in comments-title

### ISSUE THREAD

**Issue by Magical1** [Automattic/_s#1258]
I was trying to restyle the comments area on my _s theme and there appears to be something inserting extra white space/hidden characters in the `comments.php` title generated in the `<h2 class="comments-title"></h2>` tags, I only noticed as I tried to centre align the content with css and found that it remained right aligned.

I haven't been able to work out the cause, but a solution or fix would be most welcome

**Comment by crunnells** [comment]
@Magical1 thanks for the report! If you could help us further by showing us some screenshots so we know what to look for, or information on what specific circumstances you are able to reproduce the issue, that would be fantastic. 🙂

**Comment by grappler** [comment]
Closing the issue as there has been no feedback.
