### ISSUE TITLE
WooCommerce section in customizer

### ISSUE THREAD

**Issue by kloon** [Automattic/_s#1259]
Since WooCommerce 3.3.0 we have added a new WooCommerce section in the customizer. It seems that _s with WooCommerce support also add one which results in duplicate sections.

Would it be possible to change the _s section to use the WooCommerce one as some customers find it confusing having two of the same sections.

ie https://wordpress.org/support/topic/display-options-on-customizer/

**Comment by WPprodigy** [comment]
Probably will be covered under this change, but just wanted to note again:

Underscores should remove `loop_shop_columns` and `loop_shop_per_page` filters and use new theme support options for those.

**Comment by nielslange** [comment]
Related to #1278 and `loop_shop_columns` and `loop_shop_per_page` have been removed in #1281.
