### ISSUE TITLE
the_content()

### ISSUE THREAD

**Issue by AndiZu2** [Automattic/_s#1261]
Hi Folks have been working on my site and have just added woocommerce to it! but have now noticed that Elementor won't let me edit my page content anymore! I get the following error!

Sorry, the content area was not found in your page
You must call ‘the_content’ fiction in the current template. in order for Elementor to work on this page

Can someone please tell me what I'm supposed to do and what code to add to which file?

Many thanks

**Comment by slushman** [comment]
Have you contacted the Elementor developer for support? This repo is meant for tracking bugs in the _s starter theme, not supporting WooCommerce or other themes.

**Comment by davidakennedy** [comment]
Hi @AndiZu2! Thanks for creating this issue! Like @slushman said, I would check with Elementor's developer docs if you need help integrating it into a theme you're building.

Since this isn't related to Underscores itself, I'll go ahead and close it. Good luck with your theme!
