### ISSUE TITLE
Images alignment bottom margin

### ISSUE THREAD

**Issue by carlosromanxyz** [Automattic/_s#1273]
Please consider add a bottom when user align images (center, left, right)

`margin-botom: 1.5em; ` it's ok.

I try it and this is result

![fireshot capture 86 - nosotros_](https://user-images.githubusercontent.com/20117120/36812172-fe31915c-1cae-11e8-825a-9ac3c5e9b1f8.png)

And no margin on bottom:

![fireshot capture 87 - nosotros2_](https://user-images.githubusercontent.com/20117120/36812252-5569f9f0-1caf-11e8-80ad-2e93ff22b609.png)

Thanks :)

**Comment by sixhours** [comment]
We add bottom margins to most other elements in the stylesheet, so this makes sense to me.

**Comment by laurelfulford** [comment]
I think this makes sense, too.

**Comment by Atiladanvi** [comment]
I think equal. But i'ts is a customizer for a especific job.

**Comment by Ismail-elkorchi** [comment]
@carlosromanxyz Thank you for reaching out!

Closing as `margin-botom: 1.5em;` was added to  `.alignleft`, `.alignright` and `.aligncenter` classes in https://github.com/Automattic/_s/pull/1301.
