### ISSUE TITLE
PHPCS sniffs in VS Code

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#1275]
Thanks @jrfnl for new `phpcs.xml.dist`. I'm also using PHPCS sniffs in [VS Code](https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs) but it somehow stopped working after update.

When removing line `<arg name="basepath" value="./"/>` sniffs works again. Any idea is that a bug in VS Code Plugin or what does `basepath` do?

**Comment by samikeijonen** [comment]
Thanks for quick answer!

**Comment by sixhours** [comment]
Going to close this since it sounds like a VS issue.
