### ISSUE TITLE
Double quotation mark

### ISSUE THREAD

**Issue by zimnyd** [Automattic/_s#1276]
https://github.com/Automattic/_s/blob/72e34ef6bc795cdb7fec74c82577a7ce4e61076d/comments.php#L41
In different languages double quote mark is writing in different way. For example in polish is used unicode "201E" for left and "201D" for right quotation mark. See: https://en.wikipedia.org/wiki/Quotation_mark

I propose use :lang() atribute like:
```
.comments-title span {
    &:before {
        content: "\201C";
    }
    &:after {
        content: "\201D";
    }
    &:lang(pl) {
        &:before {
            content: "\201E";
        }
        &:after {
            content: "\201D";
        }
    }
}
```

**Comment by grappler** [comment]
In that case for Polish you would translate `&ldquo;` as  `&bdquo;`  and you would leave `&rdquo;` as is.

There is no  need for a CSS solution.
