### ISSUE TITLE
hardcoded values in woocommerce boilerplate

### ISSUE THREAD

**Issue by smartcatdev** [Automattic/_s#1278]
In https://github.com/Automattic/_s/blob/master/inc/woocommerce.php#L78
```
/**
 * Products per page.
 *
 * @return integer number of products.
 */
function designr_woocommerce_products_per_page() {
    return 12;
}

add_filter( 'loop_shop_per_page', 'designr_woocommerce_products_per_page' );

/**
 * Product gallery thumnbail columns.
 *
 * @return integer number of columns.
 */
function designr_woocommerce_thumbnail_columns() {
    return 4;
}

add_filter( 'woocommerce_product_thumbnails_columns', 'designr_woocommerce_thumbnail_columns' );

/**
 * Default loop columns on product archives.
 *
 * @return integer products per row.
 */
function designr_woocommerce_loop_columns() {
    return 3;
}

add_filter( 'loop_shop_columns', 'designr_woocommerce_loop_columns' );
```

**Comment by slushman** [comment]
Can you explain this issue a bit? I believe each filter is supposed to return a number, so I'm not sure what the problem is here.

**Comment by nielslange** [comment]
@smartcatdev and @slushman: The `products per page` and the `products per row` can now be adjusted via the customizer.  

Furthermore, I wasn't able to figure out where to see `designr_woocommerce_thumbnail_columns()` in action. I've changed the return values from 1 to 10 but wasn't able to detect any change on the site. It looks like this function has no effect on this theme and could be removed.
