### ISSUE TITLE
Adjusting the width of the Primary Menu (or it's container)?

### ISSUE THREAD

**Issue by mikerekka** [Automattic/_s#1287]
I'm trying to expand the width of my Main Menu (or it's container) so that when a visitor switches language, the menu doesn't carry over to the next line down.

If you want to see what I mean check out www.flexmse.com and switch from English to French or Spanish.

I've tried a number of things in the stylesheet but can't get it to adjust.  Help!! 

Thanks in advance!

![5-4-2018 8-12-53 am](https://user-images.githubusercontent.com/302419/39635974-cc2203e8-4f73-11e8-9e2d-b8193e9c4cde.png)

![5-4-2018 8-13-32 am](https://user-images.githubusercontent.com/302419/39635981-d017922e-4f73-11e8-9d35-b27357bbd580.png)

**Comment by grappler** [comment]
Hi!

The GitHub repo is to track bugs and improvements to the `_s` theme and not provide customisation support.

Please ask your question in the [WordPress.org support forum](https://wordpress.org/support/) or [WordPress Stack exchange](http://wordpress.stackexchange.com/).

Thanks! 😄
