### ISSUE TITLE
Add custom color scheme in admin personalize page with pallets

### ISSUE THREAD

**Issue by Atiladanvi** [Automattic/_s#1290]
The custom coloris util to dont touch in core. Is a power full mode to change the nav background and footer. I can implements this function. When do ?

**Comment by grappler** [comment]
Hi!

The GitHub repo is to track bugs and improvements to the `_s` theme and not provide customisation support.

Please ask your question in the [WordPress.org support forum](https://wordpress.org/support/) or [WordPress Stack exchange](http://wordpress.stackexchange.com/).

Thanks! 😄

**Comment by Atiladanvi** [comment]
Thanks. So sorry for this useless issue
