### ISSUE TITLE
Add PostCSS Partials

### ISSUE THREAD

**Issue by cedon** [Automattic/_s#1292]
I have created a refactored set of SASS partials to allow developers to utilize _s in a PostCSS workflow. Since PostCSS allows access to tools not necessarily available to SASS out of the box, like CSS Next, I thought this might be an option to include in repository.

Pull request is being submitted from my fork.

**Comment by mtomas7** [comment]
I based my theme on _s and currently I'm evaluating the option to use PostCSS and this is a great help to start! Thank you!

**Comment by Ismail-elkorchi** [comment]
Hello @cedon ! Thank you for the issue report and the Pull Request.

While PostCSS offer more flexibility thanks to all the available plugins, it depend on more moving parts and its maintenance is more complex. It's much simpler with SASS since it depend only on `node-sass`.
