### ISSUE TITLE
How to add full width background color to header only

### ISSUE THREAD

**Issue by nabtron** [Automattic/_s#1295]
I tried underscores template today and was amazed to see that the header / main / footer does not contain a sub div to contain all the elements. 

I am using a fixed width, and thus need to define width of the content. Now if i want to give a full width background to header or footer, it's impossible to give width to the header.... 

Check the image below: 
<img width="1006" alt="screen shot 2018-05-29 at 5 56 13 am" src="https://user-images.githubusercontent.com/9471128/40632885-0a02f3ee-6305-11e8-8e46-806665e2f55f.png">

Or am i too noob to do it the right way? Can anyone suggest please? 

Please note, i want to have a solution where this can be done via css only, without editing other theme files.

**Comment by alaczek** [comment]
Hi @nabtron! Great to see your interest in _s!

_s is a minimal starter theme, and as such it is meant to be edited to suit your needs. It also means it will not cover all use cases out of the box, and you'll probably run into more situations that are hard or impossible to address with CSS alone. 

In this case, you could try restricting the header content width by adding left and right padding, but ultimately it would probably be best to edit header.php and add the necessary containers.

Cheers!

**Comment by nabtron** [comment]
So why don't we add a wrapper div within header, footer and main for everyone? instead of asking all of them to edit it for this basic thing even? whats the purpose of a starter template if its incomplete and people have to code basic stuff themselves too

**Comment by grappler** [comment]
I think this is the first time in the last 5 years that someone has requested this feature.

Generally it is best to have a little HTML tags. These extra divs will not be used by everyone.

https://help.github.com/articles/ignoring-files/#create-a-global-gitignore
