### ISSUE TITLE
Docker for development

### ISSUE THREAD

**Issue by marcusmyers** [Automattic/_s#1298]
Would there be any interest in adding a `docker-compose.yml` for developing a theme using docker? I recently used _s, for the first time, to develop a theme and was wondering if developing in docker would be an added plus. I wouldn't mind putting together a pull request with some basic instructions.

**Comment by marcusmyers** [comment]
Good point. I guess I was thinking about the people just getting started with theme development having to setup their machine with php, mysql and apache/nginx or with a vagrant box with everything installed already.

**Comment by dingo-d** [comment]
On any machine, having one docker file or vagrant file won't help with kickstarting the development. They still need to install those programs, and do some setting up :D 

In the end setting up your own development environment is a great way to understand a bit more how these technologies work together :)

**Comment by grappler** [comment]
I know that people have found it helpful having a docker file with Gutenberg. But I don't think this project is big enough for a docker file to be needed.
