### ISSUE TITLE
Missing sass compilation scripts and npm packages!

### ISSUE THREAD

**Issue by hasnatbabur** [Automattic/_s#1306]
Missing sass compilation scripts and npm packages!

**Comment by Luc45** [comment]
I came here for this as well. First of all, thanks for all the effort everyone has put in this amazing theme. It's hard to find a non-opinionated theme to start things on.

But indeed, it would be nice to have files we need to compile SASS if we choose the _sassify version.

**Comment by cinghaman** [comment]
Thanks

**Comment by hasnatbabur** [comment]
@cinghaman 
Hi, I fall into similar error many times before and a possible solution for you may be running 'npm rebuild node-sass' script after installing packages.

Please have a look here also:
https://stackoverflow.com/questions/46515077/unable-to-install-node-sass-in-my-project?rq=1

Thanks.

**Comment by cinghaman** [comment]
Thanks @hasnatbabur I created my own package.json and grunt file all good

**Comment by Ismail-elkorchi** [comment]
@hasnatbabur Thank you for reaching out!

I'm going to close this issue since it is a duplicate of https://github.com/Automattic/_s/issues/1149. You may want to subscribe there for updates.

**Comment by GoyalAnuj973** [comment]
Still not able to resolve the issue!!
