### ISSUE TITLE
Why is .widget-area outside of .site-content?

### ISSUE THREAD

**Issue by olegovk** [Automattic/_s#1307]
It seems from [previous discussions](https://github.com/Automattic/_s/issues/727) that `.widget-area` used to be a sibling of `.content-area`, i.e. inside of `.site-content`. According to naming convention it looks very logical this way. However now `.widget-area` is outside of `.site-content`.

Is there a specific reason why it's outside now, making it a site-level element, rather than part of site content?

**Comment by GitaStreet** [comment]
Where do you see this? 
I see the starting .site-content starts in header.php and closing in footer.php.

index.php and page.php use to get_sidebar() before get_footer() - so .widget-area is still wrapped in the .site-content.

**Comment by olegovk** [comment]
How embarrassing... you are right.
Thanks for kindly answering, though.
