### ISSUE TITLE
Help with custom header  

### ISSUE THREAD

**Issue by Lootstep** [Automattic/_s#1308]
In custom-header.php  it says to uncomment a line of code in functions.php but never says where. 
In my  functions.php all  the lines are uncommented from the start.
I tried to put the 

> <?php the_header_image_tag(); ?>
In my header.php it shows up, but not the right size what my custom-header.php says. And there is  small unwanted space below  php the_header_image_tag.

Any help would be appreciated ty

**Comment by komodev** [comment]
hi @Lootstep 
What do you mean by 

> ### unwanted space below php the_header_image_tag.

where do you have unwanted space, in a template of header or custom-header.php file?
Or is it maybe rendered in your browser with some empty-space below header image?

Can you clear up a bit so I can help you.

cheers

**Comment by Lootstep** [comment]
I forgot my site so you and see
[https://gfxhideout.com](url)

I need to know how to activate my custom header

**Comment by komodev** [comment]
just add the code snippet found in the comments of inc/custom-header.php to your header.php template.

**Comment by komodev** [comment]
also read about custom headers here
https://developer.wordpress.org/themes/functionality/custom-headers/

**Comment by Lootstep** [comment]
Good to go now ty
