### ISSUE TITLE
Nested comments

### ISSUE THREAD

**Issue by label-e** [Automattic/_s#1309]
I noticed that the nested comments don’t seem to work. when you click at ‘reply’ under a given comment, the new comment is still added at the end of the row, so they are sorted on time. I even tried it with a clean installation of the template but even than it didn't seem to work.

So it looks like this now:

- 1. comment 1
- 2. comment 2
- 3. comment 3
- 4. reply at comment 1

Anybody knows how to fix it?

**Comment by crunnells** [comment]
Comment markup is dependent on the core function `wp_list_comments()` (see documentation [here](https://codex.wordpress.org/Function_Reference/wp_list_comments )), and by default (see https://github.com/Automattic/_s/blob/master/comments.php#L53) `_s` should display replies below the parent comment:

```
* Comment 1 (ID: 1)
  * Reply to Comment 1  (ID: 4)
* Comment 2 (ID: 2)
* Comment 3 (ID: 3)
```

I'm not sure why it would be behaving the way you're seeing, short of some non-default setting in the theme, your WP install, or a plugin that changes comment markup.

**Comment by crunnells** [comment]
Closing this issue since we haven't heard back from the reporter in a few months. Feel free to re-open the issue if you have further information.
