### ISSUE TITLE
Unwanted space on the top of my header

### ISSUE THREAD

**Issue by Lootstep** [Automattic/_s#1312]
I cant not figure out  what's causing a margin / padding on my header. Is it a script? Its on the very top of [my site](https://gfxhideout.tk) thank you for your time.
Ps im on a tablet until my comp is fixed

**Comment by wp1111** [comment]
With the inspector (in Chrome CTRL+Shift+I) it is easy to find such margins, paddings or in your case a border. I made some screenshots that may help you to find and solve such problems.

### 1) Open inspector and find your element in the html-code
![masthead1](https://user-images.githubusercontent.com/42349383/44088333-edfb90f0-9fec-11e8-8145-523abb9068a6.jpg)

### 2) Find the CSS on the right and toggle it off
![masthead2](https://user-images.githubusercontent.com/42349383/44088436-49e6dc12-9fed-11e8-84d8-7b2d9bd8e4c3.jpg)

### 3) Test to overwrite a CSS rule in element.style
![masthead3](https://user-images.githubusercontent.com/42349383/44088492-7507249c-9fed-11e8-8ea7-fbcb4e48069e.jpg)

### 4) Now delete or overwrite the CSS in your CSS or SCSS file, i. e.
```
.site-head-gfx {
    border-top: 0px;
}
```

Hope that helps,
Sam

**Comment by Lootstep** [comment]
Im sorry but i want the top border, Is  there a reason why there is space on the top even with out the top border. Dose it have something  to do with em instead of px ?  This is my first layout using em

**Comment by Lootstep** [comment]
Nvm i forgot to add the extra width of the top border my bad ty
