### ISSUE TITLE
Unable to fill in the credit card details

### ISSUE THREAD

**Issue by craigsteel** [Automattic/_s#1313]
Hi I have created a site using _s with advanced options WooCommerce boilerplate and _sassify 

https://taxispirit.com/

It all works really well except for WooCommerce Stripe Gateway plugin
When I proceed to checkout and chose CREDIT CARD (STRIPE) it won't allow me to fill in the Credit Card details

I have contacted Woocommerce Strip Support
Luminus (@luminus)
Automattic Happiness Engineer

https://wordpress.org/support/topic/unable-to-fill-in-the-credit-card-details/

This is his reply 

"That all looks fine from here.
This kind of problem is usually caused by either a conflict with your theme or with another plugin.
The best way to determine if the issue is being caused by a theme and/or plugin is to temporarily switch your theme to Storefront and disable all plugins except for WooCommerce. If you can install plugins, install Health Check. On the troubleshooting tab, you can click the button to disable all plugins and change the theme for you while you’re logged in to that session without affecting normal visitors to your site. Note that Health Check may not count Storefront as a default theme, so you can also use Twenty Seventeen as well.
If that resolves the issue, then one-by-one you can switch back your theme and re-enable your plugins, testing in between, until you find the one causing the conflict."

I have done all the above and the problem lies with the theme Underscores based theme. 

I'm at a loss of what to do to fix this. Can you please please help!!?

Here is the system report
`
### WordPress Environment ###

Home URL: https://taxispirit.com
Site URL: https://taxispirit.com
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.30-0ubuntu0.16.04.1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.22-22-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.53MB
Database Data Size: 2.50MB
Database Index Size: 1.03MB
wp_woocommerce_sessions: Data: 1.17MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_csp3_subscribers: Data: 0.02MB + Index: 0.00MB
wp_cspv5_pages: Data: 0.02MB + Index: 0.00MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 0.17MB + Index: 0.06MB
wp_postmeta: Data: 0.38MB + Index: 0.17MB
wp_posts: Data: 0.17MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

acf-field: 76
acf-field-group: 12
attachment: 40
book: 1
customize_changeset: 7
master-popups: 2
nav_menu_item: 16
oembed_cache: 1
page: 12
post: 61
product: 3
revision: 25
shop_order: 4
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.7.2
Advanced Custom Fields: by Elliot Condon – 4.4.12
All-in-One WP Migration: by ServMask – 6.73
BJ Lazy Load: by Bjørn Johansen
Aron Tornberg
angrycreative – 1.0.9

Contact Form 7: by Takayuki Miyoshi – 5.0.3
Custom Post Type UI: by WebDevStudios – 1.5.8
Health Check & Troubleshooting: by The WordPress.org community – 1.2.1
Master Popups: by MaxLopez – 2.2.7
SVG Support: by Benbodhi – 2.3.15
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.3
WooCommerce Stripe Gateway: by WooCommerce – 4.1.8
WooCommerce Services: by Automattic – 1.15.1
WooCommerce: by Automattic – 3.4.4
WordPress Importer: by wordpressdotorg – 0.6.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Taxi Spirit
Version: 1.0.0
Author URL: https://craigsteel-design.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: taxispirit/woocommerce/archive-product.php
taxispirit/woocommerce/content-product.php
taxispirit/woocommerce/content-single-product.php
taxispirit/woocommerce/global/wrapper-end.php
taxispirit/woocommerce/global/wrapper-start.php
taxispirit/woocommerce/single-product.php

**Comment by Luminus** [comment]
Hi @craigsteel,

Please keep your support requests to the appropriate forum as this is not a support forum. I'll go ahead and close this issue now.
