### ISSUE TITLE
Duplicated <time>?

### ISSUE THREAD

**Issue by rafafields** [Automattic/_s#1315]
Hello!

I realised a duplication in the date. Is it a bug?

https://github.com/Automattic/_s/blob/9274f322d0d40cef1e0c15a34aba5678862f1b17/inc/template-tags.php#L17

**Comment by slushman** [comment]
I don't believe so. One is the publication date and the other is the last time it was updated. For a new post, those could be the same. It would be different for older posts that have been updated. if you don't need one of those for your particular theme, you can remove one or the other.

**Comment by alaczek** [comment]
Yep, this is not a bug. If you'd rather not include the date post was updated on, you're welcome to remove that bit in your theme.
