### ISSUE TITLE
Woocommerce zoomimg not working in product page

### ISSUE THREAD

**Issue by bubbledesign** [Automattic/_s#1316]
I use _s for build theme but I'm having issues with zoomImg in product page.

Woocommerce zoomImg not working in product page, when you hover product image there is no zoom in on hover. Why zoomImg not in the class?

functions.php

`function u_setup() { add_theme_support( 'woocommerce' ); add_theme_support( 'wc-product-gallery-zoom' ); add_theme_support( 'wc-product-gallery-lightbox' ); add_theme_support( 'wc-product-gallery-slider' ); } add_action( 'after_setup_theme', 'u_setup' );`

See screenshot: [Single Product page](Single Product page)

Does anyone know about this?

**Comment by slushman** [comment]
You'd need to contact the developers for that plugin. This repo is meant for tracking bugs and fixes for _s itself. I don't know that plugin or why it wouldn't work with _s.

**Comment by bubbledesign** [comment]
Ok I will do. I don't understand why it not working.

**Comment by bubbledesign** [comment]
@slushman Woocommerce said nothing wrong with their plugin, something wrong with _s theme, please check it on your localhost.

**Comment by grappler** [comment]
I tested it quickly and the magnifying glass icon was shown in the corner.

The problem that I saw that all images were shown instead of just one.
![image](https://user-images.githubusercontent.com/1785641/48315496-3681b680-e5d7-11e8-827c-d382aa1471ca.png)

**Comment by bubbledesign** [comment]
Hi @grappler Still not working, I've been researched it to solve it but still not working.

**Comment by grappler** [comment]
@bubbledesign Can you share a screenshot like I did? Did you disable all plugins except for WooCommerce?

**Comment by bubbledesign** [comment]
@grappler https://i.stack.imgur.com/mYSJD.png

**Comment by grappler** [comment]
You have added your own CSS which may be causing the issue. Please use a bare `_s` theme without using an custom CSS to reproduce the issue.

**Comment by bubbledesign** [comment]
@grappler I have download _s theme here via Github but still same issue

**Comment by grappler** [comment]
I can't reproduce the issue so I would need you to show the issue with a screenshot.

**Comment by WebAssembler** [comment]
When viewing a single product I could only get the zoomImg class to appear when the browser viewport was thinner than the product image. To reproduce, set a large product image > 1000px for example and then reduce the size of the browser (around 500px) and reload the page.

In your [example screenshot](https://i.stack.imgur.com/mYSJD.png) you asked why zoomImg was not present on the main image, well I was only seeing the ```zoomImg``` class on the image outside of the main one with the role of ```presentation``` which I've highlighted in this screenshot from my localhost [https://imgur.com/a/TdYDd0P](https://imgur.com/a/TdYDd0P)

**Comment by Ismail-elkorchi** [comment]
I was able to reproduce. https://github.com/Automattic/_s/pull/1406 is a simple fix that makes gallery zoom and gallery lightbox both work.
