### ISSUE TITLE
Some Bug for default template

### ISSUE THREAD

**Issue by princ-imran** [Automattic/_s#1317]
![screenshot_2](https://user-images.githubusercontent.com/23343155/45593296-f8845f80-b9a4-11e8-9a8a-2f8df0ffd4e2.png)
When generate a new theme i got a problem. Like that picture. When update my post show modify date and published date also. bellow this picture.
![screenshot_3](https://user-images.githubusercontent.com/23343155/45593312-852f1d80-b9a5-11e8-82e7-5f5f8598a362.png)
Thanks.

**Comment by zimnyd** [comment]
It's not a bug.
The first date is the date of post create. The second one is the date for post update. If you update post, the second date will be different. To hide one of theme I use:
`/* updated - published */`
`.updated:not(.published) {`
`    display: none;`
`}`

**Comment by alaczek** [comment]
Yep, you should not be seeing the date a post was updated on. The CSS needed to hide it is already present in the style.css: https://github.com/Automattic/_s/blob/master/style.css#L849

Did you by any chance edit the stylesheet and removed this bit?

**Comment by grappler** [comment]
@princ-imran Were you able to sort the issue out?

**Comment by crunnells** [comment]
Closing this issue since we haven't heard back from the reporter in a few months.
