### ISSUE TITLE
Woocommerce Shop page pagination is not works 

### ISSUE THREAD

**Issue by bubbledesign** [Automattic/_s#1318]
Woocommerce Shop page pagination is not works, when I clicked page 2,3,4,5 but only showing page 1.

Woocommerce said "I'm just suggesting the debug process I usually go through when trying to find the source of a problem. default theme + WooCommerce"

Would you be able to find out why it not works?

Storefront works on pagination but not _s

**Comment by alaczek** [comment]
Hi there! I cannot replicate the issue on my local test site with _s (without any modifications). _s uses core function `[the_posts_navigation()]` ([documentation](https://developer.wordpress.org/reference/functions/the_posts_navigation/)) to display navigation to next/previous set of posts, so it should work with any content type, including products. 

Are you using _s as is, or a theme based on _s? If you're using a theme based on _s there might be a number of differences causing your issue. The problem might also be with plugins you're using, so I'd recommend disabling all of them (besides WooCommerce) to see if that helps.

**Comment by grappler** [comment]
@bubbledesign Were you able to solve it?

**Comment by crunnells** [comment]
Closing this issue since we haven't heard back from the reporter in a few months.
