### ISSUE TITLE
How do I remove the cost (£1.89) and item text in mini cart Woocommerce?

### ISSUE THREAD

**Issue by bubbledesign** [Automattic/_s#1319]
How do I remove the cost (£1.89) and item text in mini cart Woocommerce?  I only want to leave number of items with basket icon.

![screen shot 2018-09-19 at 10 38 08](https://user-images.githubusercontent.com/43243739/45746837-1566a000-bbfc-11e8-90b9-62f51bf7824e.png)

      if ( ! function_exists( 'agricola_woocommerce_cart_link_fragment' ) ) {
	/**
	 * Cart Fragments.
	 *
	 * Ensure cart contents update when products are added to the cart via AJAX.
	 *
	 * @param array $fragments Fragments to refresh via AJAX.
	 * @return array Fragments to refresh via AJAX.
	 */
	function agricola_woocommerce_cart_link_fragment( $fragments ) {
		ob_start();
		agricola_woocommerce_cart_link();
		$fragments['a.cart-contents'] = ob_get_clean();

		return $fragments;
	}
    }
    add_filter( 'woocommerce_add_to_cart_fragments', 'agricola_woocommerce_cart_link_fragment' );

    if ( ! function_exists( 'agricola_woocommerce_cart_link' ) ) {
	/**
	 * Cart Link.
	 *
	 * Displayed a link to the cart including the number of items present and the cart total.
	 *
	 * @return void
	 */
	function agricola_woocommerce_cart_link() {
		?>
		<a class="cart-contents" href="<?php echo esc_url( wc_get_cart_url() ); ?>" title="<?php esc_attr_e( 'View your shopping cart', 'agricola' ); ?>">
			<?php
			$item_count_text = sprintf(
				/* translators: number of items in the mini cart. */
				_n( '%d item', '%d items', WC()->cart->get_cart_contents_count(), 'agricola' ),
				WC()->cart->get_cart_contents_count()
			);
			?>
			<span class="amount"><?php echo wp_kses_data( WC()->cart->get_cart_subtotal() ); ?></span> <span class="count"><?php echo esc_html( $item_count_text ); ?></span>
		</a>
		<?php
	}
    }

    if ( ! function_exists( 'agricola_woocommerce_header_cart' ) ) {
	/**
	 * Display Header Cart.
	 *
	 * @return void
	 */
	function agricola_woocommerce_header_cart() {
		if ( is_cart() ) {
			$class = 'current-menu-item';
		} else {
			$class = '';
		}
		?>
		<ul id="site-header-cart" class="site-header-cart">
			<li class="<?php echo esc_attr( $class ); ?>">
				<?php agricola_woocommerce_cart_link(); ?>
			</li>
			<li>
				<?php
				$instance = array(
					'title' => '',
				);

				the_widget( 'WC_Widget_Cart', $instance );
				?>
			</li>
		</ul>
		<?php
	}
    }

Then I paste it in header.php

```
<?php
	if ( function_exists( 'agricola_woocommerce_header_cart' ) ) {
		agricola_woocommerce_header_cart();
	}
?>
```

**Comment by slushman** [comment]
This repo is intended for fixing issues with the _s starter theme. If you need help with WooCommerce, I'd recommend trying their support forums.
