### ISSUE TITLE
customize.js question 

### ISSUE THREAD

**Issue by Lootstep** [Automattic/_s#1321]
If I Change the  functions like for example  `wp.customize( 'header_textcolor', function( value ) {
		value.bind( function( to ) {`
To something like `	wp.customize( 'header_textcolor', function( dog ) {
		value.bind( function( cat ) {` too all the function names in **customize.js**
The code stops working. and I can't find a reason why.
Are "to" and "value" are core functions used by all themes and I should always use them, or is there another file/s  I need to edit too.
sorry new to php and JavaScript

**Comment by philiparthurmoore** [comment]
It shouldn't matter whether you use `value` and `to` as names as long as there is consistency. What's your full code snippet?
