### ISSUE TITLE
Using consistent font-sizing mixins

### ISSUE THREAD

**Issue by jaclyntan** [Automattic/_s#1322]
I'm using the woocommerce boilerplate _s provides( it is such a time saver, thank you so much to the people that made this), however I noticed this in the components scss under shop:

`font-size: ms(-1);`

This isn't used anywhere else in the css as far as I know, and from my quick google ms(x) is an addon to scss (never used it before personally). I feel like `font-size: ms(-1);` should be replaced with @include font-size(x) or font-size: 90% since ms(x) seems to be in contrast to the other font mixins used in the code.

**Comment by grappler** [comment]
hi @jacklenox I can't seem to find the reference to `font-size: ms(-1);` in the code. Could you link to the line number?

**Comment by jaclyntan** [comment]
Sorry, I must have gotten confused between some other woocommerce styles because I can't find that mixing anywhere in this repo either!

On the topic of consistency though, one thing that did confuse me with the woocommerce styles  in _s is that font sizing often changes between `font-size: 1em;` and `font-size: 1rem;`. Can this be resolved and made consistent with other _s styles?

**Comment by Ismail-elkorchi** [comment]
Hi @jaclyntan 👋 ! Thank you for the issue report. While the repo had stoped being updated for quite some time, it has some movement now. It would be nice if you could create a PR, I would be happy to review it and merge it.
