### ISSUE TITLE
Rationale + usability of navigation

### ISSUE THREAD

**Issue by shawnCaza** [Automattic/_s#1325]
I've just finished up my first _S wp theme. I've also borrowed the navigation menu for use in an non-wp project.

I think it's great for the most part.

I'm curious why it doesn't support rollover when the device allows for it? From my perspective the click to open + click to close functionality reduces usability when not using touch devices. Maybe I'm wrong?

As a result I modified the .js file in my projects to allow for rollover/out menu opening/closing while maintaining the tap functionality for touch devices and keyboard navigation. Is there any reason anyone wouldn't want their menu to be modified in this way?

**Comment by grappler** [comment]
Hi @shawnCaza 

I just tested the menu in `_s` and the submenu opens when I hover over the parent menu item. Did you experience something different?

> I'm curious why **it** doesn't support rollover when the device allows for it?

Sorry I was not sure what you meant with it, did you mean `_s` or the navigation menu that you used from a non-wp project?

**Comment by Ismail-elkorchi** [comment]
Closing this issue since we haven't heard back from the reporter. Feel free to re-open the issue if you have further information.
