### ISSUE TITLE
Permalinks not working in custom theme

### ISSUE THREAD

**Issue by COUDESCHAMPS** [Automattic/_s#1327]
Hi! 

I'm experiencing some issues with the permalinks, it doesn't matter wich link i click, all of them are redirecting to the same post, i've tried with different estructures within the loop but i always get the same result... It happens in my index.php, single.php, etc... I don't know if there is some issue with _s-master or i need to rewrite the loop, but i've tried with other themes and the permalinks worked correctly with that themes but they don't work under "underscores"... Anyone with similar problems that can give me a hand with this issue?

Thanks in advance.

**Comment by philiparthurmoore** [comment]
It's really hard to help out with this without seeing any code samples or live links. Do you have anything we could look at to see if you're dealing with an _s issue or something else?

**Comment by COUDESCHAMPS** [comment]
You're right.. I'm a newbie...

The live link to my custom _s-master theme is 

http://hdcmedia.es/wordpress/

thanks in advance

**Comment by grappler** [comment]
Generally we do not provide general support. The place for that would be https://wordpress.org/support/

I don't think there is a problem with `_s`. If you are having problems with the permalinks then it is good to try to flush them by opening the permalinks page in the admin.

Also make sure to disable all plugins to make sure it is not a plugin affecting the site.

I could find an issue when going through your site.

**Comment by crunnells** [comment]
Closing this as it's not a theme issue.
