### ISSUE TITLE
ERROR: Referenced sniff "PHPCompatibility.PHP.RemovedExtensions" does not exist

### ISSUE THREAD

**Issue by limestreet** [Automattic/_s#1331]
ERROR: Referenced sniff "PHPCompatibility.PHP.RemovedExtensions" does not exist
is caused by changes in https://github.com/PHPCompatibility/PHPCompatibility
**PHP.RemovedExtensions** is moved to **Extensions.RemovedExtensions**
To fix it we should modify following line:
https://github.com/Automattic/_s/blob/master/phpcs.xml.dist#L126

**Comment by jrfnl** [comment]
PR #1311 already takes care of this.

**Comment by limestreet** [comment]
Ohh... I see. Thanks! :)
