### ISSUE TITLE
Compatibility issue with WooCommerce Product Add-ons

### ISSUE THREAD

**Issue by FreshPhil** [Automattic/_s#1333]
1585014-zd-woothemes

**What's the problem?**

When using the underscores theme along with WooCommerce and WooCommerce Product Add-Ons, product names are replaced with `1x Undefined` text.

**How to replicate:**
Install WooCommerce v 3.5.0
Install WooCommerce Product Add-Ons v 3.0.4

- Create a product that has a product add-on
- Browse to product and observe product name

Now activate the underscores theme and check the product name again

![](http://cld.wthms.co/6yxwzB+)
Image Link: http://cld.wthms.co/6yxwzB

**Comment by owaisobjects** [comment]
I have the same issue

**Comment by owaisobjects** [comment]
For the time being, I found a solution to add a class "product_title" into product title element using jQuery on page load.
This works for me ;)

**Comment by owaisobjects** [comment]
add_action( 'wp_footer', 'product_addon_remove_undefined' );

function product_addon_remove_undefined() { ?>
	<script>
		jQuery(document).ready(function() {
			if(jQuery(".mk-product-details h1.title").length > 0){
			    jQuery(".mk-product-details h1.title").addClass("product_title");
			}
		});
	</script> <?php
}

paste this code in your theme's functions.php file and replace "mk-product-details" CSS class with your product title CSS class

**Comment by TassieNZ** [comment]
Hi owaisobjects,

How do I find the correct product title CSS class please? I've tried several things but so far without success!

Thanks.

**Comment by Bromovite** [comment]
@TassieNZ Did you manage to find the correct product title CSS class? If so, how did you find it??

**Comment by TassieNZ** [comment]
**@Bromovite** No, this is still a work in progress. Very frustration.

**Comment by Bromovite** [comment]
@TassieNZ I found mine with a little help. I used the Inspect tool on Google Chrome. I hovered over the title I wanted to insert then hit inspect (right click) then located my CSS class by looking at the div class of that item. Mine was .post-title

**Comment by TassieNZ** [comment]
**Bromovite** That is exactly what I did ... numerous times! Mine appears to be .entry-title unless I'm missing something. e.g. https://bruce-mclaren.com/product/joint-membership-nz/

You won't see the 1x Undefined error as it's set to not show unless logged in until I get it all fixed.

**Comment by Bromovite** [comment]
My code changed slightly to what was on this thread. Maybe it'll help you

add_action( 'wp_footer', 'product_addon_remove_undefined' );

function product_addon_remove_undefined() { ?>
<script>
jQuery(document).ready(function() {
if(jQuery(".post-title h1").length > 0){
jQuery(".post-title h1").addClass("product_title");
}
});
</script> <?php
}

**Comment by Bromovite** [comment]
``add_action( 'wp_footer', 'product_addon_remove_undefined' );

function product_addon_remove_undefined() { ?>
<script>
jQuery(document).ready(function() {
if(jQuery(".post-title h1").length > 0){
jQuery(".post-title h1").addClass("product_title");
}
});
</script> <?php
}

**Comment by Bromovite** [comment]
`add_action(` 'wp_footer', 'product_addon_remove_undefined' );

function product_addon_remove_undefined() { ?>
<script>
jQuery(document).ready(function() {
if(jQuery(".post-title h1").length > 0){
jQuery(".post-title h1").addClass("product_title");
}
});
</script> <?php
}``

**Comment by Bromovite** [comment]
`add_action( 'wp_footer', 'product_addon_remove_undefined' );

function product_addon_remove_undefined() { ?>
<script>
jQuery(document).ready(function() {
if(jQuery(".post-title h1").length > 0){
jQuery(".post-title h1").addClass("product_title");
}
});
</script> <?php
}`

**Comment by Bromovite** [comment]
`add_action( 'wp_footer', 'product_addon_remove_undefined' );

function product_addon_remove_undefined() { ?>
<script>
jQuery(document).ready(function() {
if(jQuery(".post-title h1").length > 0){
jQuery(".post-title h1").addClass("product_title");
}
});
</script> <?php
}`

**Comment by Bromovite** [comment]
This might get confusing as I can't paste the code properly. I don't use this often so not sure how. The code was the same except these two lines

**Comment by Bromovite** [comment]
if(jQuery(".post-title h1").length > 0){
jQuery(".post-title h1").addClass("product_title");

**Comment by TassieNZ** [comment]
**@Bromovite** Thanks, but unfortunately still not working.

**Comment by Bromovite** [comment]
shame. Well good luck anyway!

**Comment by jbrundige** [comment]
Thank you for this code! I want to confirm that it still works!!

**Comment by jbrundige** [comment]
the code I used in elementor: 
add_action( 'login_enqueue_scripts', 'my_login_logo' );

add_action( 'wp_footer', 'product_addon_remove_undefined' );

function product_addon_remove_undefined() { ?>

add_action( 'wp_footer', 'product_addon_remove_undefined' );

function product_addon_remove_undefined() { ?>
	<script>
		jQuery(document).ready(function() {
			if(jQuery(".elementor-heading-title").length > 0){
			    jQuery(".elementor-heading-title").addClass("product_title");
			}
		});
	</script> <?php
}

**Comment by jbrundige** [comment]
ignore the first line :)

**Comment by Ismail-elkorchi** [comment]
It seems that it's not an issue anymore. I just tried this using WordPress 5.4, WooCommerce 4.0.1 and WooCommerce Product Add-ons 3.0.30, and it's working fine for me.

<img width="561" alt="woocommerce-add-ons" src="https://user-images.githubusercontent.com/5872391/80129958-62081f00-8587-11ea-9857-13a0a8b70ec0.png">
