### ISSUE TITLE
:root footer - display: none !important;

### ISSUE THREAD

**Issue by Grimmwicht** [Automattic/_s#1337]
Hi folks,

I used your base theme to create a custom theme. All went well until recently I discovered that my footer is missing. It gets the following CSS style automatically:

`:root #ad_footer, :root .ad_footer {
	display: none !important;
}`

I can't figure out what's causing this. Even if I add `display: block !important;` to my CSS file, this is overridden by the CSS above, because the source for this is apparently Inline:1.

Does the theme add this dreadful CSS by some PHP magic? Or is this some Wordpress malignity? It would be really nice if someone could point me in the right direction.

**Comment by crunnells** [comment]
This is definitely not something that comes from Underscores or WordPress core; check your plugins and browser extensions :)

**Comment by Grimmwicht** [comment]
Splendid! Thanks for pointing me to the right direction. Yes, it was the Firefox-Addon Adblocker Ultimate which killed the poor footer. Cheers!
