### ISSUE TITLE
Noob question sorry

### ISSUE THREAD

**Issue by Glen-Dango** [Automattic/_s#1343]
" I'm a theme meant for hacking so don't use me as a Parent Theme"

what does that mean? do i create a child or can i just use the theme folder?  thx

**Comment by sterndata** [comment]
>> can i just use the theme folder <<

Exactly.

**Comment by Glen-Dango** [comment]
so it is a parent theme?

**Comment by Glen-Dango** [comment]
oh i see...you would normally say use a child theme to make changes but _s is an original folder so dont have to worry about having a child theme...  
So maybe i should have read it as:
" I'm a parent theme meant for hacking so don't use me as a Parent Theme and create a child"

**Comment by crunnells** [comment]
The primary goal is to take the code (and best practices) in this theme, and use it to build something new.
