### ISSUE TITLE
WooCommerce

### ISSUE THREAD

**Issue by mark60480** [Automattic/_s#1345]
I'm having issues with the WooCommerce gallery zoom and gallery lightbox not working. In order to troubleshoot, I installed a completely blank underscores theme with the WooCommerce boilerplate - and the problem still exists.
Underscores files - downloaded and installed today (1/25/19)
Wordpress version: 5.0.3
WooCommerce version: 3.5.4
PHP version: 7.1
Is anyone else having this problem or know what the cause might be?

BTW, if I remove the link to the boilerplate file from the functions.php, the gallery zoom and lightbox both work perfectly.

**Comment by WebAssembler** [comment]
Hi @mark60480 

I've tried to replicate your issue with the same versions you listed above and the only thing I found was the gallery zoom icon is visible but is positioned all the way over to the right of the page. I had to scroll all the way to the right to use it. 

I can see that the ```/inc/woocommerce.php``` file is being loaded which adds theme support for the gallery zoom, lightbox and slider as described in the [WooCommerce wiki](https://github.com/woocommerce/woocommerce/wiki/Enabling-product-gallery-features-(zoom,-swipe,-lightbox))

When you say the "WooCommerce boilerplate" do you mean the plugin. Have you tried it with the Product CSV sample? [https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv](https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv) 

> BTW, if I remove the link to the boilerplate file from the functions.php, the gallery zoom and lightbox both work perfectly.

Do you mean the ```/inc/woocommerce.php``` file?

**Comment by Ismail-elkorchi** [comment]
Hi @mark60480, @WebAssembler !

I was able to reproduce this issue with WooCommerce 4.0.1 and WordPress 5.4. The PR https://github.com/Automattic/_s/pull/1406 is a simple fix that makes gallery zoom and gallery lightbox both work.
