### ISSUE TITLE
Not Align Woocommerce Product Add-Ons text on chart & Checkout box

### ISSUE THREAD

**Issue by msurubel** [Automattic/_s#1353]
Hello i am Msu Rubel
When i ad adons on a product then when i fillup the adons for order and click chart this not adjust in the chart & Checkout box area.
Issue pic of Chart: https://snag.gy/Jc58Kb.jpg
Issue Pic of Checkout: https://snag.gy/NPlMmn.jpg

Please help me that how i solved it?
I want all text are adjust in chart & Checkout box.

**Comment by nielslange** [comment]
@msurubel Is sounds like this issue is related to the add-ons that you're using. Please deactivate them to double check if the issue is indeed caused by the add-ons. If so, then please contact the developer of the add-ons regarding fixing this issue.

**Comment by Ismail-elkorchi** [comment]
As @nielslange said, this is not an issue that is related to _s.
