### ISSUE TITLE
Missing Woocommerce Body Classes

### ISSUE THREAD

**Issue by pierrerocket** [Automattic/_s#1355]
Hello,

I have noticed when using stock underscores when on product category pages all the Woocommerce added body classes don't seem to be working.

I tested this with a brand new fresh wordpress install and a totally unmodified version of underscores generated and downloaded fresh from underscores.me, and used the store sample data as the only data in the shop.

Here is the body class Im getting with underscores:
`logged-in admin-bar woocommerce woocommerce-page woocommerce-js hfeed customize-support`

And this is the body class I am getting with 2019 theme:
`archive tax-product_cat term-hoodies term-17 logged-in admin-bar wp-embed-responsive woocommerce woocommerce-page woocommerce-js hfeed image-filters-enabled customize-support
`

Any ideas what is going on here?

**Comment by pierrerocket** [comment]
Duh, problem was I had to add theme support for woocommerce.  I thought this was already setup in underscores, and I didnt see the theme warning you used to get.  Sorry!

**Comment by nielslange** [comment]
Issue solved as mentioned in https://github.com/Automattic/_s/issues/1355#issuecomment-484997235
