### ISSUE TITLE
LI "focus" class is not removed on ontouchstart

### ISSUE THREAD

**Issue by tomanatura** [Automattic/_s#1356]
Hello, 
"focus" class is added to LI element if I touch it, but if I touch it again (to close sub menu) 'focus' class is not removed. 
Is it intentional function, or bug?
If it is not bug, can anyone help me to fix that?
Thanks you

**Comment by Ismail-elkorchi** [comment]
Hi @tomanatura ! I just tested a new version of `_s` and I can't replicate the problem that you describe. What are the steps to follow to reproduce this behavior
?

**Comment by tomanatura** [comment]
Hi @Ismail-elkorchi 
Thanks you for your reply. I've try that too now (with new _s) and it is still working same.
Steps: 
1) Add menu with submenu item
2) Click on li.menu-item-has-children = 'focus' class is added
3) Click again on li.menu-item-has-children (to close it) =  'focus' class is **not** removed. 'Focus' class is removed only after you click outside of menu, that can be OK for some of usage but it is not completely OK solution - from my perspective. 
But maybe... am I doing something wrong?
Thanks you

**Comment by Ismail-elkorchi** [comment]
Ahh ! Now I see what you mean. In fact, this behavior is correct. We don't want to remove the `focus` class since we have to keep the focus on the last touched menu item regardless of its state.

Thanks @tomanatura for the update.
