### ISSUE TITLE
Add call to wp_body_open

### ISSUE THREAD

**Issue by spacedmonkey** [Automattic/_s#1357]
The function `wp_body_open` was added in WordPress 5.2. This theme should call it in header.php and include a backward compatilibity slim for old versions of WordPress.

**Comment by spacedmonkey** [comment]
Related #1350

**Comment by kafleg** [comment]
<?php //wp_body_open hook from WordPress 5.2
if ( function_exists( 'wp_body_open' ) ) {
    wp_body_open();
} ?>

**Comment by Ismail-elkorchi** [comment]
Closing as it is fixed in #1350.
