### ISSUE TITLE
Is underscores theme update

### ISSUE THREAD

**Issue by bubbledesign** [Automattic/_s#1363]
Hi guys,

I want to know is underscores theme update because WordPress version now is 5+

Is underscores theme still recoding in github or no longer use it?

Thanks,

Shaun.

**Comment by denis-adobe** [comment]
i can verify that _s works without a problem on wordpress 5+

**Comment by philiparthurmoore** [comment]
@bubbledesign It still works but development on it is basically at 0 right now. Super-slow, if at all. It works though.
