### ISSUE TITLE
Sliders (any slider AFAIK) problem in _S

### ISSUE THREAD

**Issue by MarcinSzafran** [Automattic/_s#1364]
Hi,
I'm afraid there is a problem with sliders in _S.
I'm trying to use Slide Anything (and tried few others sliders).
Slider is doing some strange things with page, does not fit in page, resizes page and so on (horizontal scrollbar appears, page can get thousands of pixels of length with some sliders' configs etc.).
I've added jQuery3 to the theme ff course, should I do something more?

**Comment by MarcinSzafran** [comment]
Simple example (see attachment):
Slider in clean _S, slider starts below header ("Zobacz, co mówią...") and just below name ("Jolanta, ...") naviagtion dots should be seen - but the are few hundreds pixels lower, and slider is too wide (in this case - just a little), and you can see vertical scrollbar

![slider_problem](https://user-images.githubusercontent.com/25611974/60833446-8c3a4d00-a1be-11e9-9333-6abbbb3f5791.jpg)

**Comment by denis-adobe** [comment]
i think you have not positioned the slide elements with `position: absolute`?
and did you follow their faq https://edgewebpages.com/faqs/

**Comment by MarcinSzafran** [comment]
> i think you have not positioned the slide elements with `position: absolute`?
???
Why should I do it?
I just installed the plugin and launched the test slider (slide elements are positioned by plugin and it works right with other themes - test it with any twenty something WP theme for example)

> and did you follow their faq https://edgewebpages.com/faqs/
Well, as I noticed, there is no useful information about the reported problem.
I used this plugin with other themes in other projects without problems.
And reminder: I tested other sliders with _S also and there were problems also.

OK, I have some time now, so I'll try to check this problem even more intensively, maybe I will find something. Report in a few days

**Comment by crunnells** [comment]
Underscores is meant for hacking, and might not support things like sliders out of the box. The purpose of this theme is to be a foundation that you use to build your own theme on top of.

**Comment by philiparthurmoore** [comment]
Out of scope for this project. Not an issue that is related to _s.

**Comment by MarcinSzafran** [comment]
OK, long story short... Not reopen ;-)
I was very busy despite the previous declaration, sorry.
Slide Anything and few other sliders are working right until Twenty Seventeen theme, in the next (and _S) they are cut or have their dimensions changed in a different way.
So it looks like the problem is caused by some changes in newest themes and sliders developers should correct their code
