### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in …/wp-includes/post-template.php on line 310

### ISSUE THREAD

**Issue by tomektomczuk** [Automattic/_s#1371]
To fix that you have to: 

downgrade PHP version to 7.1 or edit wp-config.php and replace

define('WP_DEBUG', false);

to

ini_set('display_errors','Off');
ini_set('error_reporting', E_ALL );
define('WP_DEBUG', false);
define('WP_DEBUG_DISPLAY', false);

**Comment by jbotte** [comment]
is there a fix for this yet?

**Comment by Ismail-elkorchi** [comment]
@tomektomczuk I just tried `_s` on a fresh install of WordPress with PHP 7.4 and I cannot reproduce the issue you are reporting.

Closing for now. Feel free to reopen the issue if you have additional information.
