### ISSUE TITLE
Duplicate layout CSS

### ISSUE THREAD

**Issue by Sigri44** [Automattic/_s#1373]
Hi,

I have use your website to generate a basic theme.
And i noticed that there is duplicate layout CSS files, into /theme/layouts/ :
- content-sidebar.css
- sidebar-content.css

With the same content. I think it's a bug using.

![1](https://user-images.githubusercontent.com/9304947/64787172-735c6800-d570-11e9-90a6-0ed077705335.png)
![2](https://user-images.githubusercontent.com/9304947/64787177-75262b80-d570-11e9-9e72-d8682d047be2.png)

Sigri44

**Comment by zimnyd** [comment]
No, there are not the same. Look on the float and margin on. One is for sidebar from left side of content, one is for sidebar from right side of content.

**Comment by Sigri44** [comment]
And why don't use one css file "sidebar", or simply rename it "right-sidebar" and "left-sidebar".. ?!

**Comment by crunnells** [comment]
Underscores is meant for hacking, rather than using as-is. There are two CSS files provided so that you can choose the one you want to use, and delete the other one. Or, use both, as you mentioned. Think of Underscores as a foundation that you use to build your own theme on top of.
