### ISSUE TITLE
Can we align `.alignleft` and `.alignright` to be full-width in mobile devices?

### ISSUE THREAD

**Issue by mayeenulislam** [Automattic/_s#1376]
The idea is behind a common pattern that, in mobile devices float images often make the text to be unreadable or difficult to read. So, in mobile devices (viewport lesser than `37.5em`) we can make the images full-width to make the text distributed in a nicer way.

## Current
At present the content breaks because of float on mobile devices if the image is small.<br>
![floatright](https://user-images.githubusercontent.com/4551598/67758542-122d1d00-fa68-11e9-85a9-e6da2976feac.png)

## Expected
Expecting a good-read text top or bottom of the image while in smaller viewport.<br>
![floatnone](https://user-images.githubusercontent.com/4551598/67758625-40126180-fa68-11e9-915c-8ed286c512e3.png)

Actually we did similar in our development. So we thought it'd be nice to have that in core `_s`.

**Comment by philiparthurmoore** [comment]
Sometimes images aren't big, though. How do you cover those cases?

**Comment by philiparthurmoore** [comment]
Closing this - there is an assumption in this issue that all images on mobile will be large enough to fit mobile viewports. That's not true. 

I suggest you work on mobile image size handling rather than how they are aligned in mobile views.
