### ISSUE TITLE
spaces above and below the footer

### ISSUE THREAD

**Issue by Prunello** [Automattic/_s#1380]
Hi, I'm wondering why the footer has these spaces above and below only on the homepage, unlike the other pages (as you can see in the pics). I mean, as usual I don't see the spaces in the other pages, but I see them in the home page and I don't like it. How can I fix this only regarding the home page?
![11](https://user-images.githubusercontent.com/57717521/68772283-d67a8180-0629-11ea-950c-953449444045.PNG)
![21](https://user-images.githubusercontent.com/57717521/68772285-d7131800-0629-11ea-8da5-234037867539.PNG)

**Comment by designarti** [comment]
**I don't want to be rude but this isn't an issue to post here.** 
1. That is a front-end issue, 0% chances to be an Underscores flaw
2. Without a live site there's no way someone could tell

**Comment by Prunello** [comment]
I've recently passed to _s theme, with the precedently theme, or other themes i've tried, this issue doesn't appears. My theme builder's support tells this isn't a their issue, and to ask assistance to my theme (_s) support

**Comment by sterndata** [comment]
post a question in the wordpress.org forums and I'll take a look if you include the URL of your site.

**Comment by crunnells** [comment]
As @designarti said, this isn't an _problem_ with Underscores itself. The wordpress.org forums are a much better avenue for general theme and CSS support.
