### ISSUE TITLE
back browser button not working

### ISSUE THREAD

**Issue by aseo13** [Automattic/_s#1381]
When I go to a page and click browser's back button - the page jumps to bottom of the screen. 
ie. go here... https://firepitoutfitter.com/product/46%e2%80%b3-square-custom-stone-gas-fire-pit/ - click on a couple images and then try and use your browser's back button.

**Comment by bej-soan** [comment]
I just tried and cannot reproduce this

**Comment by crunnells** [comment]
Same, I cannot reproduce this, and it's more likely this is a browser issue.
