### ISSUE TITLE
Removing Built and Test files?

### ISSUE THREAD

**Issue by HannesDev** [Automattic/_s#1392]
Thanks @Ismail-elkorchi for breathing life back into the project!

I'm not sure about the built and test files like package.json, travis, et cetera.
For me underscores is perfect, because it has much less clutter than other starter themes, so I'd have to delete them first and use my files.

What do you think?

**Comment by Ismail-elkorchi** [comment]
Hello @HannesDev and thank you for the feedback.

Introducing build tools to `_s` was discussed heavily in https://github.com/Automattic/_s/issues/1149.
 
In short, these tools allow to automate some of the pain points of maintaining this project, like compiling SCSS files to CSS and forcing the project files to follow the WordPress coding standards.

I'm pretty sure issues likes https://github.com/Automattic/_s/issues/615, https://github.com/Automattic/_s/pull/1382, https://github.com/Automattic/_s/pull/932, https://github.com/Automattic/_s/pull/1168 and many others were the result of lacking these tools.

**Comment by HannesDev** [comment]
Thanks for the answer.
So, you include built tools but also stripped down to it's essentials. Do I get that right?

**Comment by Ismail-elkorchi** [comment]
> So, you include built tools but also stripped down to it's essentials. Do I get that right?

Yes, that was the idea. To include a simple workflow for automating some basic tasks while keeping the barrier to entry as low as possible.

**Comment by HannesDev** [comment]
Got it, thanks.
