### ISSUE TITLE
all woocommerce pages blank

### ISSUE THREAD

**Issue by peteratomic** [Automattic/_s#1402]
Not sure what's wrong with this. Had been running a custom theme based on _s for a while, then the client asked for woocommerce support. Downloaded a new version from the underscores site, uploaded the updated functions and inc/woocommerce files and... nothing. All shop pages blank.

**Comment by peteratomic** [comment]
Woops. Unrelated issue. No support needed.

**Comment by Ismail-elkorchi** [comment]
Hi @peteratomic ! Thanks for following up.
