### ISSUE TITLE
woocommerce customizations

### ISSUE THREAD

**Issue by peteratomic** [Automattic/_s#1403]
I generated a new underscores theme and looking at the inc/woocommerce.php file, there's a clear implication that it should be customizing the shop based on this theme. Specifically the comment:

> Wraps all WooCommerce content in wrappers which match the theme markup.

And yet, when adding a class to the "primary" div, nothing happens. Doesn't seem as if woocommerce is using this include at all. And when I try to add woocommerce templates (from the main wc plugin folder) those customizations are also not appearing.

Find it very odd that underscores doesn't seem to support woocommerce.

**Comment by Ismail-elkorchi** [comment]
Hi @peteratomic 👋 ! Thanks for the report.

> And yet, when adding a class to the "primary" div, nothing happens.

Can you please explain what do you mean by adding a class to the "primary" div ? What you were expecting to happen ?

I've just set up locally a WordPress site with WooCommerce and a newly generated `_s`. Looking at the code, I found indeed the wrappers added by [the function that you have mentioned](https://github.com/Automattic/_s/blob/master/inc/woocommerce.php#L111-L126) as you can see in the screenshot below :

<img width="777" alt="underscores-woocommerce" src="https://user-images.githubusercontent.com/5872391/79248762-2cbb4d00-7e74-11ea-8c4b-20766e2ae16d.png">

> And when I try to add woocommerce templates (from the main wc plugin folder) those customizations are also not appearing.

I can't reproduce either. I created a folder with the name woocommerce, and I copied into it `single-product.php` from `woocommerce/templates`. and any changes to this file override without any problem the original one from the WooCommerce plugin.

Can you reproduce this issue with a fresh install of WordPress with only _s and WooCommerce ?

**Comment by peteratomic** [comment]
Apologies for an unnecessary post. User error.

I had been following a tutorial on the Woocommerce site and when nothing in it worked, I then started with a fresh _s download (with the WC functions) and got it partially working, but couldn't figure out why my edits in the WC inc file weren't showing up. Later discovered it was because I had forgotten to delete a specific file from my earlier tests.
