### ISSUE TITLE
Is there any documentation on how to use the bundler for this theme?

### ISSUE THREAD

**Issue by sjoerdvermeijden** [Automattic/_s#1420]
The title basically explains things ;)

**Comment by Ismail-elkorchi** [comment]
There is an open PR which does exactly that, but it is not yet finished : https://github.com/Automattic/_s/pull/1419.

First you have to install [Node.js](https://nodejs.org/), then in the command line run :

```sh
$ cd _s
$ npm install
$ npm run bundle
```

**Comment by Ismail-elkorchi** [comment]
I hope that the comment above helped. Closing for now. Feel free to reopen the issue if you have any additional questions.
