### ISSUE TITLE
Need help updating from 3.2.0 to 4.1.0

### ISSUE THREAD

**Issue by Elyssa444** [Automattic/_s#1452]
Hi, I'm new to this and recently took over managing a site created with  _s.  I have some experience with WordPress, updating themes and plugins, but not with custom themes. I just downloaded the code, but I'm not sure what is involved in updating the current site. Please help!

**Comment by scrobbleme** [comment]
I think _s is not meant to be used that way... As there are probably to many changes in your theme you won't be able to "update".

Maybe:

1. Just update your old code to follow current theme guidelines
2. Use some diff tool and try to merge the latest version into your old one (i.e. PhpStorm)
3. Start from scratch with the latest version and try to incorporate necessary changes from your old theme

**Comment by Elyssa444** [comment]
Yes, I just learned that. There was something left in the code that triggered an out of date warning in the status report.  I'm sure it's one of the plugins causing the problem. Thanks for your help!
