### ISSUE TITLE
Download from underscores.me is missing sass folder.

### ISSUE THREAD

**Issue by raphaelparent** [Automattic/_s#1461]
Hi all, I've just generated _s theme from http://underscores.me and it is missing the sass folder. I've looked up in the issues but I haven't found anything related to it so I thought it needed to be mentioned somewhere.

It's making me wonder if the generating function delivers the latest version of the repository.

Not a big issue for me as I will / am able to download the repo and do all the changes manually.

**Comment by MihaiSlujitoru** [comment]
Under the input for theme name, there is a small link called "Advanced Options". If you click on that there is an option to add sass.

**Comment by raphaelparent** [comment]
Oh well lol, thanks for the reply!
