### ISSUE TITLE
_S_VERSION constant must be rename with the theme name 

### ISSUE THREAD

**Issue by kishanjasani** [Automattic/_s#1462]
In [underscore](https://underscores.me/) site. `_S_VERSION` constant must be rename with the theme name of users.

- Like the theme is `AQUA` then the constant should be `AQUA_VERSION`.

**Comment by BrookeDot** [comment]
I'm not sure I understand completely, can you clarify what the request here is? The [theme name is `_s`](https://github.com/Automattic/_s/blob/master/style.css) which is why the constant is `_S_VERSION`.

**Comment by BrookeDot** [comment]
Ah, are you talking about the script that bundles the theme? If so, the site has its own repo here:
https://github.com/Automattic/underscores.me

**Comment by kishanjasani** [comment]
Thanks, @BrookeDot 
Yes Exactly, I am talking about the script that bundles the theme

**Comment by BrookeDot** [comment]
@kishanjasani I'm going to close this out since the script that bundles the theme is within the other repo as a plugin. Do you mind opening up the issue there?
https://github.com/Automattic/underscores.me/blob/master/plugins/underscoresme-generator/underscoresme-generator.php
