### ISSUE TITLE
Issue when running lint npm commands

### ISSUE THREAD

**Issue by celsomtrindade** [Automattic/_s#1467]
After installing a blank new wordpress environment and installing this theme, I tried running the following commands:

```
npm run lint:js
npm run lint:scss
```
This was giving me errors like:
> Error: No files matching the pattern "'./sass/**/*.scss'" were found.

By removing the single quote on the command line, it worked.

```
// This
"lint:scss": "wp-scripts lint-style './sass/**/*.scss'"` 

// Becomes this
"lint:scss": "wp-scripts lint-style ./sass/**/*.scss"
```
Also, the package @wordpress/scripts can be updated.

Is it something within my specs or it's correct to remove the quotes?

--

Also, since we are in the `package.json` file, isn't it better to generate the `.zip` file within this theme folder instead of returning one folder and putting it on the `wp-content/themes` folder?

```
// This
"bundle": "dir-archiver --src . --dest ../_s.zip [...]"

// Becomes this
"bundle": "dir-archiver --src . --dest ./_s.zip [...]"
```

**Comment by salsasanna** [comment]
I had the same issue but with npm run compile:css, this fixed it, a big thank you!

**Comment by Ismail-elkorchi** [comment]
Hi, @celsomtrindade, @salsasanna  ! I have just updated the npm packages (https://github.com/Automattic/_s/pull/1516), which seems to resolve the issues reported here.
