### ISSUE TITLE
Underscores - still good to use in WP5?

### ISSUE THREAD

**Issue by toby1kenobi** [Automattic/_s#1470]
Have used underscores a bit in WordPress up to 4.9, wondering (from comments) here if it's still good to use, specifically in WP5? Sorry, I know this maybe isn't an issue in the full sense, I don't know how else to ask though.

**Comment by scruffian** [comment]
Underscores is no longer maintained, so if you're looking for a good parent theme to use in WP5, I'd try Seedlet: https://github.com/Automattic/themes/tree/trunk/seedlet

**Comment by ianstewart** [comment]
Oh — just wanted to note that [PRs still do get merged in here](https://github.com/Automattic/_s/pulls?q=is%3Apr+is%3Aclosed) from time to time.

I'd also take a look at this Gutenberg Block-based Theme starter too …

https://github.com/WordPress/theme-experiments/tree/master/gutenberg-starter-theme-blocks

Never too soon to start experimenting with block-based themes.
