### ISSUE TITLE
no SCSS?

### ISSUE THREAD

**Issue by welbinator** [Automattic/_s#1473]
Why doesn't the theme include a scss folder anymore? Not a huge deal I can make my own it's just weird, the documentation mentions stuff you can do with scss but doesn't actually include scss in the theme files.

**Comment by welbinator** [comment]
nevermind I'm an idiot.

**Comment by Ismail-elkorchi** [comment]
You are not an idiot @welbinator ! It happens to the best of us 😃 ! Thank you for the issue report.

**Comment by N30** [comment]
Would have been great if you actually answered your own question for the rest of us idiots with the same question, lol

**Comment by welbinator** [comment]
This is super old so I don't remember what the deal was but I'm thinking I forgot to choose scss when downloading the theme

**Comment by welbinator** [comment]
![Screenshot_20221010-171955](https://user-images.githubusercontent.com/7120386/194960854-0926bc9a-ff25-4f3e-b3e1-f775f8eb5e70.png)
