### ISSUE TITLE
please add tailwind inside saas

### ISSUE THREAD

**Issue by vahidalvandi** [Automattic/_s#1531]
resently same team created new stater kit with name tailpress . is good idea for use new framework like tailwind

**Comment by adrianvalenz** [comment]
They won't do that. But if you are interested in something like that @gregsullivan has a really great theme based off this with JavaScript support too. Really forward thinking. https://underscoretw.com/  and https://github.com/gregsullivan/_tw 

I'm sure you'll love it.

**Comment by 8704dev** [comment]
Dear team 
Then Check some new update Cher
