### ISSUE TITLE
Is this theme dead, Can I still use it as starter template?

### ISSUE THREAD

**Issue by manish2525** [Automattic/_s#1547]
The last commit is on Jan 2, 2022 in this repo. Is it the end for this theme? I am a new WordPress developer looking to use it as starter theme but it's updated a long time ago. Can I still use it as starter template?

**Comment by hanneslsm** [comment]
_s is a starter theme for classic Themes. The future are block themes. For that, you might want to look into the official [Create Block Theme Plugin](https://wordpress.org/plugins/create-block-theme/) which creates you a starter theme for you.
Additionally, a great resource for more information on block themes is [the official developer blog](https://developer.wordpress.org/news/)

However, if you want to create classic themes you still can use _s. Some npm packages might be outdated, but theoretically you could update them.
