### ISSUE TITLE
menu toggle on click - underscores.me

### ISSUE THREAD

**Issue by saxisme** [Automattic/_s#273]
Hi everybody,

First time posting an issue, so forgive me in advance for "anything" wrong.

Ok, so i followed issue #262 and #261 and everything looks fine in _s.
I downloaded the theme from underscores.me but there is a problem with the class of <pre><code>nav#site-navigation</code></pre> as the class is:

<pre><code>main-navigation
</code></pre>

While in the css and in the _s version is

<pre><code>navigation-main
</code></pre>

This prevents the toggle to work properly.

Thanks

**Comment by PittsburghChris** [comment]
This happens to me when, from a clean install of _underscores, I check  the Primary Menu box next to "Theme Locations" in the WordPress Appearance --> Menus administrative section. If I check the box, the responsive menu will not toggle "open". If I uncheck the box, the responsive menu will toggle open.
