### ISSUE TITLE
Top menu to work on click instead of on hover?

### ISSUE THREAD

**Issue by vejin** [Automattic/_s#364]
Hey guys,

is there an easy way to change a theme to make top menu work on click instead of on hover? So that actually submenu opens when you click on top level link, not when you hover it. It's usually needed functionality to create multilevel mobile menu, so I was wondering is this something I can easily change in a theme. Of course in that case the 1st level link would have to be dead link, and that's ok.
I can see that on smaller width screen "Menu" button appears which works on click, but main navigation still works on hover.

Cheers.

**Comment by cbananal** [comment]
Hi, were you able to work this around?
