### ISSUE TITLE
Submenus not working/showing in _s responsive menu

### ISSUE THREAD

**Issue by kat2014** [Automattic/_s#384]
Hello,

I'm using the _s theme, and noticed that the submenu items are not showing on the built-in responsive menu.

I haven't been able to find any threads noting similar issues online, but thought I'd check to see if this was a common issue, or one that was known and/or hopefully easily resolved.

My html looks like this:

```
<nav id="site-navigation" class="main-navigation" role="navigation">
<h1 class="menu-toggle"><?php _e( 'Menu', 'mytheme_s' ); ?></h1>
<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'mytheme_s' ); ?></a>
<?php wp_nav_menu( array( 'theme_location' => 'primary' ) ); ?>
</nav><!-- #site-navigation -->
```

i'm not 100% sure whether i've changed anything in my css to affect this, but was wondering if there was something obvious i ought to consider when using submenus with the built-in responsive menu?

Thanks in advance of any thoughts and advice.

PS) I am also curious what this line of code does/means:

```
<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'shanti_s' ); ?></a>
```

**Comment by webprom** [comment]
Better mobile submenus handling required, takes a lot of time to make it.
