### ISSUE TITLE
[suggestion] Twig fork of underscores anyone?

### ISSUE THREAD

**Issue by alexej-d** [Automattic/_s#455]
Hey guys,

first of all: Great work!
I was just asking myself if anyone has some time to 'port' the theme to twig templates using ['Timber'](https://github.com/jarednova/timber) for separation of views and logic.
I would do this myself, but my schedule would just crush me…
Maybe I am not the only one who would be interested in cleaner and more object-oriented code like this:

```
{% extends "base.twig" %}
{% block content %}
<h1 class="big-title">{{foo}}</h1>
<h2>{{post.title}}</h2>
<img src="{{post.thumbnail.src}}" />
<div class="body">
    {{post.content}}
</div>
{% endblock %}
```

**Comment by chrisjimallen** [comment]
Been thinking about taking this on, if I decide to do it I'll post the repo here.
