### ISSUE TITLE
Bug: skip-link-focus-fix.js causes unexpected outline on elements in Chrome

### ISSUE THREAD

**Issue by SimonEast** [Automattic/_s#543]
**skip-link-focus-fix.js** is supposed to correct the tab order for keyboard navigation to increase usability.  One unintended side-effect, however is that once the script adds `tabindex="-1"` to elements on `hashchange`, that DIV can now receive focus PLUS it also receives Chrome's `:focus` styling which is a blue outline.  After the hash-change event, you can simply click on the DIV and an outline appears in blue.  That's not too pretty.

**Steps to recreate issue in Chrome:**

1. Load a URL that contains skip-link-focus-fix.js
2. Pick a DIV on the page that has an ID
3. Append `#id-goes-here` to the URL
4. That element now has a blue border, and anytime you click on that element the blue border returns.

**Workaround**
You can apply some CSS overrides such as:
```
:focus {
    outline: none;
}
```
or
```
#myElement:focus {
    outline: none;
}
```

**Comment by davidakennedy** [comment]
Doubling back to this since it's got a bit stale.

Let's get this in. @jefferyto makes a solid argument, and even though the "skip link bug" is getting fixed in browsers, it will likely be awhile before it lands in Safari and Chrome.

@jefferyto Can you clean up your patch, sync with master and make an official pull request.

Also, in running the possible solution through JS Hint, I get two warnings we may need to address:

```bash
14	Use '!==' to compare with 'null'.
26	Use '===' to compare with '0'.
```

Thanks!

**Comment by davidyezsetz** [comment]
@davidakennedy I've wrapped this up in https://github.com/Automattic/_s/pull/755

**Comment by karmatosed** [comment]
@davidakennedy any ideas on this as I see you are active around it.

**Comment by davidakennedy** [comment]
@karmatosed The latest is here:

https://github.com/Automattic/_s/pull/814

Lots of feedback and thoughts, trying to move forward with it.

**Comment by lachlancanard739** [comment]
> hi [@davidakennedy](https://github.com/davidakennedy) if you do the same test changing the URL adding #post-1 you wiil see the outline on the article element. That's because CSS reset takes care of the outline only for a subset of elements, including DIVs (and #comments is a div) while #post-1 is an article. Teorically, this would happen for all the elements not included in the outline CSS reset like for example: article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, meter, nav, output, ruby, rb, rt, rp, section, summary... etc.
> 
> Please also notice the tabindex="-1" is only added once, only when you change the URL. If you refresh the page, the URL is not changed so there will be no tabindex="-1" and your test will fail.





https://preprocessor.space/questions/looking-to-customize-the-display-format-of-your-wordpress-archive
