### ISSUE TITLE
Child menu items inherit from parent in navigation menu

### ISSUE THREAD

**Issue by kiasta** [Automattic/_s#587]
One thing I noticed when adding a menu is the child items inherit from the parent when you click on them in the menu bar. It can be quite annoying when styling the menu so here is a suggestion to implement in your code. You have this as default:

.main-navigation .current_page_item a,
.main-navigation .current-menu-item a {
}

Now to fix this issue, is simple:

.main-navigation .current_page_item > a,
.main-navigation .current-menu-item > a {
}

I'm not sure if this was intentional or not, but it fixes the problem of inheritance.

**Comment by ururk** [comment]
I'm wondering if this should also handle current-page-ancestor (https://core.trac.wordpress.org/ticket/14701)? Or is the intent to only handle arbitrary menu assignments?

**Comment by gatespace** [comment]
@ururk
Related #706.
But The PR not merged yet.
