### ISSUE TITLE
Validation Errors & Warnings

### ISSUE THREAD

**Issue by emiluzelac** [Automattic/_s#654]
Hey folks,

Before we close this in right away, please give me a moment or two to explain.

At least once a month someone will bring the ```h1``` problem to the table, but only for SEO reasons right? OK, now let's forget the SEO for a sec.

Few moments ago I was trying to validate an ```_s``` based theme I am working on and validator throws the following messages.

## Warnings

*Consider using the h1 element as a top-level heading only (all h1 elements are treated as top-level headings by many screen readers and other tools).*

This would be accessibility if I am not mistaking and our accessibility gurus can confirm.

```<h1 class="screen-reader-text">Posts navigation</h1>```

Second and very similar:

*Consider using the h1 element as a top-level heading only (all h1 elements are treated as top-level headings by many screen readers and other tools).*

```<h1 class="entry-title"><a href="#" rel="b…```

## Errors

We introduced this while ago:

*The aria-controls attribute must point to an element in the same document.*

```…on class="menu-toggle" aria-controls="menu" aria-expanded="false">Primary Menu</button>```

----

```h1``` is a no brainer, switching them to i.e. ```h2``` will eliminate the warnings, but I have no idea how to get around the aria-controls.

At the same time HTML5 does recommend that we don't follow current aproach, see: http://www.w3.org/TR/2014/WD-html5-20140617/sections.html#headings-and-sections

From what I can see, we did not discuss this particular issue, searched for it, but no luck. If we did and you think that I am being too OCD, feel free to close the ticket :)

**Comment by davidakennedy** [comment]
Hey @emiluzelac, we have an open pull request for a [new heading structure](https://github.com/Automattic/_s/pull/651). We'll see what happens there.

I'll check into the warning on the `aria-control`.

**Comment by emiluzelac** [comment]
Great, feel free to handle the ticket status any way you find appropriate :)

**Comment by jaspermdegroot** [comment]
@davidakennedy - My PR https://github.com/Automattic/_s/pull/657 will fix the ```aria-control``` issue.

**Comment by karmatosed** [comment]
I think I am right with the new PR merged this should be closed. Please reopen if I am wrong though.
