### ISSUE TITLE
Automatically Load Parent Styles In _s Children

### ISSUE THREAD

**Issue by philiparthurmoore** [Automattic/_s#658]
This is a continuation of the discussion in #638. Because there is no way to re-open a PR once it's been closed, I'm opening this issue. Please read #638 and if there's any additional input, add it to that thread. This will be closed once there has been suitable consensus reached around #638.

**Comment by ianstewart** [comment]
Since you opened this issue on my birthday I feel obligated to comment here and say I'm not really a fan of it because it starts to introduce non-markup-specific "fixes" for WordPress development in the theme. Like "fixing" something that already has a standard practice by making a new _s-specific practice.

**Comment by obenland** [comment]
> Like "fixing" something that already has a standard practice by making a new _s-specific practice.

Maybe that practice is outdated and this is a better way to do it?

**Comment by ianstewart** [comment]
Is doing it in _s the best way to change that practice? Introducing a group of themes that do it one way, and a group of themes that do it another way?

**Comment by grappler** [comment]
Thank you @ianstewart for reviving the discussion.
> Like "fixing" something that already has a standard practice by making a new _s-specific practice.
Why do you see it as a "fix" and _s-specific practice. I don't see this as a "fix" but a change in standard practice and not a _s-specific but a general one.

> Is doing it in _s the best way to change that practice?
The idea is not to use _s to change the practice but _s follow the new standard practice

I would be interested how you would load the parent styles in child theme.

**Comment by mor10** [comment]
Relevant to this discussion: 

After this debate got started a while back, it appears a schism has formed in the documentation team. In Codex, the recommendation is still the (problematic) functions.php approach: https://codex.wordpress.org/Child_Themes. In the Theme Handbook however, the classic @import approach is recommended: https://developer.wordpress.org/themes/advanced-topics/child-themes

If the goal here is to create a consistent and straight forward user experience for theme and child theme developers, whatever implementation made in _s has to reflect official documentation. However, at the moment it appears that documentation is not in agreement with itself. 

IMO this is an example of an area where _s can serve a higher purpose so to speak. Where there is confusion and lack of direction, _s can provide a definitive and authoritative example that can end the confusion.

**Comment by justnorris** [comment]
This is what I've been using for a very long time in my themes, and I think it's the best solution for the end-users.
~~~
if ( is_child_theme() ) {
  wp_enqueue_style( '_s-child-style', get_stylesheet_directory_uri() . '/style.css'  );
}
~~~
1. If the user creates a child theme, like in the Codex, style.css is automatically enqueued and can be used to add styles.
2. If the user wants to rewrite **all** of the style, there is a is 95% chance that he/she is advanced enough, to dequeue parent style.
3. If you just created a child-theme to modify home.php - style.css is included anyway, but the overhead is tiny, but it's still a better approach than `@import` in my opinion.

**Comment by anagio** [comment]
As _s says _I'm a theme meant for hacking_ styles may be loaded any number of ways. _s should let people choose how they wan't to load them and certainly not add additional code to check for child themes. _s not checking for child themes and automatically loading styles is certainly not an issue. This issue should be closed.

**Comment by sixhours** [comment]
> _s should let people choose how they wan't to load them and certainly not add additional code to check for child themes.

That's how I feel, too.

Given we haven't been able to reach a consensus in some time, and no one has made an argument for or against either method that's compelling enough to move the issue forward, *and* the official WordPress documentation can't even agree with itself, I'd suggest closing this and leaving it as-is until a more compelling argument comes along.

**Comment by sixhours** [comment]
Closing this, with reasoning above.
