### ISSUE TITLE
post formats

### ISSUE THREAD

**Issue by saladaze** [Automattic/_s#675]
just a note, or maybe im oblivious... I was having some issues creating post-format templates. I created a content-aside.php file so I can adjust its appearance and no matter what I did I realized it was falling back to content-single.php

found this: https://core.trac.wordpress.org/ticket/17996 which locates the problem to the get post format code. 

line 15 on my _s package single.php reads 
`<?php get_template_part( 'content', 'single' ); ?>`

which should be

`<?php get_template_part( 'content', get_post_format() ); ?>`

if the formats were to work.

**Comment by philiparthurmoore** [comment]
This is definitely an issue that we need to fix in _s. The PR in #676 will fix this issue, so I'm going to close this and handle the update in that ticket instead. Thanks for bringing this up.
