### ISSUE TITLE
Custom header image

### ISSUE THREAD

**Issue by dafad** [Automattic/_s#678]
I wasn't able to set a default image for custom header. Shouldn't changes to $defaults in functions.php do the job? Seems like the defaults don't have any effect. Adding an image through the admin menu does work, though. Can anyone confirm this?

**Comment by jacklenox** [comment]
It doesn't look like you're referencing anything specific to `_s` here.

If you're using `_s`, the example for this is actually within [`inc/custom-header.php`](https://github.com/Automattic/_s/blob/master/inc/custom-header.php#L27). This file can optionally be included in `functions.php`. There isn't an array in there assigned to a variable `$defaults`.

There is an article about [Custom Headers on the WordPress codex](http://codex.wordpress.org/Custom_Headers).

If you continue to have problems I recommend seeking help on the [WordPress.org forums](https://wordpress.org/support/forum/themes-and-templates).

Issues reported here are for problems and improvements directly related to the `_s` starter theme.
