### ISSUE TITLE
the_archive_title function is pulled from general-template.php instead of /inc/template-tags.php

### ISSUE THREAD

**Issue by Kovas** [Automattic/_s#681]
Hello,

I've downloaded _s theme from underscores.me (advanced options) and noticed that modified `the_archive_title` function in `/inc/template-tags.php` had no effect on my theme, instead  `general-template.php` was used. I've changed function name and it solved my problem, but that didn't feel right :)

Sorry if I'm missing something.

**Comment by philiparthurmoore** [comment]
Hi @Kovas. Those functions are fallbacks for WordPress installs that do not natively support `the_archive_title`. So installs older than 4.1 should use the included template tags, while installs at 4.1 and newer will use Core's native functions. This is intentional.

**Comment by Kovas** [comment]
I see.  Well, thanks for explanation :)
