### ISSUE TITLE
Recent posts show thumbnail

### ISSUE THREAD

**Issue by thehung2224** [Automattic/_s#685]
This is the first time I use Underscores, how can I show either a small thumbnail of a image or featured image, from each post In my recent posts custom widget. Thank you

**Comment by philiparthurmoore** [comment]
Hi there; this isn't something that we're able to assist with, I'm afraid. This Issues tracker is for issues with the codebase of _s, for example potential bugs and enhancements to the starter theme. What you're asking for doesn't involve either so I suggest going to the WordPress.org support forums or the WordPress Development Stack Exchange site and asking for assistance. Cheers.

**Comment by sterndata** [comment]
thehung2224:  If you have questions, stop by #wordpress on IRC.

**Comment by emiluzelac** [comment]
You mean Slack 😜

**Comment by obenland** [comment]
There is no support on Slack. It's about Making WordPress.

**Comment by emiluzelac** [comment]
Aha I thought we moved all
