### ISSUE TITLE
WP newbie looking for help

### ISSUE THREAD

**Issue by CaptSaltyJack** [Automattic/_s#687]
Hey guys,

I'm a seasoned web developer but have pretty much zero experience hacking WP. I'm wondering, once I have a boilerplate theme uploaded, what do I do? Should I edit styles.css directly and change things as I'd like them to be displayed? What about adding extra DIVs and other HTML code, where does this all go? And how can I make my own shortcodes?

Maybe that's diving more into topics that are covered in the WP Codex...

**Comment by jacklenox** [comment]
Hi there, this is for reporting issues with the `_s` theme itself. If you want general help with theming, the [forums](https://wordpress.org/support/forum/themes-and-templates) are a good place to start.

To briefly answer your questions. Yes, many good themes are created with `_s` without changing any markup. Almost every element has at least one class that you can use to style it.

You add the extra `div`s wherever they want them to be.

And yes, [you can make your own shortcodes](http://codex.wordpress.org/Shortcode_API).

I would finally recommend that you check out [this guide to making themes](http://themeshaper.com/2012/10/22/the-themeshaper-wordpress-theme-tutorial-2nd-edition/).
