### ISSUE TITLE
.editorconfing

### ISSUE THREAD

**Issue by oriSomething** [Automattic/_s#688]
i think [editorconfig](http://editorconfig.org/) can be great to this project.
to those who doesn't know what it is. it's a file that forces your favorite code editor to follow some rules for some files by your definition.
for example:
- force tabs / space as indentation
- trim trailing white space
- force 2 or 4 space indentation
- ...

**Comment by emiluzelac** [comment]
This would fall into a personal preference actually :)

**Comment by oriSomething** [comment]
on the other hand, right now, everything is tabs so if someone uses editor's default settings of spaces he gon'na have mixed whitespace types on the document which could lead also to a mess.
also default of trailing white space it's always good for git and i'm sure not every one who uses this project is using trailing white space by default

**Comment by karmatosed** [comment]
I would absolutely say this is for personal choice not to be included in the project itself.

**Comment by corvannoorloos** [comment]
I'd say it has absolutely nothing to do with personal choice, but whether or not `_s` authors like to encourage people even better to use WordPress' coding standards when developing on this specific project (note, I'm not talking about any forks).

As is currently encouraged by the Travic CI setup, and similar as is handled with WordPress, Jetpack and almost any other mayor programming project.

It remains of course to the `_s` authors whether or not they'd like to include it.

**Comment by aryaprakasa** [comment]
Agreed! personal preference/choice is for production version  (generated via underscores.me).

But for the main branch of `_s`, which are open for public to pull request should be standardized. Just like WordPress [did](https://core.trac.wordpress.org/browser/trunk/.editorconfig).

We know that some editors require to install the plugin first and some editors didn't support `.editorconfig`. But this will help developers adhere `_s` style guide, which is based on WordPress Coding Standards.
