### ISSUE TITLE
Master Slider doesn't work with _S starter theme

### ISSUE THREAD

**Issue by thehung2224** [Automattic/_s#693]
The slider doesn't work with _S starter theme, I only styled the theme with css, but the slider is not displayed. The twentytwelve and twentyfourteen themes display the slider. help please.

**Comment by emiluzelac** [comment]
I would direct this to: https://wordpress.org/support/plugin/master-slider instead :)

**Comment by thehung2224** [comment]
I think this is _s problem. I already checked on 2 default themes and it worked.

**Comment by emiluzelac** [comment]
What would that problem be?

**Comment by chrisdc** [comment]
It seems to be working here. Do you still have the same problem with a fresh install of _s and no other active plugins?

**Comment by obenland** [comment]
No response in three weeks. Closing for now.
