### ISSUE TITLE
`small` rule is declared twice: _normalize.scss and typography/_copy.scss

### ISSUE THREAD

**Issue by FStop** [Automattic/_s#694]
[sass/_normalize.scss#L76](https://github.com/Automattic/_s/blob/ea84ceec956152db7ec5f221eaf9dcab283a3751/sass/_normalize.scss#L76) declares
```
small {
	font-size: 80%;
}
```

[sass/typography/_copy.scss#L47](https://github.com/Automattic/_s/blob/ea84ceec956152db7ec5f221eaf9dcab283a3751/sass/typography/_copy.scss#L47) declares
```
small {
	font-size: 75%;
}
```

This compiles to `font-size: 80%` followed by `font-size: 75%` in style.css.

**Comment by obenland** [comment]
Nice find! Would you want to create Pull Request to remove the latter?
Is this also in `style.css`?

**Comment by FStop** [comment]
Now that I know which one should be kept I'll be happy to create a PR in just a bit. 

This is also in style.css, so I assume I should include the change there?

**Comment by obenland** [comment]
Yes please!
