### ISSUE TITLE
Duplicate styling & SASS syntax

### ISSUE THREAD

**Issue by slushman** [Automattic/_s#697]
The b & strong tags are already declared bold in normalize, so the declaration in _copy.scss is a duplicate.

I also found several places in the SASS to improve the syntax. They don't change the final output, but make better use of SASS, reduce lines of code, and match files like _links.scss & _accessibility.scss:

_menu.scss, _galleries.scss, _buttons.scss, _fields.scss, & _elements.scss.

**Comment by obenland** [comment]
Fixed in 7ef388656ee80b80e6ec15e79497e8a1fa4705c1.
