### ISSUE TITLE
Documentation is needed for the CSS structure

### ISSUE THREAD

**Issue by karmatosed** [Automattic/_s#709]
We have a very particular structure and this is undocumented. I am going to make a start with a wiki page on this repo regarding this. Whilst we don't want _s (and it shouldn't need) to have a manual, enabling people to understand where to put things in their CSS is important. Props to @hugobaeta for raising this as an issue for new users.

I plan on working on this during maintenance week next week.

**Comment by obenland** [comment]
Wait!

**Comment by obenland** [comment]
Before we open the can of GitHub Wikis, have you considered making author-oriented documentation part of Underscores.me?

We worked hard at establishing underscores.me as the place to go to download the theme, and GitHub the place to go to work on the theme (meta). I'm not sure it would be beneficial to soften that up again.

**Comment by karmatosed** [comment]
I don't mind where it is so long as we document so that also works for me :)

**Comment by obenland** [comment]
:+1:

**Comment by ianstewart** [comment]
> We have a very particular structure

Is the structure too particular right now? And maybe something to fix there versus documenting it?

**Comment by hugobaeta** [comment]
@ianstewart I used the Sass version for the first time not that long ago, hence my conversation with @karmatosed. The first thing I found confusing was the rigid TOC numbered structure, and how I struggled to figure out where I'd put my own CSS for layout and other elements not covered in the structure.

I think a quick fix to that is simply removing the numbers in the TOC, that way it's easier to add new partials wherever one needs them, without breaking the numbered structure. Actually, I'm gonna make a patch for that right now, and we can discuss it around it  ;)

**Comment by ihorvorotnov** [comment]
+1 on documentation for SASS/CSS structure. Just started a new theme based on _s and one of the first changes I need to do is configure the main container `.site` global styles like width, alignment etc. And I'm stuck between several options - layout section, site section, site section root or primary/secondary subsection or even custom partial. 

Even basic inline comments in SCSS files would be great.

**Comment by karmatosed** [comment]
Closing this as working on underscores.me for this.
