### ISSUE TITLE
Template Tags.php

### ISSUE THREAD

**Issue by malvouz** [Automattic/_s#711]
At inc/template-tags.php there is function "the_posts_navigation" and "the_post_navigation" and the comment is
```
 @todo Remove this function when WordPress 4.3 is released.
```

I think it should be **WordPress 4.1** not 4.3.

**Comment by obenland** [comment]
Please see an explanation of why it is 4.3 [here](https://github.com/Automattic/_s/pull/707#issuecomment-76682536).
