### ISSUE TITLE
nofollow  for links in footer.php

### ISSUE THREAD

**Issue by HeikoMamerow** [Automattic/_s#712]
Hi, John Mueller (Webmaster Trends Analyst by Google) gave recently a tip, to put a nofollow rel-attribute to footer links like *"designed by link"*. Also he said: *"I guess this kind of looks at things like with regards to unnatural links, for example."*

I think, its better to follow his advice and put the nofollow rel-attribute in both links in footer.php. What do you think?

More infos & the video from his hangout here: https://www.seroundtable.com/google-nofollow-web-design-by-links-19943.html

Greetings from Berlin 
:-)

**Comment by emiluzelac** [comment]
I would recommend not.

First not all links are credited equally
https://m.youtube.com/watch?v=D0fgh5RIHdE and there's nothing in current
algorithm which would advise that this is bad or that it can hurt as in
anyway.

**Comment by jamigibbs** [comment]
I think the advice John's giving is specifically for those link that are placed on their own without being related to the overall content of the site. In the case of underscores, the WordPress links in the footer specifically relate to the project and "make sense" which he mentioned was ok.

Now what a developer does with those links once they've incorporated underscores in their project is an entirely different thing.

**Comment by obenland** [comment]
Yeah, let's not do that.

**Comment by HeikoMamerow** [comment]
Jo, that makes sense to me. 
tnx :-)
