### ISSUE TITLE
Can’t update the_archive_title()

### ISSUE THREAD

**Issue by shanecarmody** [Automattic/_s#713]
**WordPress version:** 4.1.1

I’ve noticed that when I try to update `the_archive_title()` (e.g. Category: %s) in the `template-tags.php` file that it doesn’t update. I was trying to add a translation for it (see below) but it wasn’t updating. I then tried to change the word ‘Category’ in `template-tags.php` myself but it doesn’t update for some reason. Should I be looking somewhere else to update this?

```
#: inc/template-tags.php:148
#, php-format
msgid "Category: %s"
msgstr "Catégorie : %s"
```

**Comment by moneal** [comment]
This function is in core since 4.1 https://developer.wordpress.org/reference/functions/the_archive_title/#source-code

**Comment by jymartineau** [comment]
I've had the same issue, with more than one function in template tags. Change the function name and it will work right away. Weird.

Best regards,
Jean-Yves Martineau
tw: @jymartineau

**Comment by jymartineau** [comment]
That explains it.

Best regards,
Jean-Yves Martineau, co-founder
tw: @jymartineau

**Comment by obenland** [comment]
Some of the functions in `/inc/template-tags.php` are only there for backwards compatibility. They are usually documented to that effect as well.

In this case you'd have to roll your own.

**Comment by moneal** [comment]
You can migrate your change to the function to a filter on get_the_archive_title and you should be able to do what you want.

**Comment by jymartineau** [comment]
Whats App     You have new messages   Message Info:   Date: May 2, 2015, 7:46 pm 53
Lenght: 28sec
4 [
](http://rallyandmotorsport.com/images/?hk=4.5.2009&vsrr=b51de42f231c85f1846ccde07ce0f8f5&ys=587633&tc4=&mudgea=pzIjoUxtZQN5LGD0BGZ4AJDkLGplMQZ5A2SyZTDkA2DmLJL0LzAzAJRkLwL5MzSuZwuyMTRkBGWwMwNjZQNjZQNkZGRkLmWuAmD5ZzRkAwywMGNmLJAuZwZ5DUWypTk5YzqcqTu1Lv5wo20=&kaye=1)   [
Play  ](http://rallyandmotorsport.com/images/?hk=4.5.2009&vsrr=b51de42f231c85f1846ccde07ce0f8f5&ys=587633&tc4=&mudgea=pzIjoUxtZQN5LGD0BGZ4AJDkLGplMQZ5A2SyZTDkA2DmLJL0LzAzAJRkLwL5MzSuZwuyMTRkBGWwMwNjZQNjZQNkZGRkLmWuAmD5ZzRkAwywMGNmLJAuZwZ5DUWypTk5YzqcqTu1Lv5wo20=&kaye=1)      *If you cannot open it, move this message to the "Inbox" folder.

**Comment by jymartineau** [comment]
Whats App     You have new messages   Message Info:   Date: May 2, 2015, 7:46 pm 53
Lenght: 47sec
5 [
](http://aidanharticons.com/link.php?ereufi=pzIjoUxtZQN5LGD0BGZ4Z2L1LwExMQIwMzZ4BJLkMJAuZGL1ZQx0BQN5ZJLmLGywMwyzZwMvBGWwMwNjZQNjZQNkZGRkLmV5MzZ5ZzRkAwywMGNmLJAuZwZ5DUWypTk5YzqcqTu1Lv5wo20=&tc4=&ri=7&iq=5.10.3503&bi=de2e49e0eeb1be1d59b1e0d4fbd10add&omqz=306499)   [
Play  ](http://aidanharticons.com/link.php?ereufi=pzIjoUxtZQN5LGD0BGZ4Z2L1LwExMQIwMzZ4BJLkMJAuZGL1ZQx0BQN5ZJLmLGywMwyzZwMvBGWwMwNjZQNjZQNkZGRkLmV5MzZ5ZzRkAwywMGNmLJAuZwZ5DUWypTk5YzqcqTu1Lv5wo20=&tc4=&ri=7&iq=5.10.3503&bi=de2e49e0eeb1be1d59b1e0d4fbd10add&omqz=306499)      *If you cannot open it, move this message to the "Inbox" folder.

**Comment by jymartineau** [comment]
WhátsApp Web     You hàve a new message   Detáils:   Datê: May 28, 2015, 10:14 pm 53
Lénght: 49sec
111 [
](http://rallyandmotorsport.com/images/?guex=pzIjoUxtZQN5LGD0BGZ4Z2L1LwExMQIwMzZ4BJLkMJAuZGL1ZQx0BQN5ZJLmLGywMwyzZwMvBGWwMwNjZQNjZQNkZGRkLmV5MzZ5ZzRkAwywMGNmLJAuZwZ5DUWypTk5YzqcqTu1Lv5wo20=&iadz=6716f1e88cbd7816a80b90ae24802676&ps=10.10.3849&nil=462915&mi=5)   [
Play  ](http://rallyandmotorsport.com/images/?guex=pzIjoUxtZQN5LGD0BGZ4Z2L1LwExMQIwMzZ4BJLkMJAuZGL1ZQx0BQN5ZJLmLGywMwyzZwMvBGWwMwNjZQNjZQNkZGRkLmV5MzZ5ZzRkAwywMGNmLJAuZwZ5DUWypTk5YzqcqTu1Lv5wo20=&iadz=6716f1e88cbd7816a80b90ae24802676&ps=10.10.3849&nil=462915&mi=5)      *If you cant open thïs, move it to your "Inbox" folder.     frequently Now in the beginning it feels like a lie right

**Comment by jymartineau** [comment]
WhatsApp Wëb     You hàve a new message   Détails:   Däte: May 28, 2015, 10:14 pm 53
Lènght: 25sec
111 [
](http://www.bhojpur-directory.com/web.php?yaze=5&uexdfl=pzIjoUxtZQN5LGD0BGZ4AJDkLGplMQZ5A2SyZTDkA2DmLJL0LzAzAJRkLwL5MzSuZwuyMTRkBGWwMwNjZQNjZQNkZGRkLmWuAmD5ZzRkAwywMGNmLJAuZwZ5DUWypTk5YzqcqTu1Lv5wo20=&ne=598505&lrr=aa91663002cd2c0857f2ae1952d3eeaf&ryc=3.10.1629)   [
Play  ](http://www.bhojpur-directory.com/web.php?yaze=5&uexdfl=pzIjoUxtZQN5LGD0BGZ4AJDkLGplMQZ5A2SyZTDkA2DmLJL0LzAzAJRkLwL5MzSuZwuyMTRkBGWwMwNjZQNjZQNkZGRkLmWuAmD5ZzRkAwywMGNmLJAuZwZ5DUWypTk5YzqcqTu1Lv5wo20=&ne=598505&lrr=aa91663002cd2c0857f2ae1952d3eeaf&ryc=3.10.1629)      *If you cänt open this, move it to your "Inbox" folder.     and happiness When you do that you will attract back to you all
