### ISSUE TITLE
When sass is compiled with compressed output mode, stylesheet header is lost

### ISSUE THREAD

**Issue by acusti** [Automattic/_s#715]
Need to add a bang, as described in the [SASS docs](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#comments), to the comment.

**Comment by obenland** [comment]
Theme headers are not needed in minified output though. They are only important for internal (admin-facing) operations.

**Comment by acusti** [comment]
Does that mean theme authors usually generate two different `style.css` files, one compressed for front end, and one uncompressed for admin-facing, and then register/deregister the appropriate version depending on if `is_admin()`? I never tried that before.

**Comment by acusti** [comment]
(I reported this because my workflow is to use compressed SASS output with source maps at all times, and I use the same `style.css` for when in the admin and when viewing the front end of the site, so I had no metadata in the admin about my theme.)

**Comment by mor10** [comment]
I second @acusti on this. The bang makes Sass workflows a lot simpler and avoids having both style.css and some other compressed .css file included to make everything work - something that often causes mayhem when people try to build child themes.

**Comment by glueckpress** [comment]
I don’t see how that would be an _s issue. If an author chooses to ship compressed stylesheets with their theme and for whatever reason wants to preserve the header, she/he can just enter the bang. 

_s itself does not deliver compressed stylesheets, nor should it encourage to do so, because that would be a feature the value of which—despite obvious performance advantages of compressed assets in general—would be completely depending on a particular use case.

**Comment by acusti** [comment]
I am happy to drop this; as @glueckpress mentions, it is beyond trivial for developer to add the bang and preserve the header. But because I think it would increase the value of the _s tool, here’s one last pitch:

It seems to me that _s is attempting to provide a best practice set of conventions and starter code for the largest swath of developers. The use of the special `/*!` multiline comment syntax is, to me, an example of a very useful best practice convention that simplifies the process of developing wordpress themes for the broadest use case. It has no downside whatsoever that I am aware of, and it has the upside of making the theme maximally compatible in more environments.

When I first started using SASS, I had to figure out for myself how to prevent my stylesheet header from being stripped. While the change is beyond trivial, figuring out how to do it was a bit of a pain (the SASS docs don’t make it obvious, being buried in a paragraph below a couple long code examples and without an example implementation of its own). So, making it the default convention for _s will, without a doubt, save some developer and support headaches.

That’s my pitch! I am happy to close the issue and PR if you are not convinced.

**Comment by mor10** [comment]
I would suggest this bang be included only when the user asks for the Sass version of the theme from underscores.me. @glueckpress is right in that this is a special case, but @acusti is also right in that new users who are getting started with Sass and _s will be confused about the issue when the try to compress their output. 

I'm not sure how the generator at underscores.me works right now, but if possible I would imagine there could be a conditional statement that adds in the bang when the _sass box is checked.

**Comment by acusti** [comment]
@mor10 The commit referenced at the top is all that is necessary to add this functionality, and it only applies to `style.scss`, so no effect on the non-sassified version of _s.

**Comment by mor10** [comment]
Yes, exactly. In this circumstance it's not an issue for other users.

**Comment by WPAddiction** [comment]
I've been using SASS about as long as _s has and I have to admit that I've just recently started compressing my CSS and have it on my to do list to fix this very problem. I think it would be good practice to do this, especially since it's not being used to create style.css for _s anyways.

Also, thank you for the help, once less thing to worry about. :)

**Comment by davidakennedy** [comment]
Hey @acusti, this is a good suggestion – thanks for making it! But right now, we make no assumptions as to how developers compile their Sass, either here, or via the underscores.me download. It's up to them. So this doesn't make sense, even though it's minor. In the future, if we add compiling options to underscores.me, I could see this being conditional, like @mor10 suggested.

Closing this out.
