### ISSUE TITLE
Can you sell this?

### ISSUE THREAD

**Issue by chrisdrogaris** [Automattic/_s#719]
Hi

I am wondering if I can use this to start with and make a template to sell on Themeforest or other marketplaces?

Is there any restrictions?

**Comment by philiparthurmoore** [comment]
Totally fine. You'll need to license your theme under the GPL, though, as _s itself is licensed `GNU General Public License v2 or later`. In short, if you release a theme on ThemeForest please ensure that you release it under the GPL and not Envato's other licensing options.
