### ISSUE TITLE
Conflict with Google Maps

### ISSUE THREAD

**Issue by polp6880** [Automattic/_s#720]
The "max-width: 100%" property on the img tag is conflicting with images used by the google map api when adding to a page as described here: https://developers.google.com/maps/documentation/javascript/examples/marker-simple. I always tend to fix this by doing something like:
```
#map-canvas img { max-width: inherit; }
```
... but I wonder if it's worth trying to find an alternative solution for this in future versions of the theme.

Similarly, Google added a Sign In option on the top right hand side of their embedded maps. When hovering over the profile picture, the tooltip is truncated.

**Comment by obenland** [comment]
Adding compat styles for third party apps sounds like a rabbit hole. A deep one.

**Comment by polp6880** [comment]
That's ok - it was just a suggestion ;) Thanks for the reply though.
