### ISSUE TITLE
CSS and Scripts are not loading in multisite

### ISSUE THREAD

**Issue by GreyCanary** [Automattic/_s#725]
Hello everyone,

I'm working on a theme for a multisite installation which does not seem to be working when I upload it. 

wp_enqueue_style( 'greycanary-style', get_stylesheet_uri() );

Is returning with

http://michaelwood.ca/digital-marketing/wp-content/themes/greycanary/style.css?ver=4.1.1

The theme location in multisite is actually

http://michaelwood.ca/wp-content/themes/greycanary/style.css?ver=4.1.1

Any idea how to correct this?

**Comment by davidakennedy** [comment]
Howdy @GreyCanary!

Thanks for reaching out. This repository and issues list is for the ongoing development of the `_s` theme. We don't offer support or troubleshooting here, but head over the the WordPress.org forums, and you should be able to find help. Check out the Multisite forum to start:

https://wordpress.org/support/forum/multisite

Good luck, and happy theming!
