### ISSUE TITLE
Mysterious 4px

### ISSUE THREAD

**Issue by PaulBart** [Automattic/_s#730]
Hello.  I've been using the _S theme to create a few themes of my own - really great what you have done.  However the last couple of job's I'm currently developing seem to have a mysterious 4px margin added to certain elements - images, divs etc.  It's really strange and I can't for the life of me find what's causing it!  I am having to create calc's to my margin setting of - 4px to get rid of them... any ideas??? I've even switched all the styles off in my browser and they still appear?

Thanks in advance

**Comment by jamigibbs** [comment]
What does Firebug or Inspect Element identify it as?

**Comment by emiluzelac** [comment]
Hi Paul,

I would try https://wordpress.org/support/forum/themes-and-templates
instead.

**Comment by PaulBart** [comment]
I though this was the theme support? Firebug or inspectors don't show anything, I can't physically select the 4px. I only know it's a margin because I've put a minus 4px to elements within the containing div. I'm working locally at the moment, maybe I'll post a link next week when I have it up on a remote server.

**Comment by chrisdc** [comment]
This is more for discussing bugs in / potential improvements to _s rather than general technical support. If the margins aren't showing up on a fresh install of _s then it sounds like something you're adding in (maybe using inline-block for layout).

**Comment by sterndata** [comment]
Stop by on the #Wordpress channel on IRC sometime and we'll look at your
site and offer advice.

 Steve

**Comment by PaulBart** [comment]
OK will head over there.  Thanks all.
