### ISSUE TITLE
Hfeed on single pages

### ISSUE THREAD

**Issue by dshanske** [Automattic/_s#740]
I considered sending a pull request for it, but I'm not sure if there is a historic reason for it I'm missing.

<div id="page" class="hfeed site">

This means that any page, regardless of if it is a single page or not, is a feed. If I understand the specification correctly, it should only add hfeed if it is not a singular page. A single page is not technically a feed.

Wanted to ask about this before submitting because I searched around and cannot find discussion on the matter.

**Comment by grappler** [comment]
This was partly discussed in https://github.com/Automattic/_s/issues/510

**Comment by dshanske** [comment]
I read #510 and saw where the issue of Microformats in general was brought up and the discussion of the placement of hentry, but not any discussion of hfeed. The decision that appeared to be made about hentry was that it was a core issue, which I would agree on. But this is about hfeed, which does not appear in core.

It could be added to core, but the addition of hfeed in core raises the same concerns about the current misuse of hentry in core...that changing the behavior would break more sites than it would fix. 

Since _s doesn't have a backward compatibility concern in this case, it could be fixed going forward to address the improper application without affecting any sites.

**Comment by grappler** [comment]
What would the code change that you make?

**Comment by dshanske** [comment]
There are some options I can think of.

1. Make the addition of hfeed to the div optional based on if(!is_singular())
2. Add hfeed based on the same condition to the body class, which would make it easier to override in a child of a theme based on _s in the future.
3. Remove the hfeed entirely, making it the responsibility of anyone concerned enough to add it to their theme.

**Comment by sixhours** [comment]
> Add hfeed based on the same condition to the body class, which would make it easier to override in a child of a theme based on _s in the future.

I like this idea most, since we already have a function to add classes to the body tag.

**Comment by sixhours** [comment]
See #820 for a potential patch, if we decide on a direction.

**Comment by davidakennedy** [comment]
Looks like we merged this PR, so closing this out.
