### ISSUE TITLE
Isn't a time to move wp_link_pages to template-tags.php?

### ISSUE THREAD

**Issue by mtomas7** [Automattic/_s#741]
Currently this same function sits in:

content.php
content-page.php
content-single.php

It can also be wrapped in !function_exists, so it could be change from the child theme.

**Comment by andyjsaint** [comment]
I would use a filter for this then you can still call wp_link_pages().

```
function _s_wp_link_pages_args( $args ) {

	$args['before'] = '<div class="page-links">' . esc_html__( 'Pages:', '_s' );
	$args['after']  = '</div>';	

	return $args;

}

add_filter( 'wp_link_pages_args', '_s_wp_link_pages_args' );
```

**Comment by karmatosed** [comment]
I don't think it needs moving out personally. We don't have to move everything into a function.

**Comment by fklein-lu** [comment]
I agree with Tammie. It's a call to a template tag, we should not add any further abstraction.

**Comment by obenland** [comment]
+1
