### ISSUE TITLE
Extracting zip from underscore does not set right folder permissions

### ISSUE THREAD

**Issue by lustremedia** [Automattic/_s#749]
I created a zip from underscores.me and extracted the theme into my wp on a linux machine. WP did not pick the theme up because all folders were extracted with 700 rights only. So WP could not pickup the theme. Did anyone else have an issue like that before?

When I did: http://serverfault.com/questions/363425/change-all-file-permissions-to-644-and-all-folder-permissions-to-755-recursively

All was well, but it took me like 1 hour to figure out what was wrong.

**Comment by obenland** [comment]
I'm sorry you ran into problems while getting set up with Underscores. File permissions is not something we'd have control over unfortunately.

Please feel free to check https://wordpress.org/tags/_s for more information and help.

**Comment by fabiangarga** [comment]
Run chmod on your linux terminal, its  very easy to  solve that. Sudo chmod -R 777 and the theme folder.

**Comment by lustremedia** [comment]
@obenland what I actually was asking is: Are the file permissions when generating the zip file zip correct, and could they be corrected?

**Comment by lustremedia** [comment]
@fabiangarga as you can see I have posted a stackoverflow q/a which solved the issue. 777 is certainly not what you want for all of your theme file and folders!

**Comment by emiluzelac** [comment]
Generated ZIP is 644, more than enough to be extracted. Please see
https://codex.wordpress.org/Changing_File_Permissions#Shared_Hosting_with_suexec

Also, you're more than welcome to compress under any permission you like :)

**Comment by lustremedia** [comment]
@emiluzelac 
> All directories should be 755 or 750.
> All files should be 644 or 640. Exception: wp-config.php should be 440 or 400 to prevent other users on the server from reading it.
> No directories should ever be given 777, even upload directories. Since the php process is running as the owner of the files, it gets the owners permissions and can write to even a 755 directory. 

.zip I got from http://underscore.me had 700 for all directories! Thus it threw me off!
