### ISSUE TITLE
Class names on content-page.php

### ISSUE THREAD

**Issue by slushman** [Automattic/_s#753]
Since the content-page.php file displays the content for a page, shouldn't the header class be page-header and the content class be page-content? Each of the other page files (archive.php, search.php, 404.php, content-none.php) all use those classes, it seems to me that content-page.php should too.

**Comment by obenland** [comment]
It's a little confusing, but that is WordPress for ya. :) `page-*` are classes for lists of posts, while a page is just another content type.

**Comment by slushman** [comment]
Ah. I guess that makes sense. I just ran into an issue with a project where the pages needed to be styled differently than the posts and noticed this difference. I wasn't sure if that was purposeful or something that was overlooked.
