### ISSUE TITLE
the_post_navigation function now exists in core, but a poorer cousin

### ISSUE THREAD

**Issue by mikelittle** [Automattic/_s#759]
The version of the_post_navigation in _s, that mentions in the comment "Remove this function when WordPress 4.3 is released." is already replaced by a same name function in core WordPress, however the functionality in core is less. It does not allow you to pass parameters to the underlying functions past the first two for example, the flag to stay within the same category.
Should core be encouraged to adopt the full functionality, or should _s go back to calling it's own version?

**Comment by philiparthurmoore** [comment]
I've run into this very same problem as of last week. I think that a Core ticket should be filed for this. The functions that it offers are somewhat limited.

**Comment by philiparthurmoore** [comment]
To explain this further to people who come along and read this ticket, [this](https://github.com/WordPress/WordPress/blob/ad475b3c696ed60cee43c1166a7ef6324cc58344/wp-includes/link-template.php#L2224) is the currently handling of `get_the_post_navigation`, which is invoked by `the_post_navigation`:

```php
/**
 * Return navigation to next/previous post when applicable.
 *
 * @since 4.1.0
 *
 * @param array $args {
 *     Optional. Default post navigation arguments. Default empty array.
 *
 *     @type string $prev_text          Anchor text to display in the previous post link. Default `%title`.
 *     @type string $next_text          Anchor text to display in the next post link. Default `%title`.
 *     @type string $screen_reader_text Screen reader text for nav element. Default 'Post navigation'.
 * }
 * @return string Markup for post links.
 */
function get_the_post_navigation( $args = array() ) {
	$args = wp_parse_args( $args, array(
		'prev_text'          => '%title',
		'next_text'          => '%title',
		'screen_reader_text' => __( 'Post navigation' ),
	) );

	$navigation = '';
	$previous   = get_previous_post_link( '<div class="nav-previous">%link</div>', $args['prev_text'] );
	$next       = get_next_post_link( '<div class="nav-next">%link</div>', $args['next_text'] );

	// Only add markup if there's somewhere to navigate to.
	if ( $previous || $next ) {
		$navigation = _navigation_markup( $previous . $next, 'post-navigation', $args['screen_reader_text'] );
	}

	return $navigation;
}
```

This isn't great, because the functions `get_previous_post_link` and `get_next_post_link` accept more parameters than just the three that are currently allowed by `get_the_post_navigation`:

```php
/*
 * Get previous post link that is adjacent to the current post.
 *
 * @since 3.7.0
 *
 * @param string       $format         Optional. Link anchor format.
 * @param string       $link           Optional. Link permalink format.
 * @param bool         $in_same_term   Optional. Whether link should be in a same taxonomy term.
 * @param array|string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
 * @param string       $taxonomy       Optional. Taxonomy, if $in_same_term is true. Default 'category'.
 * @return string The link URL of the previous post in relation to the current post.
 */
function get_previous_post_link( $format = '&laquo; %link', $link = '%title', $in_same_term = false, $excluded_terms = '', $taxonomy = 'category' ) {
	return get_adjacent_post_link( $format, $link, $in_same_term, $excluded_terms, true, $taxonomy );
}
```

The function `get_the_post_navigation` should be updated so that these additional parameters can be passed to it and workaround functions won't need to be created within the theme, _s included.

@mikelittle, does this accurately touch on the issue you're raising?

**Comment by mikelittle** [comment]
Hi @philiparthurmoore, Yes that summarises it nicely, thanks. 

Note that one of the three parameters to the new core function ```screen_reader_text``` is only used by the underlying ```_navigation_markup``` function and not by deeper```get_previous_post_link`` and ```get_next_post_link``` functions.

**Comment by obenland** [comment]
This sounds like it should be a core ticket, rather than an `_s` one, no?

**Comment by philiparthurmoore** [comment]
Yep. Happy to make one. Wanted to make sure we were on the same page.

**Comment by mtomas7** [comment]
I also was missing the way how to limit Next/Previous posts to same category as main post, as it was possible with the old function.

**Comment by ChaseWiseman** [comment]
Hey folks! I'm new around these parts, but I tried my hand at a ticket & patch for this here: https://core.trac.wordpress.org/ticket/32618

**Comment by philiparthurmoore** [comment]
@ChaseWiseman Thanks so much for this. I've been crazy-busy. Cheers.

**Comment by davidakennedy** [comment]
Thanks all for talking this through and @ChaseWiseman – thanks for the Core ticket and patch. I'm going to close this, as it looks like we'll pursue improvements in Core.

**Comment by ChaseWiseman** [comment]
Looks like this one's in: https://core.trac.wordpress.org/changeset/34715 :smile:
