### ISSUE TITLE
WooCommerce

### ISSUE THREAD

**Issue by fabianhenzler** [Automattic/_s#761]
Is there anything you recommend for WooCommerce? Is _s the right thing to start with?

**Comment by emiluzelac** [comment]
Please see: https://wordpress.org/support/plugin/woocommerce

**Comment by karmatosed** [comment]
I'm closing this as issues are for reporting or adding things to _s not to ask questions about other projects. Woo commerce is a plugin, if you want to create a theme to support it, you can start with any theme base. _s is a good starting point to creating a theme, so yep you can use it. But there are other options such as using http://www.woothemes.com/storefront/.
