### ISSUE TITLE
Customizing the default _S style.css file?

### ISSUE THREAD

**Issue by g12mcgov** [Automattic/_s#766]
I'm currently building a custom theme on top of the [_S Underscores Wordpress theme.][1] One of the things I immediately did was remove all the content in the `style.css` file, as I want to create my own styling (largely using Bootstrap). 

However, I can't seem to get certain attributes in the `style.css` to make changes to the html. For example, I'm trying to set the following `<h1>` tag to red in my `header.php` file. But it will not change.

`<h1 id="testOfContent">Test</h1>`

CSS (in the `style.css` file provided by Underscores):

    #testOfContent {
        color: red;
    }

However, the font remains black. How do you manipulate a wordpress theme (especially _S Underscores which is meant to be customizable) to use your own css? Any ideas as to why it won't register my own CSS?

Here's my `functions.php` file and how I'm loading the script:

    function tlas_css() {
		// Enqueue bootstrap css
		wp_register_style('bootstrap-css', get_template_directory_uri() . '/bootstrap-3.3.4/css/bootstrap.min.css');
		wp_enqueue_style('bootstrap-css');

		// Enqueue custom stylesheet
		wp_enqueue_style( 'tlas-custom-style', get_template_directory_uri() . '/css/tlas.css' );
		wp_enqueue_style( 'tlas-style', get_template_directory_uri() . '/style.css');
	}
    add_action(	'wp_enqueue_scripts', 'tlas_css' );

  [1]: http://underscores.me/

**Comment by emiluzelac** [comment]
Hi Grant, please try
https://wordpress.org/support/forum/themes-and-templates instead.
