### ISSUE TITLE
Site title color in the Customizer

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#768]
There is probably a ticket for this but could not find it.

Should `.site-title` be `.site-title a` in `customizer.js` so that color change work in live preview? Otherwise link color in `style.css` can overwrite the site title link color in live preview.

https://github.com/Automattic/_s/blob/master/js/customizer.js#L28

**Comment by carl-alberto** [comment]
I was also not able to find an open ticket about that issue so I have added a pull request for it in here: https://github.com/Automattic/_s/pull/785

**Comment by davidakennedy** [comment]
Fixed here: https://github.com/Automattic/_s/pull/785
