### ISSUE TITLE
Add Post Title to edit_post_link for Improved Accessibility

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/_s#774]
One small tweak we could make to improve the accessibility of `_s` is adding the post title to the `edit_post_link` and hiding it with `screen-reader-text`. We do this in a few other spots to provide more context to link text, and the case would be the same here.

Thoughts?

Pull request incoming. :smile:

**Comment by karmatosed** [comment]
Sounds a good idea to me.

**Comment by Daronspence** [comment]
Since it seems we're waiting on a second opinion, I second this.

**Comment by karmatosed** [comment]
@davidakennedy have you got any opnions on this?

**Comment by sixhours** [comment]
Fixed in #775
