### ISSUE TITLE
DIV ids

### ISSUE THREAD

**Issue by tivnet** [Automattic/_s#777]
Would it be better if less common names are used for IDs?

HTML like `<div id="content"` may conflicts with ~~WooCommerce's wrapper, for example~~ someone else's "content".

How about generating all IDs like `<div id="{my-theme-slug}-content"` ?

Just a suggestion.

Thanks

**Comment by emiluzelac** [comment]
Hi,

To add WooCommerce compatibility you would need to adjust your theme first: http://docs.woothemes.com/document/third-party-custom-theme-compatibility/#section-2

And `_s` specific wrappers are:

```
function s_wrapper_start() {
  echo '<div id="primary" class="content-area">';
}

function s_wrapper_end() {
  echo '</div>';
}
```

**Comment by tivnet** [comment]
@emiluzelac I knew that by mentioning WC, I open the Pandora box :-)

I know exactly how to make WC-compatible themes. Used that just for example.

What I wanted to say: having hard-coded common names is bad, in my opinion. Forget WC.

Thanks

**Comment by emiluzelac** [comment]
Plugins are made to work with any* given theme, not other way around ;)

**Comment by tivnet** [comment]
Now, since WC is part of Automattic, that's an internal issue :)

**Comment by emiluzelac** [comment]
:)

**Comment by karmatosed** [comment]
Whilst I understand the motivation behind this request, I would say currently there are no plans to change this. I also don't agree that we should change it just to work around any plugin - no matter what that plugin is. Having an id labelled content is normal practice in a lot of themes, so there is no current urgency or need for us to change this.
