### ISSUE TITLE
Improve links to WordPress Documentation in comments at the top of files.

### ISSUE THREAD

**Issue by PJ-Finlay** [Automattic/_s#780]
I'm starting out with WordPress and I've been using this theme as a starter theme for the website I'm making, and I've found the short descriptions of what a file does and the links to the proper documentation on codex.wordpress.org very helpful. However this is not universally present throughout the project. For example in template-parts  content-search.php and content-none.php have a link to the template hierarchy page in the WordPress documentation while the other three files don't. I would like to create a pull request for this. Would my contribution be welcome? Thanks.

**Comment by obenland** [comment]
Absolutely!

**Comment by PJ-Finlay** [comment]
Thanks I'll try to have a pull request somewhat quickly.

**Comment by davidakennedy** [comment]
Looks like the associated pull request for this got merged, so closing it out. Thanks!
