### ISSUE TITLE
Resolve strict comparison warnings

### ISSUE THREAD

**Issue by grantpalin** [Automattic/_s#784]
I've been working on a theme based off of _s. Running PHP_CodeSniffer with the WordPress checks yields numerous results, including several warnings on using strict comparisons (`===` and `!==` instead of `==` and `!=`). I decided to run the check against a fresh download from here.

I ran the following command, which limits to just the relevant sniff:

    phpcs --standard=WordPress --sniffs=WordPress.PHP.StrictComparisons .

And the results:

    FILE: C:\Users\Grant\Downloads\_s-master\_s-master\comments.php
    ----------------------------------------------------------------------
    FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
    ----------------------------------------------------------------------
     73 | WARNING | Found: !=. Use strict comparisons (=== or !==).
    ----------------------------------------------------------------------
    
    FILE: ...\Users\Grant\Downloads\_s-master\_s-master\inc\custom-header.php
    ----------------------------------------------------------------------
    FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
    ----------------------------------------------------------------------
     49 | WARNING | Found: ==. Use strict comparisons (=== or !==).
     58 | WARNING | Found: ==. Use strict comparisons (=== or !==).
    ----------------------------------------------------------------------
    
    FILE: ...\Users\Grant\Downloads\_s-master\_s-master\inc\template-tags.php
    ----------------------------------------------------------------------
    FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
    ----------------------------------------------------------------------
     106 | WARNING | Found: ==. Use strict comparisons (=== or !==).
    ----------------------------------------------------------------------
    
    FILE: ...\Downloads\_s-master\_s-master\template-parts\content-search.php
    ----------------------------------------------------------------------
    FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
    ----------------------------------------------------------------------
     16 | WARNING | Found: ==. Use strict comparisons (=== or !==).
    ----------------------------------------------------------------------
    
    FILE: ...s\Grant\Downloads\_s-master\_s-master\template-parts\content.php
    ----------------------------------------------------------------------
    FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
    ----------------------------------------------------------------------
     14 | WARNING | Found: ==. Use strict comparisons (=== or !==).
    ----------------------------------------------------------------------

The first incidence seems like it may be left over from https://github.com/Automattic/_s/issues/632. The rest look like they can be easily resolved by amending the operator.

If there's no disagreement I can offer a pull request to resolve these warnings.

**Comment by davidakennedy** [comment]
@fklein-lu Pinging you since you've done a lot of work on the CodeSniffer side of things. What are your thoughts here?

**Comment by philiparthurmoore** [comment]
FWIW I always take heed of these warnings and fix them. Would love to hear Fränk's thoughts.

**Comment by fklein-lu** [comment]
Yes, we should fix these.

We could hold off on `inc\custom-header.php`, since that will go away with the release of 4.3 very soon.

**Comment by davidakennedy** [comment]
So @grantpalin, full steam ahead on that pull request if you want to work on it. We'd appreciate it!

**Comment by grantpalin** [comment]
@davidakennedy Will do, hopefully later today.

**Comment by davidakennedy** [comment]
All merged! Thanks @grantpalin!
