### ISSUE TITLE
How to customize blog index page

### ISSUE THREAD

**Issue by hgnelson83** [Automattic/_s#787]
Hello. I've trying to customize the Blog index page, but I am changing the index as well. How I go about that? Any help would be appreciated. I created home.php which also changes index.php. Please help me.

**Comment by emiluzelac** [comment]
Hi,

For theme support go to
https://wordpress.org/support/forum/themes-and-templates instead :)

**Comment by davidakennedy** [comment]
Hey @hgnelson83!

Please follow the advice of @emiluzelac and head to the forums for support. This Github repository is for the development purposes of _s.

Happy theming!
