### ISSUE TITLE
Unnecessary Sass ampersand for post navigation

### ISSUE THREAD

**Issue by jamigibbs** [Automattic/_s#791]
I don't think that these ampersands are necessary for the post navigation. The post nav classes are appended to the parent class either way. Perhaps there's something I've overlooked though.

```
	& .nav-previous {
		float: left;
		width: 50%;
	}

	& .nav-next {
		float: right;
		text-align: right;
		width: 50%;
	}
```

https://github.com/Automattic/_s/blob/00e6610198a0fbed48c13765f6b532889e7a8db6/sass/navigation/_menus.scss#L87-L104

I'll be happy to submit a pull request that removes them if it's agreed they're superfluous.

**Comment by slushman** [comment]
+1. The ampersand on the .site-main needs to stay since its reorders the selectors, but these are unnecessary.

**Comment by davidakennedy** [comment]
@jamigibbs Thanks for filing this issue! And good catch! I did a quick test, and those ampersands don't seem to matter. Please submit a PR.

**Comment by davidakennedy** [comment]
Nevermind @jamigibbs! I just noticed you submitted #795. Please squash your commits and we'll merge. :smile:
