### ISSUE TITLE
W3C compliant markup, adding role="" is outdated

### ISSUE THREAD

**Issue by DesignByKiltz** [Automattic/_s#797]
After removing all role="" from the _S template:
404.php
archive.php
comments.php
footer.php
header.php
template-tags.php
index.php
page.php
search.php
sidebar.php
single.php

During validation, these errors come up:
![screenshot188](https://cloud.githubusercontent.com/assets/12480193/9336976/5d6b9cc8-4591-11e5-9a5f-cb2b4181a5cc.jpg)

I have tracked this down to WP /inc link-template.php and general-template.php.

**Comment by emiluzelac** [comment]
Hi,

I don't believe that we're at that stage yet, please see: http://www.w3.org/WAI/GL/wiki/Using_HTML5_nav_element

Thanks,
Emil

**Comment by davidakennedy** [comment]
Hey @DesignByKiltz!

Thanks for filing this issue! We made a decision on this recently in #786. We're going to keep the `role`s for now, but we may drop them in the not-too-distant future.

Cheers!
