### ISSUE TITLE
Help - Can WP Customizer and Sass make a CSS baby together?

### ISSUE THREAD

**Issue by cliffordp** [Automattic/_s#807]
funny title, honest question. thanks for your help...

I used to use a WP Theme that implemented LESS. Every time I changed one of the theme's color or other LESS-variable-type settings, it cleared the cache and generated a new .css file.

I asked some friends and they said Sass is compiled client-side (e.g. PHP), but I'm not sure where that leaves me in terms of what I'm wanting to accomplish, which is giving the end user a WP Customizer color picker for `primary_color` and `accent_color` and then using those 2 colors to generate all the other colors via Sass (maybe some layout variables too) and get those compiled to a `.css` file.

Is it possible to build an _s theme that has Sass compile to CSS on page reload from WP Customizer settings?

**Comment by sarahmonster** [comment]
Hi there, 

This repository is for development and bugs. 

For theme support and development help, please head over to https://wordpress.org/support/forum/themes-and-templates instead :)

Have a lovely day!

**Comment by cliffordp** [comment]
Ok. Thanks. A WP Slack channel said it was ok to ask q's here instead of there. No problem though.

For anyone else's future reference: https://wordpress.org/support/topic/help-can-wp-customizer-and-sass-make-a-css-baby-together
