### ISSUE TITLE
Stray paragraph tag when tagline is empty

### ISSUE THREAD

**Issue by mor10** [Automattic/_s#825]
This is a problem that spans beyond _s, but it can be solved here:

If a user leaves the Tagline field empty, _s outputs an empty `<p></p>` in the markup. This is sub-optimal.

A quick search of the codex shows the current implementation of the tagline code in header.php is correct, but imo it is not good form to leave stray empty tags when content is not provided by the user.

Ideally there would be some sort of test to see if `get_bloginfo( 'description' );` is empty before the paragraph tags and function call are triggered. However, in the present state that results in the Tagline preview not working in Customizer if the user originally left the field blank.

**Comment by fklein-lu** [comment]
As you mention, this would interfere with the live preview in the Customizer, that is handled in `js/customizer.js`.

If the user has no site description, or the user deletes the site description, then the HTML markup output would have to be recreated, so we have to refresh the entire page.

Not a fan of adding more complexity like #826 just for this.

**Comment by obenland** [comment]
> If the user has no site description, or the user deletes the site description, then the HTML markup output would have to be recreated, so we have to refresh the entire page.

That should not be an issue with #826, is it? I wouldn't mind it going in, it's certainly not the most complex code that we've added recently.

**Comment by philiparthurmoore** [comment]
Those empty p tags when taglines are left blank make me twitch in a big way. #826 seems to handle this in a sensible manner and it's not complex at all.

**Comment by mor10** [comment]
I think this is a pretty clean solution.
