### ISSUE TITLE
Search input padding-right issue

### ISSUE THREAD

**Issue by bounasserabdelouahab** [Automattic/_s#828]
Search inputs have an extra padding to the right, the cause of this problem is the use of `-webkit-appearance: none;` at line 234 in `style.css`, changing that to `display: none` does fix the issue.

**Comment by baljindersingh88** [comment]
is that fixed ?

**Comment by karmatosed** [comment]
This to me comes under styling rather than something we should fix in _s. As a result I am going to close this for now.
