### ISSUE TITLE
Removing Styling from Semantic Elements

### ISSUE THREAD

**Issue by dshanske** [Automattic/_s#829]
Suggesting that the use of microformats classes as elements to be styled by CSS be removed as much as possible, most notably hentry.

**Comment by obenland** [comment]
Please feel free to open a PR with a suggested implementation.

**Comment by karmatosed** [comment]
@dshanske are you able to do a PR for this?

**Comment by dshanske** [comment]
I am. I have been a bit tied up with my day job. But I will have some time soon. Just a matter of styling article instead of hentry, for example.

**Comment by karmatosed** [comment]
That's great, look forward to it.

**Comment by davidakennedy** [comment]
I'd be up for seeing a PR too @dshanske. We've talked a bit about this via email, and _s doesn't have some of the restrictions on backward compatibility that Core, or currently-released themes do.

**Comment by limestreet** [comment]
Hi, .hentry has margin assigned, we want to remove this margin or move to other element/class?

**Comment by dshanske** [comment]
#860 seems to address hentry specifically. The others, entry-content, entry-summary, etc. are a bit more complex to figure out unless we add another class for styling, which I know was an idea rejected in another context.

**Comment by davidakennedy** [comment]
> seems to address hentry specifically. The others, entry-content, entry-summary, etc. are a bit more complex to figure out unless we add another class for styling, which I know was an idea rejected in another context.

Right, I updated the PR to remove styling from the `hentry` class, but I'm not sure it makes sense to go so far as to remove styling on all class names associated with microformats.

**Comment by dshanske** [comment]
So it may be sufficient at this time without further changes.

**Comment by sixhours** [comment]
It sounds like we're OK with closing this, since #860 should address the main concern here. Is that right?

**Comment by davidakennedy** [comment]
Yeah, I'd close so we can continue discussion in one place.
