### ISSUE TITLE
Cant use with bbpress

### ISSUE THREAD

**Issue by nhanco** [Automattic/_s#830]
Hello,
I used underscores with bbpress. i just apple some CSS and HTML not adding any special function. And when i visit my forum. I only see the forum’s name topis number post number. But it dont have any HTML warped. Please give me a solution me.
thankg for helping me.

**Comment by sarahmonster** [comment]
This repository is for development and bugs.

For theme support and development help, please head over to https://wordpress.org/support/forum/themes-and-templates instead.  :)

Have a lovely day!
