### ISSUE TITLE
Custom walker class for nav affecting anchor tags attributes

### ISSUE THREAD

**Issue by Doug021786** [Automattic/_s#833]
In underscores I created a custom navigation walker class from the template in <code>nav-menu-template.php</code>. However the Walker class does not inherit the inner HTML or the attributes of the anchor tags inside the li tags. 

I discovered this bug trying to implement a canvas tag inside of the anchor tags. The canvas implementation was successful, however even when I copy the code in <code>nav-menu-template.php</code> exactly I still run into the same issue. 

This bug is also reported on <a href="http://wordpress.stackexchange.com/questions/205056/custom-walker-anchor-tag-not-inheriting-attributes" target="_blank">Stack Exchange</a>

I believe _s could be improved by discovering issues in the filters that are affecting the anchor tags and nav titles and producing documentation that would assist developers in making successful custom walker classes for their themes.

**Comment by karmatosed** [comment]
I am trying to work out what you are asking and this feels to me either core or related to extending _s. It doesn't feel like something we should be doing in _s itself. As a result, I am tentatively going to close this for now.
