### ISSUE TITLE
background & sidebar

### ISSUE THREAD

**Issue by rebelholic** [Automattic/_s#834]
Hello,

1. How I can add a fullscreen background image to fit in one layout from header to footer?
2. How I can create a right sidebar with integrate advanced search like concept below?
![conceptsearch](https://cloud.githubusercontent.com/assets/6254876/10537977/955427b0-741f-11e5-8695-d89a963000ec.jpg)

**Comment by sixhours** [comment]
Howdy! This repo is for bug reports and suggestions specific to the _s theme. You'll find general support on the WordPress.org support forums: https://wordpress.org/support/
