### ISSUE TITLE
".main-navigation .current-menu-ancestor > a" in stylesheet missing

### ISSUE THREAD

**Issue by yet-another-Daniel** [Automattic/_s#835]
In the current style.css there are the following selectors for highlighting the current menu item:

.main-navigation .current_page_item > a,
.main-navigation .current-menu-item > a,
.main-navigation .current_page_ancestor > a {
}

If you click on a sub-menu-item the main menu item will not be selected.

I suggest to add:

.main-navigation .current-menu-ancestor > a

**Comment by limestreet** [comment]
I created PR for this issue: #837

**Comment by karmatosed** [comment]
I'm not seeing this as a bug. Can you provide a link where this occurs perhaps to check it out? Even a video would be great.

**Comment by yet-another-Daniel** [comment]
I have no video for this. Just take the last three standard WP-themes for example. They corrected this issue:

- twentythirteen:
.nav-menu .current_page_item > a,
.nav-menu .current_page_ancestor > a,
.nav-menu .current-menu-item > a,
**.nav-menu .current-menu-ancestor > a** {
	color: #bc360a;
	font-style: italic;
}

twentyfourteen:
.site-navigation .current_page_item > a,
.site-navigation .current_page_ancestor > a,
.site-navigation .current-menu-item > a,
**.site-navigation .current-menu-ancestor > a** {
	color: #55d737;
	font-weight: 900;
}

twentyfifteen:
.main-navigation .current-menu-item > a,
**.main-navigation .current-menu-ancestor > a** {
	font-weight: 700;
}

Why to highlight a submenu-item when the main menu item remains not highlighted. Nobody could see which menu is currently active.

You can leave it like that but I don't see the point that nearly every theme developer will insert this piece of code by itself.

**Comment by iamtakashi** [comment]
+1 to add the selector as I've also needed to add it many time before. In fact, this realised me that I forgot  to add it in Twenty Sixteen but it's fixed now. Thanks :)

**Comment by karmatosed** [comment]
I've merged it then :)
