### ISSUE TITLE
Learn more link in skip-link-focus-fix.js renders incorrectly after generating theme from underscores.me

### ISSUE THREAD

**Issue by fostertime** [Automattic/_s#838]
**_s** on Line 6 of **skip-link-focus-fix.js**
```
* Learn more: https://github.com/Automattic/_s/pull/136
```
Renders as **Theme Name** (whatever the user may name it)
```
* Learn more: https://github.com/Automattic/Theme Name/pull/136
```
after Generating the theme at Underscores.me

**Comment by davidakennedy** [comment]
Thanks for the report. We have an open issue for this in the Undercores.me repo, but haven't tackled it yet. See:

https://github.com/Automattic/underscores.me/issues/39

**Comment by davidakennedy** [comment]
Reopening, because this suggestion might be a good short-term solution:

https://github.com/Automattic/underscores.me/issues/39#issuecomment-151944960

**Comment by fostertime** [comment]
This issue has been resolved, via merged #842

**Comment by davidakennedy** [comment]
Thanks @fostertime! I forgot to double back here. :smile:

**Comment by fostertime** [comment]
@davidakennedy no problemo! A lot to keep track of! :)
