### ISSUE TITLE
Clicking on Anchor links cuts off page

### ISSUE THREAD

**Issue by wumbriac** [Automattic/_s#843]
My problem is: I’m trying to create anchor links within a page, but whenever I click those anchor links, the page gets cut off and only shows the content from the anchor point and down. No content above it shows. Do you possibly have a fix for this?

**Comment by sarahmonster** [comment]
Hi there,

This repository is for development and bugs.

For theme support and development help, please head over to https://wordpress.org/support/forum/themes-and-templates instead :)

Have a lovely day!
