### ISSUE TITLE
Google Search Console reveals some errors with structured data on pages

### ISSUE THREAD

**Issue by benoitchantre** [Automattic/_s#844]
In the structured data section of Google Search Console, there are errors with pages because they have `hentry` class don't have the following fields to be valid:
- author
- entry-title
- updated

There's already a [ticket on trac](https://core.trac.wordpress.org/ticket/28482), but it won't be fixed because a lot of website will break if they keep only hentry for posts.

The solution should be managed on a per-site basis by unsetting the class name in a `post_class` filter.

Would you accept a fix for this issue in _s ?

**Comment by karmatosed** [comment]
I'm not sure. To me, this is a starter theme and not sure right place. Lets get a second opinion.

**Comment by obenland** [comment]
I'm not opposed to this. We'd have to review our CSS though to make sure we're not relying on the class being there outside of syndicated content.

**Comment by davidakennedy** [comment]
I'd be willing to see a PR for this too, and consider it. This issue comes up often from users at WordPress.com, and we often can't remove the classes because of child themes and/or custom CSS used by site owners.

**Comment by davidakennedy** [comment]
I gave this a go. There may be a better way to go about it.

Also, is this bad practice, since plugins may rely on that class?

**Comment by dshanske** [comment]
Well, does the possibility of a plugin having an issue outweigh the need for proper markup?

**Comment by sixhours** [comment]
The above patch works for me.

I'd say proper markup > plugin breakage in this case.

It looks like CSS was also adjusted to account for this in #860 

Any objections to merging #860?

**Comment by philiparthurmoore** [comment]
#860 should be quickly looked over again and merged. It's a good change.

**Comment by joyously** [comment]
What's the holdup for this?

**Comment by grappler** [comment]
@joyously See the discussion at #860

**Comment by davidakennedy** [comment]
Closing in favor of the path outlined in #1268.
