### ISSUE TITLE
is_search check in jetpack infinite render

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#846]
Shouldn't there be `is_search` check in `inc/jetpack.php` `_s_infinite_scroll_render` function?

Something like this:

```
if ( is_search() ) :
	get_template_part( 'template-parts/content', 'search' );
else :
	get_template_part( 'template-parts/content', get_post_format() );
endif;
```

**Comment by karmatosed** [comment]
Adding that we have a PR here for this: https://github.com/Automattic/_s/pull/848

**Comment by iamtakashi** [comment]
Correct. For search result page, `template-parts/content-search.php` should be used.

**Comment by davidakennedy** [comment]
Fix is merged.
