### ISSUE TITLE
getting error on get_header

### ISSUE THREAD

**Issue by bayridge1** [Automattic/_s#866]
Fatal error: Call to undefined function get_header() in /home/userid/public_html/website.com/_s-master/index.php on line 15

Where is get_header function, I can't find it.

Is there a newer version maybe?

...
get_header(); ?>

	<div id="primary" class="content-area">
		<main id="main" class="site-main" role="main">
...

**Comment by sheabunge** [comment]
This theme must be used inside WordPress. Don't try to directly load the .php files.
