### ISSUE TITLE
Call to undefined function get_header()

### ISSUE THREAD

**Issue by hasannawaz** [Automattic/_s#868]
So basically if i call directly the index.php file in the theme directory 
e.g using a browser. 
http://hasan.dev/wp-content/themes/hasan/index.php

It throws the following error :
​*Fatal error: Call to undefined function get_header() in /var/www/public/wp-content/themes/hasan/index.php on line 15*

I found the issue reported by newrelic as for some reason Microsoft discovery protocol is calling this page directly searching for webdav i guess.

**Comment by alaczek** [comment]
This is not _s issue, themes files are not meant to be accessed directly.

**Comment by hasannawaz** [comment]
@alaczek 
Well what happens if they are for some reason accessed ? because somebody is calling the file with direct link because its public ? shouldn't it be handled gracefully with an exception ?

**Comment by alaczek** [comment]
Direct access to files can be disabled from php.ini or .htaccess.

If you feel strongly about this, you can open a PR with your reasoning behind it, and we'll get more eyes on it and discuss.
