### ISSUE TITLE
Lacking wp-comments-post.php file when receiving challenge from Cloudflare

### ISSUE THREAD

**Issue by benfrain** [Automattic/_s#875]
When a user of mine gets a security challenge from Cloudflare CDN they are met with a CAPTCHA page. When the user enters the CAPTCHA data they are met with a blank wp-comments-post.php page.

If I disable CloudFlare, the comment form on posts behaves as I would expect. Should the page wp-comments-post.php actually exist in the theme? Or is this purely something odd to do with Cloudflare?

**Comment by obenland** [comment]
`_s` doesn't have a `wp-comments-post.php` file, so it's likely something wonky with Cloudflare.
