### ISSUE TITLE
Adding comment does not provide a 'awaiting moderation' comment and comment preview

### ISSUE THREAD

**Issue by benfrain** [Automattic/_s#876]
I've noticed that if a user that has not commented on my site before posts a comment they get no indication that their message is being held in a moderation queue. The page simply refreshes as if nothing has happened.

In a previous theme I used there was some logic to handle this scenario:

```php
<?php if ($comment->comment_approved == '0') { ?>
        <div class="alert alert-block fade in">
          <a class="close" data-dismiss="alert">×</a>
          <p><?php _e('Your comment is awaiting moderation.', 'roots'); ?></p>
        </div>
      <?php } ?>
```

But I can find no equivalent in underscores. Does this functionality exist in underscore?

**Comment by obenland** [comment]
`_s` doesn't have a custom comment handler but uses WordPress' built-in one. `wp_list_comments()` will eventually call `Walker_Comment::html5_comment()` that handles that.
https://core.trac.wordpress.org/browser/trunk/src/wp-includes/class-walker-comment.php?rev=35013#L335

**Comment by benfrain** [comment]
OK, so are you telling me that I should be seeing an awaiting moderation message?
