### ISSUE TITLE
HTML5 Input Type Styles Redux

### ISSUE THREAD

**Issue by mrwweb** [Automattic/_s#885]
*Yes. I've read #280, #606, #613, #614, and #845. I'm hoping we can reopen this discussion because it's 2015 and I've got some data points to share. I'm happy to put together a PR, but I thought I should ask before investing any additional work.*

## tl;dr
 It's 2015 and time to style all (or at least `number` and `tel`) HTML5 input types. Core, form plugins, and the internet at large are all going that direction.

## The primary issue
\_s only includes styling for _some_ HTML5 input types and excludes at least two common ones.

## Back story
I've been using some Automattic themes recently and [filed an issue on Sequential](https://wordpress.org/support/topic/no-support-for-inputtypetel?replies=8) about `input[type="tel"]` and `input[type="number"]` recently. I ran into the issue again with Sela and realized I needed to look upstream since it's obviously coming from a similar code base. That took me to [Automattic's Theme Pattern Library](https://github.com/Automattic/theme-pattern-library) and then back to \_s. (Six-degrees of \_s, anyone?)

Here's a simple Gravity Forms form using Sela (without my child theme styles to fix this all):

![basic gravity forms form in Sela theme](https://cloud.githubusercontent.com/assets/1238696/11637327/8cd2fc2c-9cd5-11e5-814f-832ac2cc3605.png)

Note "Phone" and "Total Number of Guests" have a different border color (among other things). When I look at why this is, it's pretty easy to directly track this back to the included list of HTML5 input types in \_s.

## Previous arguments against inclusion:
@obenland in [Aug 2013](https://github.com/Automattic/_s/pull/280#issuecomment-22466443):
> Let's stick with what comes with core for now.

@karmatosed in [Sept 2014](https://github.com/Automattic/_s/pull/614#issuecomment-55486328):
> My feelings were that we should support the common ones. Even when I was freelance I can't recall the last time tel was supported in something I did, I don't think it's that common.
> This all said, if we did include it we should include everyone - perhaps a slippery slope we may not want to go down yet?

## Data
As best I could in an hour+, I reviewed Core, Jetpack, Gravity Forms, Contact Form 7, Ninja Forms, and Formidable (all power tens of thousands of sites on the low end). You can see [my preliminary data](https://docs.google.com/spreadsheets/d/1amW5LiM72o5xTMXOpKYAV7QOAD2sA9HVGfknsw7bXBA/edit?usp=sharing). Please let me know if I can update.

### Results
- If we were to includes styles for all fields types that Core outputs on the front _or_ backend: text, email, password, number, url, and search. (I'm leaving our file for now.)
- If we were to includes styles for all fields types that at least two plugins include: text, email, number, password, url, tel. (Range and Date are only supported by CF7)
- If we were to includes styles for all fields types that Core *styles*: All valid HTML5 input types (see `/wp-admin/forms.css`)

## A few more observations
- These input types have [strong browser support](http://www.wufoo.com/html5/#types).
- Most (all?) of the HTML5 input types fallback to `input[type="text"]` in unsupported browsers, so graceful degradation means we can use these *now*.
- With the rise of mobile, both `number` and `tel` trigger different keyboards in most mobile OS's, greatly increasing the [benefits of using these input types](http://www.smashingmagazine.com/2015/05/form-inputs-browser-support-issue/).
- [Google recommends using these](https://developers.google.com/web/fundamentals/design-and-ui/input/forms/choose-the-best-input-type?hl=en).

## Conclusion
I think both of the reasons for _not_ doing this are gone:
- Core anticipates these types' usage and includes styles for them
- `tel` and `number` are both fairly widely used

There are good reasons to use these input types and not many reasons not to. \_s tries to be modern and follow best practices (sometimes too much, in the case of things like HTML5 heading structure), but I think this is one place where clearly \_s is lagging behind modern developer practices.

### Moving forward?
The only question then is how to improve the styles. Do we include a list of all valid HTML5 inputs or do we style `input` and then apply additional styles to inputs that shouldn't be "text-y" in appearance (e.g. `input[type="button"]`)? (This was raised by @philiparthurmoore in [Sep 2014](https://github.com/Automattic/_s/pull/614#issuecomment-55486419).).

Based on what I've seen others do, I think listing them all—while slightly more verbose—is probably the way to go. I'm not super up on this, but I haven't seen anything to suggest that more input types will be added any time soon. (And then we can have this whole discussion all over again!)

**Comment by iamtakashi** [comment]
FYI, `tel` and `number` types are included in Twenty Sixteen to have a consistent style.

So, yes, +1 from me to include those two.

**Comment by samikeijonen** [comment]
+1 from me too.

**Comment by philiparthurmoore** [comment]
> Based on what I've seen others do, I think listing them all—while slightly more verbose—is probably the way to go.

I agree with this.

**Comment by philiparthurmoore** [comment]
@mrwweb, can you make a patch?

**Comment by mrwweb** [comment]
I'm on it!

=================
Mark Root-Wiley
MRW Web Design <http://mrwweb.com/>
*Thoughtful Websites for Nonprofits & Mission-Driven Organizations*

info@mrwweb.com
206-745-2581

*Need to send me a password? Please use** PWPush.com <http://PWPush.com>**!*

@mrwweb <https://github.com/mrwweb>, can you make a patch?

—
Reply to this email directly or view it on GitHub
<https://github.com/Automattic/_s/issues/885#issuecomment-162788089>.

**Comment by mrwweb** [comment]
PR on #887. Includes new style for `<select>` and a question about `<textarea>` padding.
