### ISSUE TITLE
Remove default implicit ARIA semantics

### ISSUE THREAD

**Issue by benoitchantre** [Automattic/_s#889]
>  Web developers should not set the ARIA role and aria-* attributes to values that match the default implicit ARIA semantics defined in the table.

Quoted from the [W3C working draft about ARIA in HTML](http://www.w3.org/TR/html-aria/#document-conformance-requirements-for-use-of-aria-attributes-in-html).

The default implicit ARIA semantics should not be used in the markup.

PR #890

**Comment by sixhours** [comment]
This looks good to me. +1 for merging #890

**Comment by mrwweb** [comment]
I was a little skeptical of this since the accessibility APIs of browsers used to be behind on this, but I think it's ok at this point.

From [HTML5Doctor](http://html5doctor.com/on-html-belts-and-aria-braces/):

> Given the more robust support for structural element semantics (sans the outline algorithm aspect, but that’s another orthogonal story) I consider web developers should think about dropping the legacy HTML belt and ARIA braces approach.

> This does not mean you can’t continue to, but is meant as a discouragement (think deprecation rather than obsolescence). So in the near future, if you check your HTML using a conformance checker, a warning will be flagged where it finds ARIA roles matching the default implict semantics of HTML elements.

This may impact the accessibility of older versions of IE, but that's beyond my knowledge. Getting a final opinion on this one might be useful.

**Comment by mrwweb** [comment]
2nd opinion found, possibly. The [A11y Project updated their guidelines](http://a11yproject.com/posts/aria-landmark-roles/) on this just a few days ago:

> The good news is most modern desktop browsers (except IE) support this mapping [of html5 structural elements to their implied ARIA roles]. However, iOS Safari does not. OUCH! For now, it’s probably best to implement the landmark roles and ignore these warnings.

Here's the relevant issue on the project: https://github.com/a11yproject/a11yproject.com/issues/357

**Comment by benoitchantre** [comment]
@mrwweb, thanks for your feedback and this useful link.

I think we can close this issue and ignore the related pull request.

**Comment by mrwweb** [comment]
Sounds good. I do think this change should eventually be made, but it's probably ~1 year early. Luckily, other than a minor developer annoyance, I can't think of any reasons leaving the roles *hurts*, so I think caution is the right approach.

**Comment by davidakennedy** [comment]
We also discussed here, and came to same conclusion. Just dropping in link for reference. #786
