### ISSUE TITLE
Two Comment Errors

### ISSUE THREAD

**Issue by WPAddiction** [Automattic/_s#891]
If you download _s from http://underscores.me/ and run Travis CI with the custom name, it picks up two comment errors. The errors are found in functions.php (line 80) and custom-header.php (line 74). Checkout the repo at https://github.com/WPAddiction/test and the Travis CI log at https://github.com/WPAddiction/test/blob/master/log.txt. I assume it doesn't pick them up in _s because of the underscore. I didn't create a pull request because I'm not sure what the rules are around comments.

**Comment by davidakennedy** [comment]
Thanks for the issue.

You're right, as far as I know. In your themes, if you were setting up Travis, you could tell it to ignore those rules. However, for _s, I don't think we need to worry about it.

**Comment by WPAddiction** [comment]
Just thought you guys would want it to be technically correct. Also thought it would be good to have it ready for others to use without having to make changes.

**Comment by obenland** [comment]
Let's just fix it.
