### ISSUE TITLE
Wordpress editor css problem

### ISSUE THREAD

**Issue by erfanatp** [Automattic/_s#901]
I used last version of _s package. But I see a problem in Editor css for rtl language. The problem is text overflow from the editor box.
I tried to fix it by adding `editor-style.css` from Twenty Thirteen Theme and adding 
```
add_editor_style( array( 'css/editor-style.css' ) );
```
in function.php
But it's not perfect.

**Comment by dhulwells** [comment]
I think this could be fixed by uncommenting the CSS in the rtl.css file in the theme root.

**Comment by erfanatp** [comment]
My problem still exist....

**Comment by erfanatp** [comment]
According to this [link](https://core.trac.wordpress.org/ticket/33868), our problem fixed. That was wp bug, not underscore.
