### ISSUE TITLE
Bad HTML markup in template-parts/*

### ISSUE THREAD

**Issue by bounasserabdelouahab** [Automattic/_s#916]
I found that all the `template-parts` files contain this line of code:
```php
// this is how it's written:
the_title( '<span class="screen-reader-text">"', '"</span>', false );

// this is how it should be:
the_title( '<span class="screen-reader-text">', '</span>', false );
```
the first argument of `the_title()` contains an extra double quote at the very end, and the second argument contains one at the very beginning, is it a design decision, too? just like the last CSS issue I added? which made me puzzled for hours to figure it out, when one guy said it's not an issue it's just a design decision, thank you :-)

**Comment by mindctrl** [comment]
This appears to be on purpose, to wrap the title in quotations. @davidakennedy committed that and could give us some insight.
