### ISSUE TITLE
SEO improvement : remove H2

### ISSUE THREAD

**Issue by redpik** [Automattic/_s#919]
There is unnecessary (and irrelevant) _H2_ in the theme.
Ex: _comments-title_, _widget-title_.

I think we should replace it with _span_ or _div_, with for example a .title class.

**Comment by sixhours** [comment]
Can you point us to a resource or resources that back up your reasoning?

**Comment by redpik** [comment]
it's just... SEO logic!
example: you have a single page with h1 (the title), and few h2 & h3 in the content. These Hn are relevant.
BUT imagine in this single page you have a sidebar with 5 widgets: you have now 5 extra 	
incongruous H2 (example: "follow us", "contact", "categories", "facebook", .....).
Do you need to be SEO compliant with the term "follow us" or "last comments"?

(sorry for my english, I'm french)

**Comment by synthetiv** [comment]
Highlighting SEO keywords is hardly the main (or only) purpose of the <h...> tags. They're used to label/delineate sections of a page, creating a semantic document structure. Improved SEO is one benefit of semantic HTML; another important one is accessibility for visually impaired users using screen readers, etc.

Look at the source of this page. "Labels," "Milestone," "Assignee" are H3 tags.

**Comment by davidakennedy** [comment]
Hey there, @redpik!

Thanks for filing this issue and sharing your thoughts.

I don't see how having less `h2` headings would impact or improve SEO at all.

However, switching away from headings to a `span` or `div` would be a move away from semantic HTML structure, as a `span` or `div` carries no meaning in HTML. So as an example, we'd lose some accessibility benefits, like screen reader users being able to navigate between widget areas by their heading level. So I don't think we should change the heading levels in this case.

The structure in a theme can't be perfect in all use cases, so theme authors do their best to balance it for as many of the important use cases as possible. Remember, this is a starter theme, so if you need to alter it for your own needs, go for it. :smile:

**Comment by sixhours** [comment]
DK makes a good point about harming accessibility by moving away from semantic markup. I'm going to close this.
