### ISSUE TITLE
Theme _s not found on WordPress GlotPress

### ISSUE THREAD

**Issue by carlmorris** [Automattic/_s#920]
Any plans to add _s to the GlotPress system at https://translate.wordpress.org/ please?

I can then import a completed language straightaway (Cymraeg / Welsh). :-)

**Comment by grappler** [comment]
There are no plans but you can contribute the translations to the collection of translations. https://github.com/ptbello/_slated

**Comment by jrfnl** [comment]
AFAIK: As strings are shared between themes in GlotPress, once in, you'll probably find your project translated in numerous languages automatically.

**Comment by sixhours** [comment]
I don't think we can add _s to the WordPress.org translations system since it's not a theme in the repository, but contributing to the above is a good idea!
