### ISSUE TITLE
Static _s Endpoint

### ISSUE THREAD

**Issue by johncionci** [Automattic/_s#921]
Is there a endpoint for the static version of _s? I would like to add this the static version of the theme through my package manager such as bower or composer.

**Comment by davidakennedy** [comment]
@johncionci Hey there! What do you mean by static version? You can grab everything via Github if you like – there aren't separate versions maintained anywhere.

**Comment by johncionci** [comment]
By "static" I meant any version that does not include SASS, contributing docs, and codesniffer rules like what can be generated on underscores.me. Im trying to not manually have to grab the theme from underscores.me each time I have a new project and just download it automatically through my installer script.

**Comment by davidakennedy** [comment]
Got it, we don't. You'd have to automate that in some way yourself.

**Comment by grappler** [comment]
Here are some cli options that you could use.

https://www.npmjs.com/package/underscores
http://evansolomon.me/notes/wordpress-themes-on-the-command-line/
http://coderrr.com/generate-a-custom-_s-underscores-wordpress-theme-from-command-line/

**Comment by johncionci** [comment]
Great! thanks guys, much appreciated!

**Comment by ruslangallo** [comment]
@johncionci add in your `composer.json`:

```
{
    "repositories":[
        {
            "type": "package",
            "package": {
                "type": "wordpress-theme",
                "name": "automattic/_s",
                "version": "1.0.0",
                "source":{
                    "type": "git",
                    "url": "https://github.com/automattic/_s",
                    "reference": "master"
                }
            }
        }
    ],
    "require": {
        "automattic/_s": "1.0.0"
    }
}
```

And run:

```
$ composer update
```

Maybe you already know it)
