### ISSUE TITLE
Site Logo Support for WordPress 4.5

### ISSUE THREAD

**Issue by WPAddiction** [Automattic/_s#922]
I would like to see _s follow Twenty Sixteen and add Site Logo Support for WordPress 4.5. I haven't gotten a chance to look to close at what's going on, but it looks like Twenty Sixteen has already added this for their upcoming 1.2 release.

https://github.com/WordPress/twentysixteen/commit/2776edd19ce3757359ab98755faff6161362b71c

https://make.wordpress.org/core/2016/02/24/theme-logo-support/

**Comment by sixhours** [comment]
Big +1 for this!

**Comment by mtomas7** [comment]
Code should be updated as after some changes logo size now should be passed via add_theme_support, see: https://github.com/WordPress/twentysixteen/commit/ba08079cd0795c05b3d955893a0c8156f7c1c0ad
