### ISSUE TITLE
Don't style hatom classes

### ISSUE THREAD

**Issue by mrwweb** [Automattic/_s#930]
There are many places where hAtom classes ([`hentry`](https://github.com/Automattic/_s/blob/d40faf1e4517173d9745b7697cffcac2fb61a22b/style.css#L779), [`entry-summary`](https://github.com/Automattic/_s/blob/f6ddaaa21ef562fe85881f7e3cc5bdd1e592bb0e/sass/site/primary/_posts-and-pages.scss#L21), [`entry-content`](https://github.com/Automattic/_s/blob/f6ddaaa21ef562fe85881f7e3cc5bdd1e592bb0e/sass/modules/_clearings.scss#L3), [`updated`](https://github.com/Automattic/_s/blob/f6ddaaa21ef562fe85881f7e3cc5bdd1e592bb0e/sass/site/primary/_posts-and-pages.scss#L10), etc.) are being styled, often without any qualifying, parent selectors.

Plugins are well within their "rights" to output these classes, yet `_s` encourages writing CSS that applies to very generic elements which a theme cannot possibly predict the use of accurately. As an example of not doing this, The Events Calendar has slowly but surely removed their styles for these elements as they conflicted with themes. `_s` is likely causing the same problem in reverse.

I'm not sure what the best way forward is (possibly utility classes like `clear` and `top-margin` that fill the same styling role?), but I want to raise the issue.

**Comment by dshanske** [comment]
I had commented on this, using the terms microformats, as opposed to hAtom. And Semantic markup. I agree that a CSS class used to indicate a semantic division should not be used for style.

**Comment by mrwweb** [comment]
See also: #428, #829

**Comment by dshanske** [comment]
I also suggested it be a theme recommended practice in the development handbook

**Comment by sixhours** [comment]
Also see #860

**Comment by karmatosed** [comment]
I kind of agree with this and kind of don't think in all cases. I'd potentially argue against all hAtom cases, I think it's interpretative. What is the full list you are thinking of culling/adjusting @mrwweb?

**Comment by mrwweb** [comment]
First, in previous tickets, the general agreement seems to have been that hAtom isn't going anywhere. I'd generally say that most themes I see use it.

Second, the places I'd want to remove those styles are the links in the OP. There may be a few more but they would all be similar in that they are single-class hAtom selectors that are likely to match classes used by existing plugins. and apply clears/margins/padding that may be undesirable.

My preference is that those rules just be completely removed, but if the styles are judged to be essential, they should be replaced with a custom class-naming scheme that is _s specific.

**Comment by philiparthurmoore** [comment]
I'd strongly +1 this.

**Comment by davidakennedy** [comment]
I'd be in favor of this.

> they should be replaced with a custom class-naming scheme that is _s specific.

I'd prefer we'd not do that. if we can help it. May not be possible, but it would cool if there other ways around this, like removing them entirely like @mrwweb suggested, or putting the styles on another existing class.

I'm wondering if we also include a note somewhere about _why_ we're not styling these classes? I know when I first started using themes with these classes, I had no idea they were used for a specific purpose like Microformats, etc. It's also pretty unrealistic that all themers won't use these. If Core outputs the class, it'll get used somewhere. 😄

**Comment by dshanske** [comment]
Is there anywhere in the Theme Development handbook this could go?

**Comment by grappler** [comment]
Two places where this could be documented in https://developer.wordpress.org/reference/functions/post_class/ and https://developer.wordpress.org/themes/functionality/sticky-posts/#style-sticky-posts

**Comment by davidakennedy** [comment]
Closing in favor of the path outlined in #1268. Which is basically the approach outlined here with a few more details.
