### ISSUE TITLE
Finding navigation codes

### ISSUE THREAD

**Issue by robertnicjoo** [Automattic/_s#934]
Hi,
I'm looking for navigation links codes, where can I find those?
![untitled](https://cloud.githubusercontent.com/assets/8672823/13561233/27cc46b0-e45d-11e5-9da3-94553d6c4038.png)

Thanks.

**Comment by slushman** [comment]
I believe that's from the_posts_navigation(), which is part of WordPress core.

https://developer.wordpress.org/reference/functions/the_posts_navigation/

You can use an array with arguments to customize the text for those links. the_posts_navigation() is a wrapper function for get_the_posts_navigation():

https://developer.wordpress.org/reference/functions/get_the_posts_navigation/

**Comment by robertnicjoo** [comment]
@slushman Thanks for reply but what I need is located of those codes in my theme so even if I want to change it with my own codes can if i just add my codes will be duplicated like this!

**Comment by MonikaTS** [comment]
Hi Robert
try to follow the links from Slushman and you will notice that there is no "duplicate" anywhere.

**Comment by sixhours** [comment]
`the_posts_navigation()` function is located in archives and index templates in _s. Closing, as this isn't an issue with the theme.
