### ISSUE TITLE
Why the comment textarea first?

### ISSUE THREAD

**Issue by nonsensecreativity** [Automattic/_s#939]
![unsc](https://cloud.githubusercontent.com/assets/14862032/14131527/54a2e9e4-f666-11e5-9b49-b70107764f81.png)

It's plain unmodified underscores theme, why is the comment form reversed starting from "comment" box first? I checked the functions files there aren't any codes that change the comment_form output.

    I'm running on WP 4.4.2
    No plugin activated
    Underscores theme freshly generated from underscores.me

Is this a feature? or a bug?

**Comment by sterndata** [comment]
It's a feature of WP 4.4

https://make.wordpress.org/core/2015/09/25/changes-to-fields-output-by-comment_form-in-wordpress-4-4/

**Comment by nonsensecreativity** [comment]
OMG, just realized this feature for so long, is there a work around to switch it back?

**Comment by sixhours** [comment]
You can customize the display using hooks/filters: http://ottopress.com/2010/wordpress-3-0-theme-tip-the-comment-form/

Closing as this isn't an _s issue.
