### ISSUE TITLE
Layouts folder

### ISSUE THREAD

**Issue by grappler** [Automattic/_s#945]
When doing reviews on w.org I see a number of themes that use _s and they do not remove the layouts folder if they are not using it.

I feel that the layouts would fit better in the [Theme Components Library](https://github.com/Automattic/theme-components). We could even add a link to it in the documentation.

**Comment by sixhours** [comment]
Adding layouts to Components is on the roadmap, but I don't see a strong need to remove them from _s in the meantime.

**Comment by karmatosed** [comment]
I'd +1 to not removing them. We can't be responsible for what someone does or doesn't remove before release their theme.

**Comment by grappler** [comment]
Do you know if they are being used or do you use them internally? :smile:

**Comment by karmatosed** [comment]
I've known of a lot of cases where users have used them, yes.

**Comment by grappler** [comment]
Ok, thats great! Fine with me. :smile:
