### ISSUE TITLE
To bring back content-single.php

### ISSUE THREAD

**Issue by emiluzelac** [Automattic/_s#948]
I am looking at this old commit https://github.com/Automattic/_s/commit/60f7311f1977179822e83c95745fa6787894959a and understand that at that time this was probably ok idea, however going by .org and Marketplace, in big majority authors are creating `content-single.php`, including https://github.com/WordPress/twentysixteen/blob/master/template-parts/content-single.php, https://github.com/WordPress/twentysixteen/blob/master/single.php#L19

What do you guys think, should we follow Twenty Sixteen's example?

**Comment by sixhours** [comment]
What's the reasoning for doing this, besides Twenty Sixteen having it?

It definitely has its place in some themes, but I haven't missed it in my own workflow, so I'm not convinced.

**Comment by emiluzelac** [comment]
It looks like you guys are using it in new themes as well:

- https://themes.svn.wordpress.org/orvis/1.0.4/template-parts/content-single.php
- https://themes.svn.wordpress.org/escutcheon/1.0.2/components/content-single.php
- https://themes.svn.wordpress.org/cols/1.0.1/content-single.php
- https://themes.svn.wordpress.org/lyretail/1.0.1/content-single.php

For advanced folks this is not an issue, but for those that are not, content-single.php is super helpful. 

Majority of the themes I see on .org and Marketplace will add content-single.php there must be something to it :)

**Comment by sixhours** [comment]
FWIW, Cols & Lyretail were created before _s removed `content-single.php`, and Escutcheon was generated from an older version of [Components](http://components.underscores.me), which no longer uses `content-single.php`, either.

**Comment by emiluzelac** [comment]
Cool, I was just wondering.

Happy Friday!
