### ISSUE TITLE
Remove Title Attributes from Social Links Widget

### ISSUE THREAD

**Issue by mrwweb** [Automattic/_s#951]
The Title attributes on those links are redundant with the screen reader text, don't work on touch devices, and generally aren't great. WordPress is moving toward removing all title attributes and Jetpack should do the same!

**Comment by grappler** [comment]
@mrwweb There are no Widgets in `_s` theme. Did you get the wrong repo by chance and wanted to post this in the Jetpack repo?

**Comment by mrwweb** [comment]
Doik. Yup. Intended for Jetpack. My apologies. Feel free to close.
