### ISSUE TITLE
structuring the html with the sidebar so that there can be a full width title

### ISSUE THREAD

**Issue by saltnpixels** [Automattic/_s#954]
The way the html is formatted right now we have #primary (with main inside) and #secondary.
This works out great if the site your making goes straight down.
But if one wanted to have them side by side -with a sidebar, there are some aesthetic issues.

Right now you can simply float primary and secondary next to each other.
But what if you wanted the title of the single article, and maybe a featured image, to be above the content and sidebar and have it be full width?
The current html structure makes this difficult. I have to resort to making changes. A lot of them.

Because the article is inside primary and its floated to the left while the sidebar is to the right, there is no way of having a full screen header from *within* the article (loop), where the h1 should really be, without resorting to major css hacks. 
Or completely changing the html structure which is difficult when it is throughout the theme files.

Here is a  visual explanation:
<img width="685" alt="screenshot 2016-05-12 12 28 08" src="https://cloud.githubusercontent.com/assets/11615474/15222389/6248a3e2-183d-11e6-8298-7bdb9cb7a645.png">

Here is one hack I came up with via css. I have another hack which is better, but of course rearranging the html would probably be best.
http://codepen.io/saltnpixels/pen/RaxLGO

Not sure if this is considered an issue or food for thought...

**Comment by phoenixenero** [comment]
Here's how I do it:

![ss 2016-05-13 at 08 07 15](https://cloud.githubusercontent.com/assets/9031092/15234193/c357deb0-18e1-11e6-9c00-8bb3954c7582.png)

![ss 2016-05-13 at 08 09 43](https://cloud.githubusercontent.com/assets/9031092/15234235/1f7449d6-18e2-11e6-8941-0278d5b73d09.png)

![ss 2016-05-13 at 08 07 15](https://cloud.githubusercontent.com/assets/9031092/15234232/19f5bbfc-18e2-11e6-97ef-16dae2b8c402.png)

**Comment by saltnpixels** [comment]
thanks for the reply!
But then your header is outside the the main and the article. Not sure if thats bad for SEO or what not.
And you can't use loop tags because your outside the loop, so you'll need to rely on $post->id.

right now i use javascript to put it in that same exact spot.
I guess its the best way for now.

**Comment by philiparthurmoore** [comment]
This isn't really an issue. Just change the HTML. 😄 

> right now i use javascript to put it in that same exact spot.

That seems like overkill to me. Why not just change your HTML and work with `$post->ID`?

**Comment by saltnpixels** [comment]
that involves a lot of changes to html.
and if you want your h1 inside the article with the content, its even harder

**Comment by phoenixenero** [comment]
The loop is pretty much unnecessary for single posts/pages, though it is still recommended to put _atleast_ one, so the "loop_end" action will fire. Say, some plugin wants to add some stuff after the loop. It won't make any sense to add it _after_ the header.

**Comment by emiluzelac** [comment]
I'll agree with @philiparthurmoore here, this also falls into a personal need project :)

**Comment by saltnpixels** [comment]
@phoenixenero thats interesting to know.
 
@emiluzelac, well i thought that if I use _s a lot, and i change the html a lot, maybe others are having the same issue.

I guess not... :)
in the end, is it bad to have the articles h1 outside of the article tag? I guess thats my main issue.

**Comment by emiluzelac** [comment]
As far as the SEO? I don't believe so, codes are semantically correct.

**Comment by saltnpixels** [comment]
ok, so in the end, I can use the global $post->ID on single pages and posts and put that outside the loop and above #primary without making a fuss?

and i shouldn't worry about having the h1 tag for the article be above the article itself, nor resort to using javascript to append it out?

im learning a lot here.... :P

**Comment by philiparthurmoore** [comment]
Here's an example from [one](https://corporatethemedemo.wordpress.com/) of our themes:

```php
<?php
/**
 * Note: If you're viewing this file from the WordPress theme editor
 * and would like to make changes, do not make direct edits to
 * this file; create a child theme instead. This will ensure that updates
 * to Corporate will not erase your edits upon upgrade.
 *
 * For more information on creating child themes, consult the
 * following page: https://codex.wordpress.org/Child_Themes
 *
 * Description: The template for displaying single post heroes within Corporate.
 *
 * @see     function corporate_entry_meta
 * @see     function corporate_hero_background
 * @see     function have_posts
 * @see     function the_post
 * @see     function the_title
 * @see     function rewind_posts
 * @package Corporate
 * @since   Corporate 1.0
 */
while ( have_posts() ) : the_post(); ?>

<section id="single-header" <?php corporate_hero_background( $post, 'corporate-page-hero' ); ?>>
	<div class="single-liner">
		<div class="grid">
			<div class="row">
				<div class="twelve column">
					<?php
						the_title( '<header class="entry-header"><h1 class="entry-title">', '</h1></header>' );
						corporate_entry_meta();
						edit_post_link( esc_html__( 'Edit', 'corporate' ), '<span class="edit-link">', '</span>' );
					?>
				</div><!-- .twelve -->
			</div><!-- .row -->
		</div><!-- .grid -->
	</div><!-- .single-liner -->
</section><!-- #single-header -->

<?php
	endwhile;
	rewind_posts();
?>
```

Here's another example from another theme:

```php
<?php
/**
 * Note: If you're viewing this file from the WordPress theme editor
 * and would like to make changes, do not make direct edits to
 * this file; create a child theme instead. This will ensure that updates
 * to Business Identity will not erase your edits upon upgrade.
 *
 * The header portion of pages, including hero images and page titles.
 *
 * For more information on creating child themes, consult the
 * following page: https://codex.wordpress.org/Child_Themes
 *
 * @package Business_Identity
 * @since   Business Identity 1.0
 */

global $post;
$page_id = $post->ID; ?>

<?php
if ( isset( $page_id ) && has_post_thumbnail( $page_id, 'business-identity-page-hero' ) ) :
	$page_hero = wp_get_attachment_image_src( get_post_thumbnail_id( $page_id ), 'business-identity-page-hero' );
?>
	<section id="page-hero"><img src="<?php echo esc_url( $page_hero[0] ); ?>" /></section>
<?php endif; ?><!-- #page-hero -->

<?php business_identity_breadcrumbs(); ?>

<?php if ( isset( $page_id ) && '' != get_the_title( $page_id ) ) : ?>
	<section id="page-header">
		<div class="grid">
			<div class="row">
				<div class="twelve column">
					<h1>
						<?php echo get_the_title( $page_id ); ?>
					</h1>
				</div><!-- .twelve -->
			</div><!-- .row -->
		</div><!-- .grid -->
	</section><!-- #page-header -->
<?php endif; ?><!-- #page-header -->
```

Some of that old [Business Identity](https://businessidentitydemo.wordpress.com/) code could probably be refactored (I'm sure of it). I'm not the biggest fan of using `$post->ID` if I don't have to. If I have to, fine.

Is my code SEO-perfect? I have no clue. Do I have some divitis going on there? Yep - generally modular development requires it for grid-based designs that need proper clearing. Do I care? Yes, but I'm not willing to use JavaScript for something as minor as outputting a post or page title in WordPress. Using JS for something like that just seems silly and not that performant.

What I do know is that [Subtitles](https://wordpress.org/plugins/subtitles/) works beautifully inside the loop and needs [custom template tags](https://github.com/professionalthemes/Subtitles#using-template-tags) outside of it, so I'm fine with the first block and hate the second, but the second was made several years ago.

I know there are people concerned about SEO, and getting as much perfection into your themes as possible with regard to HTML structure and markup, but there comes a time when content dominates and the lessons one might learn from a site like [Moz](https://moz.com/) come far more in handy than messing with your markup via JavaScript for a minor gain that might have even more major setbacks with regard to performance or page rendering.

And in the case of _s, I just don't see a reason to change anything about how it's done. Roll your own markup because _s as-is is fine.

**Comment by saltnpixels** [comment]
alright. thanks.
I guess I'll do something like that.
