### ISSUE TITLE
Enable touch support for nav menu links with subitems as seen in TwentySixteen

### ISSUE THREAD

**Issue by mtomas7** [Automattic/_s#957]
I'm sorry that I cannot directly contribute to this one as my JS skills are very poor. The problem is that normal menu (didn't test with mobile) cannot handle touch events for menu items that are links themselves.

To reproduce this, create a menu item (link to page, cat, etc.), add subitem, then try to expand the menu on a tablet. After clicking on menu item (link) submenu will be displayed for a very short time, until browser is redirecting to the parent item link.

This problem is solved in Twenty Sixteen and JS code is very similar. I was trying to make some changes to no avail :(

Another possible solution could be this:

http://osvaldas.info/drop-down-navigation-responsive-and-touch-friendly

There are [some](https://github.com/KrissieV/mobile-nav-dropdowns-for-underscores/blob/master/js/mobile-nav-dropdowns.js) [more](https://github.com/tutsplus/wordpress-theme-creation-with-underscores/blob/master/4.%20Customizing%20Theme%20PHP%20Files/4.2%20Add%20Touch%20Friendly%20Responsive%20Menu/navigation-custom.js) [code](http://krissievandenoord.com/portfolio/mobile-nav-dropdown-usability-for-underscores/) samples, but of course I would vote for the Twenty Sixteen implementation as we would have similar code among WP themes. Perhaps others already have some good working solutions?

Thank you!

**Comment by pixelstrolch** [comment]
+1

**Comment by sixhours** [comment]
This should be handled in #666; the proposed patch needs testing.

**Comment by sixhours** [comment]
#962 is the correct, most recent patch without conflicts.

**Comment by mtomas7** [comment]
It works on Nexus 7 Chrome! :+1:

**Comment by sixhours** [comment]
This has been fixed and merged in #900.
