### ISSUE TITLE
Only delete transient when post types that have the category taxonomy are saved

### ISSUE THREAD

**Issue by emhr** [Automattic/_s#959]
The  s_category_transient_flusher deletes the transient on the action "save_post" which will run whenever any post type is saved (pages for example).

This should be limited to posts only since categories are a taxonomy of posts.
#956  This PR narrows the focus to posts only using the

save_post_{post_type} hook which has been around since WP 3.7

**Comment by emhr** [comment]
The patch is in the pull request i mentioned which is:  #956

**Comment by grappler** [comment]
A possible issue could be if there is a custom post type that uses categories instead of a custom taxonomy.

**Comment by emhr** [comment]
I see that now. 

Added s_queue_transient_flusher to check all registered post types. And queue the add_action for save_post_{post_type} only if a post type has the category taxonomy.

I've hooked it late on init in case plugins are registering post types.

**Comment by davidakennedy** [comment]
Thanks for the issue @emhr! I'm closing this out, as we removed this function as part of #1131.
