### ISSUE TITLE
Custom post template is not used for the single page template

### ISSUE THREAD

**Issue by rainman20** [Automattic/_s#974]
In the sinlge.php we have 

```
get_template_part( 'template-parts/content', get_post_format() );
```

I have a post type called `shopping` and I created a template in the template-parts (content-shopping.php) but it is not used for posts which are of type shopping. The `content.php` is used for all of them. Any idea?

**Comment by slushman** [comment]
get_post_format is looking at the post format (chat, standard, audio, etc), not post types. It wouldn't work in this case.

[Post Formats Codex page](https://codex.wordpress.org/Post_Formats)

You could do something like:

`get_template_part( 'template-parts/content', 'shopping' );`

However, the get_post_formats() function only works with the standard, built-in WordPress post formats.

**Comment by rainman20** [comment]
@slushman yes, it appears that I was a little bit impatient and I assumed I have defined the post format. 
another solution would be using `get_post_type` instead of the format (in my case).
