### ISSUE TITLE
Is there a script available that performs the needed steps described in README.md?

### ISSUE THREAD

**Issue by COLABORATI** [Automattic/_s#977]
In the readme there are instructions on how to setup this theme (replacing _s and so on) - however, I would like to use this theme on a modern computer and therefore it seems a little bit odd to me that I have to manually do things to use it - certainly there is a script or a wpcli plugin that will do this for me? 

I just would like to be sure that the neccessary steps are done in the right way before using this starter theme - a script would be a good place to conserve the needed steps in a way that prevents me (and others) from doing errors.

**Comment by samikeijonen** [comment]
In the [readme file](https://github.com/Automattic/_s#getting-started) there is also link to [underscores.me](http://underscores.me/).

**Comment by biringanya** [comment]
You can setup the basics by using the generator there: http://underscores.me/




Xavier Moya
PD: Escrit des del mòbil! On Mon, Jun 27, 2016 at 1:49 PM, COLABORATI < notifications@github.com [notifications@github.com] > wrote:
In the readme there are instructions on how to setup this theme (replacing _s and so on) - however, I would like to use this theme on a modern computer and therefore it seems a little bit odd to me that I have to manually do things to use it - certainly there is a script or a wpcli plugin that will do this for me?

I just would like to be sure that the neccessary steps are done in the right way before using this starter theme - a script would be a good place to conserve the needed steps in a way that prevents me (and others) from doing errors.

**Comment by David-Brown** [comment]
There's a WP CLI command: https://wp-cli.org/commands/scaffold/_s/

**Comment by davidakennedy** [comment]
Hey @COLABORATI,

As others have mentioned, head over to http://underscores.me/ and fill out the form. A script takes care of the rest. Happy theming!
