### ISSUE TITLE
Skip to content link styles

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#982]
In `header.php` there is skip to content link: `<a class="skip-link screen-reader-text" href="#main"><?php esc_html_e( 'Skip to content', '_s' ); ?></a>`. Link `href` is for ID `#main`.

But in `style.css` there is styles for ID `#content`.

```
/* Do not show the outline on the skip link target. */
#content[tabindex="-1"]:focus {
	outline: 0;
}
````

Should styles also be for `#main`?

**Comment by grappler** [comment]
@samikeijonen Is this related to https://github.com/Automattic/_s/issues/928?

**Comment by samikeijonen** [comment]
In some sense yes. Here is commit 0f81201b5364c5c3d343c61e4b2af3c2101b5140 for changing to `#main`.

**Comment by davidakennedy** [comment]
Doubling back here to say I fixed this in: https://github.com/davidakennedy/_s/commit/44f41babcd13909a3da647aab23a7abe1a70a943

See the commit message – we shouldn't have changed the `id` in that old commit.
