### ISSUE TITLE
License of this project?

### ISSUE THREAD

**Issue by p0o** [Automattic/_s#987]
I didn't find a license file in the root directory. Is it specified yet? Wondering if I can use some of the codes in this great repository in an open source project? Surely with a back link and mentioning the name of this repository.

Let me know please, thanks.

**Comment by grappler** [comment]
> Licensed under GPLv2 or later. :) Use it to make something cool.
from the `README.md`

or you can see the licence in the `style.css`

**Comment by philiparthurmoore** [comment]
Why not just include a license file and make it easy on people? Not sure how I ever missed the fact that no license file is in this repo.

**Comment by karmatosed** [comment]
I'm not against including an explicit file but I would say we are covered in what we have. If someone wants to do a PR, that's a solid start.

**Comment by josephfusco** [comment]
IMO it is redundant. As someone who uses _s, I would just delete when building themes. It is just adding another file.

Note that all twenty* themes do not include it but rather link to the GPL like we do here.

**Comment by philiparthurmoore** [comment]
> Note that all twenty* themes do not include it but rather link to the GPL like we do here.

That's a good argument. Maybe close this out then? Core themes don't have them so I agree that it does feel redundant.

**Comment by jrfnl** [comment]
AFAIK: GPL is only valid if distributed with the code as it states in the actual license.

**Comment by josephfusco** [comment]
https://www.gnu.org/licenses/gpl-faq.en.html#WhyMustIInclude
>It might be tempting to include a URL that refers to the license, instead of the license itself. But you cannot be sure that the URL will still be valid, five years or ten years from now. Twenty years from now, URLs as we know them today may no longer exist.

So as it stands it is valid, just not completely future proof.

**Comment by philiparthurmoore** [comment]
God forbid we are still using this theme in 10 years. Oh, the humanity. :smile:

I'll leave this up to the Automattic crew. It's not important enough to me to lean one way too heavily.

**Comment by jrfnl** [comment]
@p0o That depends on what the actual license says. This is fine for a lot of licenses, just not GPL.

@josephfusco You're quoting the reason why GPL made it a *requirement*. That does not negate the fact that it still is a requirement - see the actual question you question from "Why does the GPL require including a copy of the GPL with every copy of the program?".

**Comment by josephfusco** [comment]
@jrfnl I understand what you are saying, but the reasoning behind it is still only for future proofing access to the license. Legally, it is hard to believe only having a link will invalidate the license. If that is the case, there are a lot of themes & plugins, including core themes, that have an invalid GPL license.

Since WordPress core physically includes the GPL, and themes are an extension of that, surely that is adequate?

**Comment by folletto** [comment]
> You're quoting the reason why GPL made it a requirement. That does not negate the fact that it still is a requirement - see the actual question you quoted from "Why does the GPL require including a copy of the GPL with every copy of the program?".

As far as I know, it can't be a true "requirement" unless it's written in the actual license. So unless the GPL has this written within the GPL itself (does it?), they can write "required" as much as they want, but it's just a recommendation.

So going back to the actual reason this thread started:

> Is it specified yet?

This isn't about license coverage, but ease of discovery of which license is in use. Thus, adding a file would make it more easily found, as well as editing the readme to make it more prominent (usually license details are found at the very end or beginning of it), or any other similar solution.

I guess the first one that makes a PR will help making a choice on the specific design solution we choose to make it more discoverable. ;) 

Which was already a suggestion up there:

> If someone wants to do a PR, that's a solid start.

**Comment by philiparthurmoore** [comment]
Somebody make a PR. This seems like a net positive to me. Ease of discovery
is a fantastic way of putting it.

**Comment by josephfusco** [comment]
>This isn't about license coverage, but ease of discovery of which license is in use.

Alright I agree with that. :)
