### ISSUE TITLE
Site Title in the Customizer

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#990]
I know that this has been discussed several times. Just want to check is there a small bug with the Customizer setting `Display Site Title and Tagline`.
1. Disable `Display Site Title and Tagline` under Site Identity.
2. Site Title and Tagline gets hidden in the Customizer view and when visiting site as it should.
3. Go away from the Customizer and visit the site.
4. Go back to Site Identity and enable `Display Site Title and Tagline`.
5. Now in the Customizer only Tagline will appear but not Site Title.

This is because in `inc/custom-header.php` there is this CSS:

```
.site-title,
.site-description {
    position: absolute;
    clip: rect(1px, 1px, 1px, 1px);
}
```

But in the `js/customizer.js` there is this JS with `site-title a`:

```
$( '.site-title a, .site-description' ).css( {
    'clip': 'rect(1px, 1px, 1px, 1px)',
    'position': 'absolute'
} );

...

$( '.site-title a, .site-description' ).css( {
    'clip': 'auto',
    'position': 'relative'
} );
```

I tested this JS without `a` tag using only `site-title` and that worked.

Am I missing something here or is the original behaviour as it should be?

**Comment by davidakennedy** [comment]
I've run into this too. Will look at the PR.
