### ISSUE TITLE
Selective Refresh on Widgets

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#994]
Should `_s` have selective refresh enabled because it has sidebar? 

All it needs is [theme support](https://developer.wordpress.org/themes/advanced-topics/customizer-api/#widgets-opting-in-to-selective-refresh) for Core widgets.

**Comment by celloexpressions** [comment]
This should have been added as soon as WordPress 4.5 was released. I'm shocked that it's still sitting here with no action. The UX improvement is immense, and adding support will also bring visual edit icons for each widget in WordPress 4.7.
