### ISSUE TITLE
Selective Refresh on Site Title and Tagline

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#995]
Should `_s` have selective refresh on Site Title and Tagline in the similar way as Twenty 16?

Here is [other reference](https://developer.wordpress.org/themes/advanced-topics/customizer-api/#selective-refresh-fast-accurate-updates).

**Comment by celloexpressions** [comment]
Yes, and this is also required to show visible edit icons automatically in WordPress 4.7. Not difficult to add, but every theme needs it.

**Comment by karmatosed** [comment]
Anyone up for a PR?

**Comment by samikeijonen** [comment]
I can do PR in couple of days.

**Comment by samikeijonen** [comment]
@celloexpressions: can you check is this PR ok?
